### ISSUE TITLE
Design 5

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#1]
Bonjour,
Je viens de changer le nom de SpatGRIS 2 pour ControlGRIS. C'est donc ici qu'on va travailler pour mettre au point et maintenir le nouveau plugiciel.
Pour mémoire, mon dernier message sur le design de ControlGRIS.

Plusieurs commentaires.

**1. Représentation de l'élévation**
Je trouve que c'est une bonne idée, plutôt qu'un cadran.
Et je seconderais le commentaire de David au sujet du nombre de sources représentées.
On parle bien du ControlGRIS ici, et non pas du ServerGRIS.
Ce que cela implique, c'est qu'en général, et pratiquement pour toutes les situations, on aura au maximum 8 élévations à représenter (c'est la limite des DAW: fichier octophonique max).
Donc cela se case très bien dans un graphique comme celui-là.

**2. Compaction des différents éléments**
Une des situations les plus fréquentes en situation de travail est de pouvoir réduire la taille de la représentation graphique afin:
- de mettre le plus grand nombre de plugiciels dans l'écran;
- d'être capable de travailler avec une seule fenêtre sur un portable par exemple et que ça soit lisible.

Donc ma suggestion est de reprendre la logique du SpatGRIS, avec des onglets et des potentiomètres.

2.1. Onglets
Ainsi, Settings, Sources et Interfaces, qui devrait d'ailleurs être nommé Controllers plutôt que Interfaces, seraient présentés sous la forme de trois onglets successifs comme dans le SpatGRIS actuel.
Ces éléments sont des réglages passifs.
Un coup effectué, on n'a plus besoin d'y toucher ni même de les voir.

2.2. Elevation à la place des Output Parameters
Ces derniers étaient en fait des VU-Mètres.
Comme on abandonne l'audio, on n'en a plus besoin.
On pourrait alors remplacer ces derniers par le graphique Elevation.
Ainsi les deux cadrans seraient côte à côte plutôt que superposés.

2.3. Sources parameters et les Spans
Sources Parameters pourraient être placés à la droite du cadran Elevation.
Et les Spans pourraient être disposés:
- Azimuth Span à l'horizontale sous le cadran Elevation (pour des raisons pratiques: le cadran Azimuth-Elevation a besoin d'être extensible-rétractile)
- Elevation Span à gauche de Elevation (Elevation n'a pas besoin d'être ajustable en taille), à la verticale.
Cela fonctionnerait pour LBAP et VBAP.

**3. Détails divers**
3.1. Distance au lieu de Radius (comme déjà mentionné par Nicola) sur les potentiomètres
3.2. Majuscule et anglais partout
- Azimuth-Distance
- Azimuth-Elevation
- Le mot Elevation, parfois en français, parfois en anglais.

**4. Settings**
4.1. Number of sources: 36
Vraiment 36?
4.2. OSC Active
Je remarque que ce bouton est disparu.
Or c'est très utile de pouvoir fermer l'OSC d'une piste pour des questions de vérification et de test de temps à autre.

**5. Source Parameters**
C'est pourquoi le bouton X-Y-Z en haut à droite?
Et c'est quoi le chiffre 3?
La source sélectionnée?

Version Frankenstein:

![design 5 frankenstein](https://user-images.githubusercontent.com/8959779/47954901-896bc600-df66-11e8-8c7e-5be7e46bd52b.jpg)

**Comment by Normandeau** [comment]
Où sont passés les Movements? C'est une fonction fondamentale pour relier les sources entre elles.

**Comment by belangeo** [comment]
C'est le menu "Source link" dans la section Trajectories.
