### ISSUE TITLE
Elevation Source Link: seule la source 1 peut être manipulée?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#100]
Question: ne devrions-nous pas avoir le même comportement avec Elevation Link que l'on a avec Azimuth-Distance Link? C'est à dire que seule la source 1 peut-être manipulée? Avec le même message d’avertissement: «Only Source 1 can be selected in circular or symmetric link!». On s'entend bien que de toute manière seule la source 1 est enregistrée. C'est juste que ça me permettrait de faire la même mise en garde dans le manuel à propos d'Independent. Que ce mode en multicanal ne sert qu'à placer les sources indépendamment. Pas à les enregistrer de manière indépendante.

**Comment by belangeo** [comment]
Il y a aussi en delta lock que l'on peut manipuler toutes les sources. Est-ce qu'on ne peut pas faire la mise en garde à propos d'Independent tout en laissant l'utilisateur manipuler n'importe quelle source dans le second cadran? Les calculs sont déjà présents et fonctionnels...

**Comment by NicolaGiannini** [comment]
En fait je trouve plus intuitive la façon de manipuler le deuxième cadran, soit à partir de n'importe quelle source. J'admets que je n'avais pas noté cette différence entre les deux cadrans. Mais si cela prende beaucoup de temps de uniformiser les deux, on pourrait simplement l'expliquer dans le manuel.

**Comment by Normandeau** [comment]
Ok c'est déjà dans le manuel.
