### ISSUE TITLE
Elevation trajectory: Back & Forth encore utile?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#101]
V108
Il y a 4 trajectoires dans Elevation: Down Up, Up Down, Back & Forth Down, Back & Forth Up. Avec l'introduction de l'option Back & Forth pour toutes les trajectoires, je pense que ces deux dernières ne sont plus utiles. Non?

**Comment by Xon77** [comment]
En effet, Back & Forth Down et Back & Forth Up me semblent inutiles maintenant avec l'introduction de l'option Back & Forth.

**Comment by NicolaGiannini** [comment]
Je suis d'accord avec vous.

**Comment by Normandeau** [comment]
V109
Réglé
