### ISSUE TITLE
Port OSC par défaut

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#103]
V109
Christophe écrit:
«- "• Receive and Send should be set to different OSC channels (Default: 8000 and 9000)."
Il serait bien d'uniformiser ceci entre le Lemur et Open stage Control.
Le Lemur n'écoute exclusivement que sur le port 8000 (je ne peux le changer dans le Lemur). Donc, il serait peut être judicieux d'inverser ces 2 valeurs (port de réception 9000 et port d'envoi 8000)»
D'accord?

**Comment by NicolaGiannini** [comment]
Je pense que ce changement ne pose pas de problème en Open Stage Control.

**Comment by Normandeau** [comment]
Cela ne fait pas de différence en effet. Je viens de vérifier. J'ai ouvert cette issue juste pour qu'on change les valeurs par défaut dans ControGRIS.

**Comment by Normandeau** [comment]
V110
Réglé
