### ISSUE TITLE
Les Sources se placent en paires-impaires lorsque ControlGRIS est copié d'une piste à l'autre

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#104]
V109
Pistes octophoniques DP, Logic et Reaper.
Lorsque j'ai fait les tests «d'endurance» à 128 canaux (16 pistes octo), j'ai profité d'une fonction qui permet de copier un plugiciel d'un insert d'une piste à l'autre sans avoir à ouvrir une fenêtre chaque fois. Cette fonction est disponible dans les fenêtres de mixage de DP (Opt-glisser), Logic (Opt-glisser) et Reaper (Cmd-glisser). En faisant cela, on copie cependant les mêmes paramètres d'une instance à l'autre. Il faut donc les rouvrir une après l'autre et assigner des numéros OSC différents pour chacune d'elles. Puis de placer les sources à des endroits différents. Et là, bingo! Un nouveau bogue.
Lorsqu'on ouvre un ControlGRIS en octo, les sources se placent automatiquement en Left Alternate:

![Octo Left Alternate](https://user-images.githubusercontent.com/8959779/78069602-5fd7e980-7368-11ea-9734-37afd84e08c3.jpg)

Aussitôt qu'on clique sur la source 1, les sources se placent de cette manière: la source 1 reste à sa place et dans l'ordre CW, les autres sources impaires se succèdent, avec en vis-à-vis, les numéros pairs. Très étrange car cela ne correspond à aucun des modes disponibles sous l'onglet Source. Par ailleurs, si on ouvre plusieurs ControlGRIS octo séparément (donc sans les copier), on obtient un comportement normal.

![Octo paires-impaires](https://user-images.githubusercontent.com/8959779/78069688-80a03f00-7368-11ea-99a5-0c13878bfe17.jpg)

Ce n'est pas dramatique, mais comme dirait mon comptable (ou Revenu Québec...), une différence de 1 peut être une différence d'un cent, ou d'un million!

**Comment by Normandeau** [comment]
Même comportement en DOME ou en CUBE.

**Comment by Xon77** [comment]
J'obtiens la même disposition étrange sur Reaper...Il est nécessaire de re-valider le source placement, comme Left Alternate pour retrouver la bonne disposition.

**Comment by NicolaGiannini** [comment]
Bonjour,
j’ai fait quelque test,
en mode “Source Link” independent, apparement la copie est bonne. 

en mode Source Link”  “Circular” et “Circula Fixed Radius” lorsqu’on clique sur la source 1 j'obtiens :
![circular](https://user-images.githubusercontent.com/35705913/78466318-df015080-76cd-11ea-86ad-726924871e8b.jpeg)


en mode Source Link”  “Circular Fixed Angle” et “Circular Fully Fixed” j’obtiens le comportement décrit par Robert.

J'obtiens le mêmes comportements, si je copie la piste (command D en Logic).

**Comment by Normandeau** [comment]
V110
Non réglé

**Comment by NicolaGiannini** [comment]
Je confirme, non réglé.

**Comment by SamuelBeland** [comment]
1.1.2

Confirmer si réglé.

**Comment by NicolaGiannini** [comment]
V112 Il semble réglé dans mon cas. Maintenant quand je copie une piste, le placement des sources reste le même. À voir l'issue #111 .
