### ISSUE TITLE
Le Source Link ne fonctionne pas si on déplace la source avec les contrôles de l'onglet "Source".

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#106]
V110

Fichier stéréo
Source Link: Circular
Trajectory Type: Realtime

Je déplace la source 1 à partir des contrôles de l'onglet "Source", "Ray Lenght" et "Angle"
La source 2 ne suit pas la source 1.

Même chose avec tous les Source Link. 

Si j'utilise des autres Trajectory Type, avec le Source Link "Circular" et je déplace la source 1 à partir des contrôles de l'onglet "Source", j'obtiens des comportements glitchy.

**Comment by Normandeau** [comment]
Normal. L'onglet Source Link ne sert à déplacer qu'une seule source à la fois, comme c'est très clairement indiqué par le fait qu'on doive choisir une source en particulier dans Source Number:

![Capture d’écran, le 2020-05-18 à 09 48 44](https://user-images.githubusercontent.com/8959779/82220545-c8fdc700-98ec-11ea-9ada-5239b62eadee.jpg)

**Comment by Normandeau** [comment]
J'ajoute: positionner des sources manuellement ne fonctionne correctement que lorsqu'on est en mode Independent. On place d'abord la source 1, puis ensuite on choisit le Source Link. Peut-être qu'on devrait être plus explicite dans le manuel? Quoiqu'on indique quand même à trois endroits différents en caractère gras que seule la source 1 est automatisable et que les autres sources sont esclaves. Je viens tout de même d'ajouter une NOTE à l'item 3.3.2. Source pour la prochaine version du manuel.

**Comment by NicolaGiannini** [comment]
Bonjour,
j’ai signalé ce comportement parce que (ma faute !) j’ai toujours perçu la manipulation de “Ray Length” et “Angle” comme une version alternative et equivalente de la manipulation directe de sources avec la souris. 

Donc, en déplaçant la source 1, dans le cas de sources liées, je m'attendais à ce que les autres suivent le numéro 1. Mais en fait de cette façon, il est possible de changer le positionnement des sources liées, sans passer par Source Link Indipendent.
