### ISSUE TITLE
Flickering des sources en mode stop

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#108]
V111
Nicola:
Je remarque maintenant quelque chose qui ne se produisait pas auparavant:
Utiliser les Source Link Circular avec les Trajectory Type Circle, Ellipse, Spirale, Square et Triangle cause un flickering de sources, en les déplaçant. 
Le flickering se produit sur les sources, et sur les valeurs de Ray Lenght et Angle.
Voir la vidéo
https://www.dropbox.com/s/29r9q77o042d3sw/Flickering.mov?dl=0

Testé en mode DOME et CUBE, en Logic et Reaper.

**Comment by Normandeau** [comment]
V111
Je confirme l'observation de Nicola. Je viens de passer trois heures à comparer les versions 110 et 111 avec DP, Logic et Reaper. Ce comportement était inexistant dans 110 (et à ma connaissance dans les autres versions précédentes également).

Comportement normal, V110:
https://www.dropbox.com/s/pz8v7m319c6zsip/V110%20Mouvement%20manuel%20normal.mov?dl=0 

Comportement saccadé, V111:
https://www.dropbox.com/s/bdu4hm0xopn4uy5/V111%20Mouvement%20manuel%20saccad%C3%A9.mov?dl=0

**Comment by SamuelBeland** [comment]
1.1.2

Confirmer si réglé.

**Comment by NicolaGiannini** [comment]
V112
Testé en Logic et Reaper, dans mon cas c'est réglé.

**Comment by Xon77** [comment]
v112 Reaper : le flickering est réglé pour moi aussi.
