### ISSUE TITLE
Comportement très problématique en mode Touch

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#109]
V110-V111
Une autre chose qui nous a échappé avant la publication de la version officielle V110. Le mode Touch dans les trois séquenceurs testés, DP, Logic et Reaper fonctionne très mal lors de l'enregistrement des trajectoires. Remarquez le coté saccadé de l'enregistrement de l'automation en mode Touch. Je rappelle que le mode Touch enregistre des données tant et aussi longtemps qu'on bouge la souris ou qu'une valeur change dans le plugiciel. Si rien ne bouge, l'automation essaie de revenir à une valeur de référence. Ici c'est comme si les séquenceurs ne percevaient pas le mouvement de la courbe d'automation de manière continue et tentaient de revenir à une valeur de référence entre deux points d'écriture.
PS On pourra remarquer aussi que les courbes s’aplatissent avec la version 111. Cela fait l'objet d'une autre publication #105

Fully Fixed, Circle Clockwise

DP, Latch en haut, Touch en bas:
![DP V110-111 Latch vs Touch](https://user-images.githubusercontent.com/8959779/82588817-4897ca00-9b69-11ea-92c3-b6af22d6607d.jpg)

Reaper, Latch en haut, Touch en bas:
![Reaper V110-111 Latch vs Touch](https://user-images.githubusercontent.com/8959779/82588880-62d1a800-9b69-11ea-9c32-f279f66f942c.jpg)

Logic, Latch en haut, Touch en bas. On remarque qu'il n'y a rien dans Touch. Le mode Touch ne fonctionne pas dans Logic. Rien n'est enregistré. Il faudrait confirmer (V110 et V111):
![Logic V110-111 Latch vs Touch](https://user-images.githubusercontent.com/8959779/82588978-8137a380-9b69-11ea-88ae-5383aaa8af27.jpg)

**Comment by NicolaGiannini** [comment]
Bonjour, j’ai fait des tests. 
Dans Logic il n’y a pas de différence entre la version 110 et 111. J’arrive à enregistrer quelque chose, et je pense que le comportement est conforme à celui décrit par Robert : on a comme impression que la source est attirée par une autre position et que l'écriture de l’automation est discontinue. 

Une différence que je remarque entre Logic et Reaper est la suivante : si le séquenceur n'est pas en jeu, dans Logic Touch il semble fonctionner, dans Reaper il est problématique même si la séquence n'est pas en jeu.
Logic : https://www.dropbox.com/s/7w2pk9xs1ql2f6k/Touch_Logic.mov?dl=0
Reaper : https://www.dropbox.com/s/fqadmmid0903hjz/Touch_Reaper.mov?dl=0

De façon aléatoire dans Logic, après un certain temps d'utilisation du mode Touch, je reçois ce signal d'erreur Midi.

![midi-timeout](https://user-images.githubusercontent.com/35705913/83697231-7a2e7d80-a5cc-11ea-8b8c-39488781aef5.jpeg)

**Comment by belangeo** [comment]
> Une différence que je remarque entre Logic et Reaper est la suivante : si le séquenceur n'est pas en jeu, dans Logic Touch il semble fonctionner, dans Reaper il est problématique même si la séquence n'est pas en jeu.

La loop audio tourne toujours dans Reaper, même lorsque la séquence est arrètée, dans Logic, la loop audio roule seulement en mode play!

**Comment by SamuelBeland** [comment]
Merci pour le hint @belangeo, ça explique la disparité entre Logic et Reaper.

J'y jette un coup d'oeil...

**Comment by SamuelBeland** [comment]
1.1.2

Confirmer si réglé.

**Comment by NicolaGiannini** [comment]
v112
Testé avec Logic et Reaper, dans mon cas il semble réglé.

**Comment by Xon77** [comment]
v112 Reaper : le comportement problématique en mode Touch est réglé pour moi.

**Comment by Normandeau** [comment]
V113
Réglé dans  DP aussi
