### ISSUE TITLE
Bouton link : modifier la valeur relative (et non absolue) des autres sources

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ControlGris#11]
Au lieu de réinitialiser la valeur absolue des autres sources, lorsque l'on sélectionne un des boutons link (azimuth, distance, élévation, etc.), ne serait-il pas préférable de préserver les positions relatives des sources et de simplement utiliser les boutons link pour les déplacer en groupe par rapport à une position initialement établie?

Ou encore, on pourrait ajouter un bouton qui permet de choisir entre une liaison (link) des valeurs absolues ou relatives entre les sources. L'option par défaut pourrait être la valeur relative, puisque ça peut être frustrant de placer méticuleusement ses sources, puis de les voir subitement déplacées dès que l'on sélectionne link et que l'on bouge une source.

**Comment by led78** [comment]
On pourrait mettre ce bouton juste en dessous de celui du X-Y, par exemple.

En mode X-Y, justement, le fait sélectionner la case link pour X et Y superpose systématiquement toutes les sources les unes sur les autres. Cela risque d'être très peu utile sur le plan perceptif. Toutefois, si on peut lier les sources selon leur valeur relative, ça devient pas mal plus utile.

**Comment by Xon77** [comment]
suis complètement d'accord

**Comment by belangeo** [comment]
Caduque!
