### ISSUE TITLE
Les source placements Left / Right sont inversés et de plus modifiés par certains source links

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#111]
Reaper 6 - ControlGris 1.1.2

En changeant le nombre de sources, on peut remarquer que les sources placements Left / Right sont inversés par rapport aux versions précédentes (1.1.1).
Par exemple, après avoir indiqué un nombre de sources de 8, la source 1 devrait être à gauche (et non à droite) si le source placement est left Alternate (celui par défaut).

**Comment by Xon77** [comment]
De plus, dans la version 112, le fait de modifier certains source links modifie le placement des sources, alors que cela ne devrait avoir aucun effet (v 111).
Si l'on initialise 8 sources, le fait d'appliquer le source link "circular fixed angle" ou "circular fully fixed" modifie le source placement qui était initialement en "alternate" vers un placement "clockwise".
Cela doit être sûrement relié à la résolution de l'issue #104.

**Comment by SamuelBeland** [comment]
Oh, ça m'avait échappé pour les Left / Right et pour les CW / CCW!

Pour ce qui est des links `fixed angle` ou `fully fixed`, je n'avais pas réalisé que l'ordre relative des sources devait être préservé! J'y travaille...

**Comment by NicolaGiannini** [comment]
Je confirme le comportement décrit par Christophe.

**Comment by SamuelBeland** [comment]
Réglé dans 1.1.3

À confirmer.

**Comment by Normandeau** [comment]
V113
Cela semble réglé. Source Placement et Source Link sont indépendants. Cependant, le choix opéré avec le menu déroulant dans Source Placement ne reste pas affiché. Un choix? Pas certain que c'est bon. Si on n'est pas attentif, on a plutôt l'impression que ça ne marche pas.

**Comment by belangeo** [comment]
> Cependant, le choix opéré avec le menu déroulant dans Source Placement ne reste pas affiché. Un choix? Pas certain que c'est bon. Si on n'est pas attentif, on a plutôt l'impression que ça ne marche pas.

Ce comportement a été mis en place à votre demande, afin de pouvoir sélectionner le même item sans avoir à en sélectionner un autre auparavant. Juce n'envoit pas d'event si on sélectionne l'item déjà sélectionné dans un menu...

**Comment by Normandeau** [comment]
Merci de ce rappel, Olivier. On voit que le sage n'est pas trop loin de son bébé!
