### ISSUE TITLE
Position inexacte de la source principale lors du déplacement de la tête de lecture

### ISSUE THREAD

**Issue by SamuelBeland** [GRIS-UdeM/ControlGris#112]
@NicolaGiannini dans #105 :

> V112
> Testé avec Logic et Reaper.
> La valeur de Ray Lenght reste la même pendant l'écriture de l'automation.
> Je remarque, dans certains cas, un léger flickering (autour de 0,01) de la valeur de Ray Lenght lorsque l'automatisation est en jeu.
> 
> La valeur de Ray Lenght n'est pas correcte si je déplace la tête de lecture sans que la séquence soit en jeu. Ce phénomène fait que la valeur de Ray Lenght n'est pas correcte (mais qu'elle est inférieure) lorsque je place la tête de lecture à l'endroit où j'avais commencé à enregistrer l'automation. Une fois en jeu, la valeur de Ray Lenght revient à la valeur correcte.
> 
> Voir la vidéo:
> https://www.dropbox.com/s/bo5ouhf1ihwyjsp/FlickeringRayLenght.mov?dl=0
> 
> Le phénomène se produit avec tous les Source Link et les Trajectory Type Circle, et en mode DOME et CUBE.
> 
> Pour certaines Trajectory Type, comme Triangle Square Ellipsis et Spiral, je ne peux pas dire s'il y a du flickering. Cependant, le phénomène lié au déplacement de la tête de lecture se produit toujours dans mon cas.

**Comment by NicolaGiannini** [comment]
v112

J'ai préparé deux vidéos,
une où l'automatisation est visible lors de l'enregistrement.
https://www.dropbox.com/s/vbbctewza933cu3/visible-auto.mov?dl=0

Une autre où elle n'est pas visible.
https://www.dropbox.com/s/uha931exj9sf051/hidden-auto.mov?dl=0

En utilisant SpatGRIS1, j'ai réalisé que si je gardais l'automatisation visible pendant l'enregistrement, la résolution était pire.

**Comment by Normandeau** [comment]
V113
Je ne comprends pas pourquoi ceci est un bogue High Priority! Le flickering me semble plutôt relié à l'absence de précision des séquenceurs. J'ai le même phénomène avec DP.
Quant au fait que le Ray Length ne suive pas lorsqu'on déplace le curseur dans la séquence arrêtée, c'est encore relié au type de séquenceur. DP par exemple ne déplace rien lorsqu'on change le curseur de place en mode Stop. C'est seulement quand on démarre la séquence qu'il se place à la bonne position. Cela semble donc confirmer le comportement de Logic. Peut-être que Logic a un problème de suivi de l'automation lorsque la séquence n'est pas en mode Play! (Y a-t-il une préférence pour mettre cette fonction à off?)
Quand au fait que l'écriture de l'automation soit moins précise lorsque celle-ci est affichée, c'est un problème connu et récurrent et encore une fois associé aux séquenceurs. Ceux-ci ont de la difficulté à suivre les cartes graphiques lorsqu'il y a beaucoup de choses à rafraichir à l'écran, alors certaines données sont toujours simplement ignorées lorsque cela arrive. Dans DP, il faut toujours fermer l'affichage lors de l'écriture de l'automation, sinon le résultat est très pauvre en terme de résolution. On remarque par exemple que lorsque le séquenceur a à changer de page, l'automation arrête de s’écrire pendant cette opération graphique.

**Comment by SamuelBeland** [comment]
J'ai mis ce bogue en _High Priority_ car il n'était pas présent dans Reaper pour 1.1.0. Aussi, j'ai l'impression que ce n'est pas seulement dû à un problème d'affichage.

Je crois que dans certains moments (lorsqu'il y a beaucoup de données d'automation envoyées en un court laps de temps), les données peuvent être reçues dans le désordre. Ça me va si la position d'une source n'est pas parfaitement à jour, mais son `x` devrait concorder un minimum avec son `y`. J'ai peur que ça devienne un problème important dans un setup plus complexe. Ça va me faire peur tant que je n'aurai pas identifié la source.

Il faudrait effectuer un test dans un projet massif pour confirmer que le comportement reste limité au déplacement manuel de la tête de lecture. Si c'est le cas, je suis d'accord pour baisser la priorité.

**Comment by Normandeau** [comment]
V113
DP, Séquence 48 pistes stéréo, Automation partout
Aucun problème d'écriture ou de lecture des automations (sauf celui décrit ici #121 )

**Comment by NicolaGiannini** [comment]
V113
Logic, Séquence 34 pistes stéréo, Automation partout.
Dans mon cas aussi aucun problème d'écriture ou de lecture des automations.

Dans Logic, je n'ai pas trouvé une préférence pour mettre à off la fonction de suivi de l'automation lorsque la séquence n'est pas en mode Play.

**Comment by Normandeau** [comment]
V115
Donc est-ce toujours un bogue ?

**Comment by SamuelBeland** [comment]
V115
Je ne suis plus certain que ce comportement existe encore dans  V115.

Mais, si jamais c'est le cas, il y a une question importante avant de tourner la page : est-ce que le _flickering_ se reflète dans SpatGRIS2 ?

**Comment by Normandeau** [comment]
Si ta question est de savoir si cette courbe très approximative...

![Capture d’écran, le 2020-09-29 à 11 43 59](https://user-images.githubusercontent.com/8959779/94581505-2dd90e80-0249-11eb-9688-508f8660cdc5.jpg)

... se reflète dans SpatGRIS2, la réponse est oui. Tout ce que ControlGRIS fait, se reflète dans SpatGRIS2. Mais il faut que j’agrandisse les images des courbes d'automation et le dôme de SpatGIRS2 au maximum pour le voir!
Du coup, la vraie question est plutôt: est-ce que ça s'entend?
Et là la vraie réponse c'est non!
