### ISSUE TITLE
Mauvais rappel des positions à la réouverture d'un projet

### ISSUE THREAD

**Issue by SamuelBeland** [GRIS-UdeM/ControlGris#113]
1.1.2
Testé avec Reaper

Lors de la réouverture d'un projet, si une instance de ControlGRIS n'utilise pas de preset, les positions des sources sont erronées par rapport au moment de la dernière sauvegarde.

**Comment by NicolaGiannini** [comment]
Je n'arrive pas à reproduire cela, ni avec Reaper ou Logic. Dans mon cas les positions des sources sont correctes à la réouverture d'un projet.

**Comment by SamuelBeland** [comment]
1.1.3

Impossible à reproduire de mon côté aussi!
