### ISSUE TITLE
Lorsqu'on appuie sur play à partir d'un preset et avec une Trajectory Type activée, les sources sont repositionnées de manière incorrecte.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#114]
V112
Lorsqu'on appuie sur play à partir d'un preset et avec une Trajectory Type activée, les sources sont repositionnées de manière incorrecte. 

D'après ce que je comprends, les presets rappellent correctement la position des sources, mais ce positionnement ne met pas à jour la Trajectory Type choisie.

Les sources sont repositionnées ou : 

1. à la dernière position où ils ont été placés manuellement.
Voir la vidéo :
https://www.dropbox.com/s/rp3e57ij6kmql8d/manuellement.mov?dl=0

2. Ou bien les sources sont repositionnées dans la position relative au preset à partir duquel on avait entamé la dernière trajectoire.
Voir la vidéo : 
https://www.dropbox.com/s/yoey7yj3gau0aow/preset-tr.mov?dl=0

Les sources restent correctement positionnées si je sélectionne le preset à partir duquel la dernière trajectoire a été lancée (parce que la trajectoire est la même).

 Pour revenir à la normale, un moyen que j'ai trouvé est de passer à Trajectory Type Realtime (la trajectoire disparaît), d'activer le preset souhaité, puis d'appuyer sur Activate.

Voir la vidéo : https://www.dropbox.com/s/mtmsixaodw5bg2s/normale.mov?dl=0

Testé avec Logic et Reaper, DOME et CUBE. Dans mon cas le phénomène se produit avec toutes les combinaisons de Source Link et Trajectory Type, moins Realtime. 

(Une petite note : je me demande si c'est pertinent d'avoir la possibilité de choisir les presets en trajectory Type Drawing.)

**Comment by SamuelBeland** [comment]
1.1.3

Problème réglé de mon côté. À confirmer.

**Comment by Normandeau** [comment]
V113
Pas certain de comprendre le problème ici et donc que ça soit réglé! Les presets ne stockent qu'une seule information: la position des sources. Donc  effectivement, le Trajectory Type n'est pas enregistré. Dans DP, je n'arrive pas à reproduire ce comportement. Alors peut-être que c'est réglé effectivement (je suis passé par dessus la version 112)!
Nicola: j'aimerais que tu précises cette phrase: «Lorsqu'on appuie sur play à partir d'un preset...». Comme on ne peut pas démarrer une séquence à partir d'un preset, il y a donc forcément un ordre: Play suivi de Preset? Preset suivi de Play?
En tout cas ce qui est certain, c'est que Trajectory Type ne devrait pas influencer la positon des sources. Par contre, le Source Link influence certainement la position des sources. Si on enregistre un preset avec Circular et qu'on le rappelle en Symmetric X, forcément les sources vont se placer en fonction de cette dernière fonction. Comme on a fait le choix d'assigner ce paramètre à l'automation, il faut juste être cohérent comme utilisateur.

**Comment by SamuelBeland** [comment]
Ce n'était pas le _trajectory type_ lui-même qui causait problème : la position de départ des trajectoires (et donc son angle et son amplitude) n'était pas mise à jour lorsqu'un preset était chargé. Ça faisait en sorte que la trajectoire n'était plus cohérente par rapport à la nouvelle position de la source. Aussi, activer la trajectoire à ce moment-là la téléportait sur la trajectoire non-modifiée.

Pas nécessairement un problème majeur, mais un problème réglé en tout cas !

**Comment by NicolaGiannini** [comment]
V113
Réglé.
Robert, désolé pour la manque de précision !
L'ordre était :
Je sélectionne un preset.
J'appuie sur play. 

Comme le dit Samuel, je pense que avant le problème était que bien que le preset enregistre seulement la position des sources, le rappelle aurait dû mettre à jour la trajectoire éventuellement choisie.
