### ISSUE TITLE
Dans Reaper, une trajectoire activée sur une piste instrument ne démarre pas lorsqu'on appuie sur play.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#115]
V112
Dans Reaper, une trajectoire activée sur une piste instrument ne démarre pas lorsqu'on appuie sur play. 

En appuyant sur play, le bouton Activate devient gris, si j'appuie à nouveau dessus, pendant que la séquence est en jeu, la trajectoire a lieu. La source semble se trouver au point de la trajectoire où elle aurait dû se trouver par rapport au déroulement du temps.
Voir la vidéo
https://www.dropbox.com/s/x63pehxs3qfvo4n/Reaper-tr.mov?dl=0

**Comment by SamuelBeland** [comment]
1.1.3

Je ne suis pas capable de reproduire le bug.

**Comment by Normandeau** [comment]
V113
Il y a une fonction dans Reaper qui fait que lorsqu'on crée une piste d'instruments, Reaper met automatiquement cette piste en mode d'enregistrement MIDI (le bouton rouge à gauche):

![Reaper MIDI record](https://user-images.githubusercontent.com/8959779/87230848-5d7e2600-c380-11ea-968f-45e4695ebaf3.jpg)

Il faut fermer cette option et alors la trajectoire fonctionne normalement. Peut-être y a-t-il une préférence dans Reaper qui permet de désactiver cette fonction automatique (j'ai cherché un peu mais je n'ai rien trouvé parmi la centaine de préférences...). Sinon, il faudra mettre cela dans le manuel.

**Comment by SamuelBeland** [comment]
C'est quand même curieux que ControlGRIS ne reconnaisse pas que la track soit en lecture si le mode d'enregistrement MIDI est activé. Normalement, à partir du moment que le transport audio est actif, nous devrions obtenir un envoie d'automatisation.

J'ai eu des problèmes similaires dans Logic en testant le fonctionnement de l'enregistrement des trajectoires. Logic désactive carrément l'audio d'une track lorsque elle est vide et qu'elle n'enregistre pas. Si l'audio n'est pas activé, ControlGRIS considère que le transport n'est pas activé et qu'il n'a pas besoin d'envoyer des données d'automatisation.

Peut-être devrait-on considérer une autre approche pour que ControlGRIS considère qu'il est temps d'envoyer ses données?
