### ISSUE TITLE
Le chargement d'un preset sauvegardé dans un source link différent est parfois erroné.

### ISSUE THREAD

**Issue by SamuelBeland** [GRIS-UdeM/ControlGris#119]
Ce problème touche certaines combinaisons de sauvegarde et de chargement de presets avec des _Source Links_ différents.

Un preset sauvegardé en mode `independant` réagit très bien lorsqu'il est chargé dans un autre _Source Link_, mais un preset sauvegardé en `circular`, `circular fixed radius` ou `delta lock` ne sera pas bien représenté en mode `independant`.

Étapes pour reproduire : 

1. Mettre le _source link_ à `independant`
2. Sauvegarder le preset `1`
3. Mettre le _source link_ à `circular`
4. Déplacer la source principale
5. Sauvegarder le preset `2`
6. Mettre le _source link_ à `independant`
7. Charger le preset `1`
8. Charger le preset `2`

**Comment by Normandeau** [comment]
V113
Normal. Comme je l'ai écrit dans l'issue no #114, les presets ne stockent que la position de la source 1. Les autres sources se positionnent selon le Source Link actif au moment du rappel du preset. Dans l'exemple si-haut, si le preset 1 est rappelé en mode Independent et le preset 2 rappelé en mode Circular, les sources se placent aux bons endroits. C'est à l'utilisateur d'être cohérent. C'est un choix éditorial qu'on a fait: on veut pouvoir modifier le Source Link pendant une séquence enregistrée, comme de passer à Symmetric X à Circular par exemple (je me sers de cela tout le temps, maintenant que ça marche). Donc ce paramètre est automatisable, et tout ce qui est automatisable doit être exclus des Presets, sinon, on génère des conflits à n'en plus finir.

**Comment by NicolaGiannini** [comment]
Je propose une réflexion sur ce sujet. Il s'agit d'un détail.

Il est absolument cohérent que si j'enregistre un preset avec un Source Link actif, et que je le rappelle avec un autre Source Link actif, le Source Link influence la position des sources.

Il y a peut-être une possibilité de confusion. Ce n'est que lorsque j'enregistre un preset avec le Source Link Independent actif que les positions de toutes les sources sont mémorisées. Alors qu'avec tous les autres Source Links actifs, seule la position de la première source est enregistrée. On pourrait peut-être le mentionner dans le manuel ?

Cela peut permettre de mieux comprendre pourquoi quand le Source Link Independent est actif, un preset enregistré lorsque Source Link Independent était actif rappelle la position de toutes les sources, alors qu'un preset enregistré lorsque, notamment, Source Link Circular était actif rappelle uniquement la position de la première source.
