### ISSUE TITLE
Un link appliqué dans un mode (X-Y ou Azimuth...) n'est plus visible mais fonctionne toujours dans l'autre

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ControlGris#12]
Si l'on applique un ou plusieurs link dans un mode (X-Y, par exemple) et que l'on passe au mode Azimuth (décoche la boite X-Y), le link appliqué en X-Y demeure, mais n'est plus visible puisque c'est les links du mode Azimuth qui sont maintenant affichés. Il faut retourner au mode X-Y pour désélectionner les links, ce qui est tout à fait logique, mais qui risque de devenir un irritant.

Je pose donc la question, qu'est-ce qui serait préférable entre ces options?
- Empêcher le changement de mode lorsque des links sont activés dans ce mode.
- Désactiver automatiquement tous les links du mode que l'on quitte.
- Afficher le bouton X-Y dans une autre couleur ou teinte afin de rappeler à l'utilisateur qu'il y a des links actifs dans ce mode. Dans ce cas, il faudrait aussi que l'inverse soit vrai: si on a des links actifs en mode azimuth et que l'on passe en mode X-Y, le bouton devrait nous rappeler que c'est le cas par une 3ème coloration. Peut-être serait-il préférable de remplacer le bouton par un toggle ou quelque chose du genre?
- Autres suggestions?

**Comment by NicolaGiannini** [comment]
Je suis d’accord : tous les links devraient être affichés dans chacune des pages.
Et si je devais choisir entre le deux différents modes de link (absolus et relatifs) je préférerais de préserver les positions relatives.

**Comment by NicolaGiannini** [comment]
Mais si on va utiliser le concept de point de contrôle central, cela va changer aussi je crois, n'est pas?

**Comment by belangeo** [comment]
Caduque!
