### ISSUE TITLE
Circular Fixed Angle ne préserve pas toujours les rayons relatifs

### ISSUE THREAD

**Issue by SamuelBeland** [GRIS-UdeM/ControlGris#120]
En lien `Circular Fixed Angle`, le rayon relatif d'une source secondaire est tronqué de façon définitive lorsque le déplacement de la source primaire la pousse hors des limites de l'espace.

Ceci n'est pas un problème majeur, mais devrait être réglé éventuellement afin de rester cohérent avec les autres _source links_ qui préservent maintenant les distances relatives en tout temps.

**Comment by NicolaGiannini** [comment]
Bonjour Samuel,
Tu fais référence à ce comportement ? https://www.dropbox.com/s/xbyp7xnzuwlj2i5/Circular%20Fixed%20Angle.mov?dl=0

**Comment by SamuelBeland** [comment]
@NicolaGiannini absolument, merci pour la description vidéo!

**Comment by NicolaGiannini** [comment]
V114, pas réglé de ce que je comprends.

**Comment by Normandeau** [comment]
V115
Pas réglé

**Comment by NicolaGiannini** [comment]
V115
Je confirme, pas réglé (testé dans Logic).

**Comment by NicolaGiannini** [comment]
V116
Testé en Logic.

Pas réglé. 
Le comportement est légèrement différent par rapport à V115. Le rayon relatif d'une source secondaire est tronqué lorsqu'on passe de "Indipendent" à "Circular" ou à "Circular Fixed Angle"

https://www.dropbox.com/s/qre6zpyddirr3bq/Circular-.mov?dl=0

**Comment by Normandeau** [comment]
Je détaille:
- Quand on passe de Independent à Circular, toutes les sources, sauf la 1 se déplacent légèrement. Cela ne devrait pas être le cas.
- Quand on passe de Independent à Circular Fixed Radius, toutes les sources se mettent au bon Radius mais toutes les sources, sauf la 1 se déplacent légèrement aussi en Angle. Cela ne devrait pas être le cas.
- Quand on passe de Independent à Circular Fixed Angle, toutes les sources se mettent au bon Angle mais toutes les sources, sauf la 1 se déplacent légèrement aussi en Radius. Cela ne devrait pas être le cas.
- Quand on passe de Independent à Circular Fully Fixed, toutes les sources se déplacent correctement.

Voir la vidéo:
https://www.dropbox.com/s/ski1uhgukjxk8w3/Modes%20Circular.mov?dl=0

**Comment by NicolaGiannini** [comment]
Je confirme tous les comportements décrits par Robert. Les tests de Robert indiquent que toutes les sources sauf la 1 sont déplacées de façon non correcte quand on passe de Independent à certains autres Source Link. 

J'ai fait d'autres tests et je crois comprendre ce qui suit. 

- Lorsqu'on change de Independent aux autres Source Link, les sources sauf la 1 se déplacent incorrectement si la source 1 a été déplacée de sa dernière position automatique avant l'activation du nouveau Source Link. 
- Cela détermine que les sources se déplacent comme elles l'auraient été si le nouveau Source Link était actif lors du déplacement de la source 1 (même si j'étais en mode Independent). 
- Si la source 1 n'a pas été déplacée de sa dernière position automatique, le passage de Source Link se fait correctement. 

Par positionnement automatique, j'entends l'utilisation de la fonction “Source placement” ou la modification du nombre de sources.
Ce comportement se produit lors des passages de Independent à Circular, à Circular Fixed Radius,  à Circular Fixed Angle et à Delta Lock.

Je m'explique en détail. 

Considérons le passage de Independent à Circular.
- Je suis en Source Link Independent
- Je positionne les sources de façon automatique. 
- Je déplace toutes les sources sauf la 1.
- Je passe de Independent à Circular.
- Les positions de toutes les sources sont correctes.

Cependant, si je déplace la source 1 avant de passer à Circular, les positions des autres sources ne sont correctes lors du passage à Circular. Les sources sauf la 1 se déplacent comme elles l'auraient été si le Source Link Circular était actif lorsque j’ai déplacé la source 1 de sa dernière position automatique, même si j'étais en Source Link Independent.

Dans la vidéo https://www.dropbox.com/s/jyss4chlotaicaf/Circular--.mov?dl=0 est possible de voir :

00,00 - 00,11
La source 1 n'a pas été déplacée de sa dernière position automatique, donc le passage de Source Link se fait correctement.

00,13 - 00,24 
- Je déplace la source 1 en Source Link Independent à Elevation 0.51 Azimuth 270.
- Je passe à Circular.
- Les sources se déplacent comme elles l'auraient été si le Source Link Circular était actif lors du déplacement de la source 1.

00,24 - 00,49

- Je repositionne la source 1 à sa dernière position automatique (Elevation 0, Azimuth 315)
- J'active le Source Link Circular.
- Je déplace la source 1 à Elevation 0.51 Azimuth 270 (même position du fragment vidéo précédent).
- Les sources se déplacent correctement.
- L'on peut comparer les positions à 00,23 et 00,44 et voir qu'elles sont égales.

Le même comportement se produit quand on passe de Indepedent à Circular Fixed Radius
https://www.dropbox.com/s/3zadzlg81jpxztw/Circular_Fixed_Radius-source1.mov?dl=0

00,00 - 00,14  
La source 1 n'a pas été déplacée de sa dernière position automatique, donc le passage de Source Link se fait correctement.

00,14 - 00,37

- Je déplace la source 1 en Source Link Independent à Elevation 0.40 Azimuth 290
- Je passe à Circular Fixed Radius
- Les sources se déplacent comme elles l'auraient été si le Source Link Circular Radius était actif lors du déplacement de la source 1.

00,37 - 1,07

- Je repositionne la source 1 à sa dernière position automatique (Elevation 0, Azimuth 315).
- J'active le Source Link Circular Fixed Radius.
- Je déplace la source à Elevation 0.40 Azimuth 290 (même position du fragment vidéo précédent).
- Les sources se déplacent correctement.
- On peut comparer les positions à 00,36 et 01,07 et voir qu'elles sont identiques.

Les mêmes comportements se produisent lors des passages de Independent à Circular Fixed Radius et à Delta Lock.

**Comment by NicolaGiannini** [comment]
V117
Testé dans Logic, il semble réglé !

**Comment by NicolaGiannini** [comment]
Je précise, 
il semble réglé en ce qui concerne les comportements décrits par Robert dans ce comment https://github.com/GRIS-UdeM/ControlGris/issues/120#issuecomment-706257114 et par moi ici https://github.com/GRIS-UdeM/ControlGris/issues/120#issuecomment-706607853

Cependant, de ce que je comprends, le comportement pour “Circular Fixed Angle” est le même que dans V113. Comme l’expliquait Samuel :  “En lien Circular Fixed Angle, le rayon relatif d'une source secondaire est tronqué de façon définitive lorsque le déplacement de la source primaire la pousse hors des limites de l'espace”

Voir la vidéo : https://www.dropbox.com/s/9em9jpi1xgx0rx2/CFixedAngle.mov?dl=0

**Comment by Normandeau** [comment]
V118
Cela semble réglé.
