### ISSUE TITLE
Activate génère toutes sortes de comportements dans les différents séquenceurs

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#121]
V113
DP, Séquence 48 pistes stéréo, Automation partout. Mode Latch.
Ceci est un problème récurrent (mais parfois intermittent) sur DP avec cette nouvelle version. Les ControlGRIS ne lisent pas l'information d'automation après que celle-ci a été enregistrée. J'enregistre des pistes d'automation et lorsque c'est fait, j'arrête le séquenceur et je le repart au début. Les automations ne sont pas lues. L'audio se rend bien au SpatGRIS2 mais pas l'OSC, puisque les ControlGRIS restent immobiles. Il faut signaler ici que DP est différent des autres séquenceurs en ce sens que l'automation doit être armée avant de fonctionner. Reaper et Logic au contraire sont prêts à enregistrer l'automation dès qu'on choisit un mode d'écriture (Write, Touch ou Latch par exemple).
Je n'ai pas trouvé d'autre méthode à ce jour pour repartir les automations que de quitter la session (mais pas DP) et de la rouvrir. J'avais essayé:
- Fermer la fenêtre de ControlGRIS et la rouvrir
- Changer le Source Link
- Changer le Trajectory Type
- Rappeler le Preset

Rien ne permet de «réveiller» ControlGRIS. Je n'ai jamais eu ce problème auparavant.

**Comment by Normandeau** [comment]
J'ajoute que cela ne se produit que lors d'enregistrements de trajectoires automatisées. En Realtime, il n'y a pas ce problème.

**Comment by SamuelBeland** [comment]
Un peu difficile à tester de mon côté.

Je n'ai pas encore bien cerné le problème, mais j'ai tenté un fix selon mon intuition dans 1.1.4. 

À vérifier.

**Comment by Normandeau** [comment]
V114
Réglé.

**Comment by Normandeau** [comment]
Voir le commentaire de Samuel au sujet de la version 1.14.

**Comment by NicolaGiannini** [comment]
V132 Reaper 6, Logic 10, MacOS 10.14.6
J’ai essayé de reproduire le issue dans Reaper (et Logic), mais je n’arrive pas.

**Comment by Normandeau** [comment]
Nouveaux tests avec DP11. De ControlGRIS 1.14 à 1.32 (toutes les versions)
• Je confirme que la version 1.14 n'a pas le problème.
«Potential fix for freezed automation in DP»

J'avais fait une série de tests hier mais avec seule piste stéréo. Après l'enregistrement, l'automation est lue par toutes les versions.
Mais à partir de 1.18, jusqu'à 1.32, si on enregistre une 2e piste d'automation, cette dernière n'est pas lue après avoir été enregistrée.
Refait les mêmes tests sous Reaper 6, et tout se passe bien même avec 4 pistes d'automation.

**Comment by Normandeau** [comment]
Synthèse de l'action d'Activate dans les différents DAWs

DP11
1- Essentiellement, la seconde piste d'automation n'est pas lue. Cela a été décrit en détail plus haut.
2- On peut écrire de l'automation sur une piste vide.
3- L'automation est lue sur une piste mutée.

Logic10
1- L'automation est écrite et lue sur plusieurs pistes consécutives.
2- L'automation ne peut pas s'écrire s'il n'y a pas d'audio dans une piste.
2.1- Session démarrée à la mes 0, automation écrite du début jusqu'à environ une mesure après la fin de l'audio
2.2- Session démarrée à la mes 9, automation écrite autour de la mes 16, et qui s'arrête environ une mes après l'audio. 
2.3- 1- Session démarrée à la mes 0, automation écrite du début jusqu'à la mes 2 environ, pas d'audio sur la piste.
La session a été stoppée largement après la fin de l'écriture de l'automation.
![Logic Pas d'audio pas d'automation](https://user-images.githubusercontent.com/8959779/163607862-33748c0f-bd00-42c3-878c-9636a00bc60f.jpg)
3- L'automation est lue sur une piste mutée.

Reaper6
1- L'automation est écrite et lue sur plusieurs pistes consécutives.
2- On peut écrire de l'automation sur une piste vide.
3- L'automation n'est pas lue sur une piste mutée (c'est peut-être une préférence).

Live11
1- L'automation est écrite et lue sur plusieurs pistes consécutives.
2- On peut écrire de l'automation sur une piste vide.
3- L'automation est lue sur une piste mutée.
4- Il semble que l'on ne peut pas écrire plus d'un certain nombre (nombre variable par ailleurs) de trajectoires automatisées de suite sur une même piste.

ProTools2021-12
1- L'automation est écrite et lue sur plusieurs pistes consécutives.
2- L'automation ne peut pas s'écrire s'il n'y a pas d'audio dans une piste.
3- L'automation est lue sur une piste mutée.
4- Le bouton Activate, une fois mis en marche, n'est jamais remis à Off par ProTools.

Bref, un beau bordel!

**Comment by NicolaGiannini** [comment]
En ce qui concerne Logic, j'ai noté des comportements similaires à ceux décrits par Robert, mais avec quelques différences. 

**2.1**- Session démarrée à la mes 0, automation écrite du début jusqu'à environ une mesure après la fin de l'audio
Même comportement.

**2.2**- Session démarrée à la mes 9, automation écrite autour de la mes 16, et qui s'arrête environ une mes après l'audio.

En essayant de recréer ce comportement, je me suis rendu compte qu'il se produit probablement lorsqu’on essaye d'enregistrer deux automations l'une après l'autre, sur deux pistes différentes. 

En démarrant la session à partir de 0, l'enregistrement de la seconde automation commence lorsque le premier fichier se termine.


Voir la vidéo :  https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EYcDhqSagLRPsJWKsD0MQasBq9yAeBwXaOENa7SFtdevRg?e=XLbpJo



**2.3** -  Session démarrée à la mes 0, automation écrite du début jusqu'à la mes 2 environ, pas d'audio sur la piste.

Dans mon cas j'arrive à enregistrer une automation jusqu'à la mes 2 environ comme indiqué par Robert, seulement si un fichier audio avait été lu précédemment sur la même piste (même en mute). Comme si à quelque endroit il y avait une sorte de mémoire de ce playback audio. Par contre, si par exemple je crée un nouveau projet et j'essaye d'enregistrer une automation sur une piste vide, rien ne se passe.


En général, j’ai noté aussi que si je démarre la session à 0 et le fichier n'est pas à 0, l'automation commence quelques instants avant le fichier, en anticipation. 


![Schermata 2022-04-25 alle 19 03 12](https://user-images.githubusercontent.com/35705913/165192823-7fc7c334-a4e3-4c2d-aeae-1181601f8dd5.jpg)



En ce qui concerne Live, j'ai essayé avec les versions 10 et le 11, mais je n'arrive pas à reproduire le comportement. Je me suis inspiré de la vidéo que Mélanie avait envoyée par courriel, mais après 9 trajectoires avec Activate et sur un temps de 4 minutes, les automations sont enregistrées. Peut-être que cela dépend de ma configuration sur 10.14.6 ?

**Comment by Normandeau** [comment]
V133, DP 11.1
Le problème de non-lecture de l'automation après la 2e piste est résolu dans DP. Testé avec 8 pistes stéréo et 8 trajectoires différentes.

**Comment by Normandeau** [comment]
V1.3.3
Tous les tests avec des trajectoires automatisées avec le bouton Activate

DP 11.1 (nouvelle version, 19 avril)
1- Le problème de non-lecture de l'automation après la 2e piste est résolu dans DP. Testé avec 8 pistes stéréo et 8 trajectoires différentes.
2- On peut écrire de l'automation sur une piste vide.
3- L'automation est lue sur une piste mutée.
4- J'ajoute: depuis DP11, l'écriture de l'automation n'a jamais été aussi fluide!

Logic 10.7.4 (nouvelle version, 21 avril)
1- L'automation est écrite et lue sur plusieurs pistes consécutives.
2- L'automation ne peut pas s'écrire s'il n'y a pas d'audio dans une piste.
2.1-2.3-Aucun des comportements étranges décrits plus haut ne se reproduit ici.
3- L'automation est lue sur une piste mutée.

Reaper 6.56 (nouvelle version, 25 avril)
1- L'automation est écrite et lue sur plusieurs pistes consécutives.
2- On peut écrire de l'automation sur une piste vide.
3- L'automation peut être lue sur une piste mutée (c'était effectivement une préférence).

Live 11.1.1 (3 mars)
1- L'automation est écrite et lue sur plusieurs pistes consécutives.
2- On peut écrire de l'automation sur une piste vide.
3- L'automation est lue sur une piste mutée.
4- Comme Nicola, je n'arrive pas non plus à reproduire le problème décrit par Mélanie au sujet des automations successives sur la même piste. Viens de tester avec 7 fragments différents sur la même piste. Aucun problème.

Donc synthèse: ça a l'air de bien fonctionner non? Autres tests?

**Comment by NicolaGiannini** [comment]
V133 

Logic 10.5.1. MacOS 10.14.6


Dans mon cas il ne semble pas possible d'enregistrer 2 automations en même temps. Si je lance des enregistrements en même temps sur des pistes différentes, il semble possible d'enregistrer une automation à la fois. Lorsqu’un deuxième enregistrement commence, le premier enregistrement s'arrête. 

Vidéo : https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EQLaaRjfs1JBlyaOmLz5VVAB8VkSj6VYOcyjyqFH_v5iVg?e=ci9Iqt

J'ai noté aussi que si j'efface les automations enregistrées et que je relance l'enregistrement, seulement l'automation de la dernière piste en ordre temporel peut être enregistrée.

Vidéo : https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EdoPhoaN2tRBn30BpZxCJEMB3uTRr_n11K-bLa_KCWdCcA?e=GxL1Nm

Live 10.1.42 et Live 11.0.12 tout semble beau.

**Comment by Normandeau** [comment]
Logic 10.7.4 MacOS 11.6.5. Mode Write ou Latch, Activate.
Belle expérience Nicola.
Malheureusement je n'arrive pas à la reproduire:

4 pistes simultanément:
![Logic 4 pistes ensemble](https://user-images.githubusercontent.com/8959779/166837592-b22ad7ff-0e48-4dec-a821-fb73073f3853.jpg)

4 pistes ensemble décalées:
![4 pistes ensemble décalées](https://user-images.githubusercontent.com/8959779/166837680-5247e341-41ef-4738-bdef-127715f5095c.jpg)

4 fragments séparés
![Logic 4 fragments séparés](https://user-images.githubusercontent.com/8959779/166837777-62447a61-3b1b-4702-ab4f-5899fd4ec3a8.jpg)

4 fragments légèrement superposés:
![Logic 4 fragments légèrement superposés](https://user-images.githubusercontent.com/8959779/166837882-4f9228fd-34fc-449d-a04b-4424b8e54ce3.jpg)

Tout fonctionne. Question d'OS? de version de Logic? D'une combinaison de tout cela?

**Comment by NicolaGiannini** [comment]
Probablement oui ! Il faut dire que MacOs 10.14.6 et Logic 10.5.1 commencent à être un peu datés ! Temps de faire l’upgrade !

**Comment by Normandeau** [comment]
1.3.4.
Tout semble rentré dans l'ordre avec les dernières versions des différents DAW depuis la version 1.3.3. Je ferme pour le moment, on verra avec la prochaine édition si c'est toujours résolu.
