### ISSUE TITLE
Il n'est pas possible de déplacer et de positionner correctement les sources de 2 à 8 en utilisant le Source Link Independent.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#122]
V113
Testé avec Logic et Reaper.
Il n'est pas possible de déplacer et de positionner correctement les sources de 2 à 8 en utilisant le Source Link Independent.

En mode DOME, les sources de 2 à 8, en utilisant le Source Link Independent, ne peuvent être déplacées que pour l'Azimut, mais pas pour l'Elevation. La même chose se produit lorsque l'on déplace les valeurs de Ray Lenght dans l'onglet Source.

En mode CUBE, les sources de 2 à 8, en utilisant le Source Link Independent peuvent être déplacées correctement dans le cadran Azimuth-Distance. Ces sources ne peuvent pas être déplacées dans le quadrant Elevation.

**Comment by Normandeau** [comment]
Wow! Bogue majeur, merci Nicola d'avoir vérifié cela. À corriger ASAP.

**Comment by SamuelBeland** [comment]
Effectivement, bug majeur!

Réglé dans 1.1.4.
À vérifier.

**Comment by Normandeau** [comment]
V114
Le problème décrit ici est réglé. Mais il en a fait apparaître un autre, décrit dans l'issue suivante #126
