### ISSUE TITLE
Dans Reaper, l'écriture de l'automation s'écrit environ 1/4 de seconde avant la tête de lecture

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#123]
Ceci n'est pas un problème nouveau et avais déjà été évoqué lors d'une réunion préalable. 
Je ne sais pas ce qu'il en ait des autres séquenceurs, mais l'écriture de l'automation s'écrit toujours 1/4 de seconde avant la tête de lecture dans Reaper.
Je ne sais pas s'il est possible de synchroniser de manière plus précise les 2, à la fois l'écriture de l'automation et la tête de lecture, afin de pouvoir notamment commencer l'automation à la position exacte où l'on a positionné la tête de lecture.

**Comment by SamuelBeland** [comment]
Reaper agit de la sorte pour tout enregistrement d'automation en temps réel, peu importe le plugin.

J'ai cherché dans le manuel de Reaper mais je n'ai rien trouvé à ce sujet. J'ai cru que c'était une forme de compensation pour la latence audio, mais réduire ou augmenter la taille du buffer audio ne semble pas modifier le délais (négatif) de l'enregistrement de l'automation. Étrange.

Comme c'est standard pour Reaper, c'est une mauvaise idée d'essayer de fixer ce comportement.
