### ISSUE TITLE
Relation entre les sources: le mode Delta Lock pose problème

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#126]
V114, suite au problème réglé dans #122 
Relation entre la source 1 et la source 2 (ou les sources 2 à 8 en octo)
Trajectory Type: Realtime
Tous les Source Link (sauf Independent)
Normalement, la Source 2 (en stéréo) devrait être inamovible. Or ce c'est plus le cas, la Source 2 bouge (presque toujours) indépendamment de la source 1:
- Circular: complètement libre
- Fixed Radius: en cercle, avec le même rayon que 1
- Fixed Angle: en ligne droite, avec le même angle que 1
- Fully Fixed: inamovible
- Delta Lock: complètement libre
- X et Y: inamovible
On a d'ailleurs perdu le message: «Only source 1 can be selected in circular or symmetric links». Cela permettait d'informer les utilisateurs que les sources 2 et plus ne pouvaient pas être bougées dans ces modes (V110).

**Comment by Normandeau** [comment]
V114
Circular Fixed Angle, RealTime, Octo
Cela génère d'ailleurs des comportements étranges, qui semblent aléatoires, qui sont en tout cas difficiles à prévoir et qui n'ont pas lieu d'être. Voir le film:
https://www.dropbox.com/s/0hjmry1ytki4m9u/Relation%20entre%20les%20sources%20octo.mov?dl=0

**Comment by NicolaGiannini** [comment]
Bonjour,
je confirme tout, aussi le comportement décrit par la vidéo de Robert. Je pense que le comportement général a été introduit dans la release 1.1.2. 
https://github.com/GRIS-UdeM/ControlGris/releases/tag/1.1.2

"Secondary sources (sources 2 to 8) can now be directly moved using the mouse pointer. This means it is no longer necessary to switch to an independent link in order to modify a secondary source's relative position in circular or delta-lock links. In order to stay coherent, it is no longer possible to drag all the sources when clicking a secondary source, as could be done previously with delta lock and symmetric links. This also means that dragging a secondary source around...
...in Circular Fixed Radius will change its relative angle.
...in Circular Fixed Angle will change its relative radius.
...in Circular Fully Fixed won't do anything (same as before).
...in Delta Lock will change its relative position.
...in Link Symmetric X won't do anything.
...in Link Symmetric Y won't do anything."

Je signale un autre comportement étrange en Circular Fully Fixed, voir la vidéo :
https://www.dropbox.com/s/jhfeu9qm3fdrr3f/Circular%20Fully%20Fixed.mov?dl=0

**Comment by SamuelBeland** [comment]
Effectivement, comme @NicolaGiannini l'a mentionné, c'est une feature volontairement introduite dans 1.1.2 [et expliquée dans les release notes](https://github.com/GRIS-UdeM/ControlGris/releases/tag/1.1.2) (que personne n'a lu ???). Comme je n'en ai pas entendu parlé après 1.1.2, j'ai assumé que ma proposition était la bienvenue.

Je trouvais qu’offrir la possibilité de ne pas avoir à constamment retourner en mode indépendant pour modifier la position d'une source secondaire était possiblement une bonne idée. Aussi, cela permettait de modifier la position d'une source sans "reset" la position relative de _toutes_ les autres sources (ce qui est le cas lorsque l'on change le _source link_). De plus, c'est un peu fatiguant lorsqu'on désire par exemple "modifier le rayon relatif d'une source secondaire en _circular fixed angle_", de devoir aller en mode indépendant (où toutes les positions sont permises) et d'ensuite voir la position que l'on vient de choisir être modifiée dans le retour en mode _circular fixed angle_ (puisque les positions ne sont pas toutes permises dans ce lien et que mon placement de souris n'est pas parfait).

J'ai décidé de proposer le changement en me disant que j'implémenterais l'ancien fonctionnement si jamais ma proposition ne passait pas (et, pour être honnête, c'était pas mal plus simple à implémenter de cette façon).

> Cela génère d'ailleurs des comportements étranges, qui semblent aléatoires, qui sont en tout cas difficiles à prévoir et qui n'ont pas lieu d'être. Voir le film: https://www.dropbox.com/s/0hjmry1ytki4m9u/Relation%20entre%20les%20sources%20octo.mov?dl=0

Explications : le lien est _circular fixed angle_ : l'angle est fixe, mais le rayon relatif peut être modifié. Dans la vidéo, on voit la position relative d'une source secondaire être modifiée par l'utilisateur, mais la position est contrainte par les exigences du source link actif (dans ce cas: les angles entre chaque source doivent rester égales). Aussi, on m'avait fait réaliser dans #111 que l'ordre des sources pouvait être modifiée. Donc, ce que l'on voit dans le vidéo, c'est aussi l'ordre de la source qui est modifiée. Ce comportement a également été décrit dans [des release notes précédentes](https://github.com/GRIS-UdeM/ControlGris/releases/tag/1.1.3).

> Je signale un autre comportement étrange en Circular Fully Fixed, voir la vidéo : https://www.dropbox.com/s/jhfeu9qm3fdrr3f/Circular%20Fully%20Fixed.mov?dl=0

Même chose ici : l'angle et le rayon sont fixés. La seule chose qui peut être modifiée, c'est l'ordre des sources.

**Comment by SamuelBeland** [comment]
Pour ce qui est du message lorsque l'on sélectionne une source inamovible : c'est un oubli de ma part. Je remet ça demain.

**Comment by NicolaGiannini** [comment]
V116
Testé en Logic.

Maintenant lors de la sélection d'une source qui n'est pas numéro 1, les sources se déplacent en fonction du "Source Link" sélectionné. Avant la version 1.1.2, ces sources ne pouvaient pas être sélectionnées ou déplacées.

Je confirme que cela fonctionne correctement :
 @SamuelBeland 
> "La méthode de déplacement introduite à 1.1.2 (possibilité de déplacer des sources individuelles en conservant le Source Link) est maintenant accessible en enfonçant la touche CTRL."

**Comment by Normandeau** [comment]
V116
1. Cela fonctionne bien maintenant avec les modes circulaires et les modes Symmetric, on peut désormais sélectionner n'importe quelle source, l'automation de la Source 1 s'écrit bien et elle est bien lue par la suite.
2. Il y a un problème cependant avec Delta Lock.
Le comportement des sources varient selon qu'on contrôle la situation avec la Source 1 ou avec l'une ou l'autre des autres sources. En gros, on peut dire ceci:
- si on déplace un ensemble octo avec la Source 1, on peut écraser tout le monde sur la paroi du cercle.
- si on déplace un ensemble octo avec une source autre que la Source 1, on ne peut pas ou très difficilement écraser tout le monde sur la paroi du cercle.

Voir la vidéo:
https://www.dropbox.com/s/l3upmtbnrralala/Delta%20Lock.mov?dl=0

**Comment by NicolaGiannini** [comment]
En ce qui concerne le problème avec Delta Lock, je note une chose. La source 1 peut être déplacée dans toute la surface du cercle (DOME) et du carré (CUBE), tandis que les autres sources n'ont pas les mêmes possibilités de déplacement. De ce que je comprends, plus la source est éloignée de la source 1, moins elle peut se déplacer.

**Comment by SamuelBeland** [comment]
1.1.6

Ce comportement touche aussi les modes `circular` et `circular fixed angle` ([voir la vidéo](https://drive.google.com/file/d/1Z2ZasvOIVpE6YYkuQyKSsNa6lDkRsppB/view?usp=sharing)). `Delta lock` reste le mode où cette limitation est la plus évidente. C'est un comportement qui émerge de la façon dont les source links sont calculés.

Si l'on désire permettre d'écraser la source 1, il faut se poser la question suivante :

1. Si j'active delta lock...

<img width="493" alt="1" src="https://user-images.githubusercontent.com/39448259/99981569-8fb08300-2d77-11eb-84da-10f8cb0700f2.png">

2. ...et que j'écrase la source 1...

<img width="493" alt="2" src="https://user-images.githubusercontent.com/39448259/99981596-950dcd80-2d77-11eb-9e9e-a9e578208abe.png">

3. ...___que se passe-t-il si je déplace la source 1___ (avec la souris ou par une automation) ?

Est-ce que __a__ : 

<img width="493" alt="3a" src="https://user-images.githubusercontent.com/39448259/99981841-e027e080-2d77-11eb-9aec-9cb6e6fa2965.png">

...la distance relative entre les sources a été écrasée par le mouvement ? C'est problématique est ça vient rejoindre le problème de #120.

Ou est-ce que __b__ :

<img width="493" alt="3b" src="https://user-images.githubusercontent.com/39448259/99981986-051c5380-2d78-11eb-862a-1348d4acd208.png">

...la source 2 revient instantanément à sa "bonne" position ? Si oui, ça veut donc dire que j'aurais temporairement poussé la source 1 à l'extérieur de la zone légale. __Comment va-t-on représenter ce mouvement dans l'automation__ ?

Tout cela n'est pas problématique pour les sources secondaires puisque leurs positions n'ont pas à être représentées par l'automation.

**Comment by Normandeau** [comment]
V118
Il resterait encore à discuter pas mal au sujet de Delta Lock, y compris: est-ce que quelqu'un l'utilise vraiment? En ce qui me concerne, le comportement des sources les unes par rapport aux autres avec cette nouvelle version est parfaitement cohérent. Et pour Delta Lock, on mettra dans le manuel, qu'il fait bouger la Source 1, pour obtenir la plus grande flexibilité.

**Comment by NicolaGiannini** [comment]
Je suis d'accord !
(Moi je n'ai jamais utilisé le Delta Lock.)

**Comment by Normandeau** [comment]
V132
Delta Lock et autres trajectoires à raffiner très bientôt.
