### ISSUE TITLE
Lorsque l'on utilise un Source Link Symmetric, indiquer un chiffre supérieur à 2 dans le champ sources donne lieu à des comportements étranges.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#127]
La question n'est pas importante et d'ailleurs le manuel indique clairement que les Source Link Symmetric ne peuvent être utilisés qu'avec deux sources. 

Cependant, lorsque l'on utilise un Source Link Symmetric, indiquer un chiffre supérieur à 2 dans le champ sources donne lieu à des comportements étranges.

Voir la vidéo:
https://www.dropbox.com/s/lte8z52tdy0c125/symmetric.mov?dl=0

Je me demandais s'il ne serait pas opportun de ne pas permettre à l'utilisateur d'en indiquer plus de deux pour les liens sources symétriques.

**Comment by SamuelBeland** [comment]
> Cependant, lorsque l'on utilise un Source Link Symmetric, indiquer un chiffre supérieur à 2 dans le champ sources donne lieu à des comportements étranges.

Avec plus de deux sources, les sources secondaires (2 à 8) sont toutes entassées les unes par-dessus les autres. Comme les sources sont légèrement transparentes, les couleurs sont mélangés ensemble. La source 2 sera toujours sur le dessus de la pile.

Le menu _source link_ ne permet pas sélectionner les modes symétriques lorsque le nombre de sources n'est pas égal à 2, mais lorsqu'on est déjà en mode symétrique, il n'existe aucune restriction pour le nombre de sources .

On pourrait ajouter cette restriction, ou bien changer le champs "number of sources" pour un menu _drop-down_ mais je crois que ça risque de causer de la confusion chez les utilisateurs qui ne comprendraient pas nécessairement pourquoi il leur est soudainement impossible de changer le nombre de sources. La même confusion peut exister lorsqu'il est impossible de sélectionner les liens symétriques, mais je crois que c'est pas mal moins grave dans ce cas-ci.

Je proposerais de laisser l'utilisateur modifier le nombre de sources en modes symétriques mais de lui afficher une boîte d'information (expliquant que les sources seront toutes entassées).

**Comment by NicolaGiannini** [comment]
V115
Il y a toujours des comportements étranges. 
On pourrait ajouter une restriction pour le nombre de sources, ou afficher un message. Moi probablement j'ajouterais la restriction, parce que maintenant si par erreur on indique un chiffre supérieur à 2, il n'est pas facile de revenir à la normale. Par exemple dans mon cas le Source Link affiche "independent" même si les sources se déplacent toujours en mode "Symmetric". https://www.dropbox.com/s/r690ok5999uf3zk/sym.mov?dl=0

**Comment by NicolaGiannini** [comment]
V116
Testé en Logic.
Si je mets plus de deux sources lorsque le “Source Link” “Symmetric (X ou Y)” est actif, le “Source Link” passe automatiquement à “Independent”. 
Si, après cela, je mets 2 sources, et après j’active  le “Source Link” “Symmetric (X ou Y)”, malgré l'affichage “Symmetric (X ou Y)”, on reste toujours en mode “Independent”.

Voir la vidéo https://www.dropbox.com/s/l4oine42gastqvk/Sym2-.mov?dl=0

**Comment by Normandeau** [comment]
Une précision ici. Si on pousse un peu plus l'exploration, on se rend compte qu'en fait, il faut repasser deux fois par l'un des modes Symmetric pour le réactiver. Donc:
- Si je mets plus de deux sources lorsque le “Source Link” “Symmetric (X ou Y)” est actif, le “Source Link” passe automatiquement à “Independent”.
-Si, après cela, je mets 2 sources, et après j’active le “Source Link” “Symmetric (X ou Y)”, malgré l'affichage “Symmetric (X ou Y)”, on reste toujours en mode “Independent”.
- Si Symmetrix X a été choisi après Independent, il faut sélectionner Symmetric Y pour que celui-ci devienne actif.
- Et ensuite on peut repasser en Symmetric X pour qu'il soit actif.

Voir la vidéo:
https://www.dropbox.com/s/0j7ka6474db5viz/Modes%20Symmetric.mov?dl=0

**Comment by NicolaGiannini** [comment]
V117
Testé dans Logic, il semble réglé.

**Comment by Normandeau** [comment]
V118
Cela est effectivement réglé.
