### ISSUE TITLE
Le numéro de la source sélectionnée ne se met pas à jour lorsqu'on le change

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#129]
V114
Dans une session j'ajoute une piste stéréo au milieu des autres. Je dois donc décaler les numéros OSC des pistes suivantes. Lorsque je change le numéro de la First Source ID, ça change dans la fenêtre graphique, mais le numéro de la source sélectionnée reste identique. Dans le cas d'un piste stéréo, il faut que sélectionne la source 2 pour que l'affichage se mette à jour.
Dans l'exemple, 105 était le numéro de la source avant le changement. Lorsque j'effectue le changement à 107, la source sélectionnée reste à 105. Si je sélectionne 107, rien ne se passe. Il faut sélectionner 108 pour celle-ci se mette à jour. Ensuite, si je sélectionne 107, elle se met à jour finalement.

![Source sélectionnée](https://user-images.githubusercontent.com/8959779/90073777-cfbb9080-dcc7-11ea-9977-327f2ea7dcd8.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme, testé en Logic.

**Comment by NicolaGiannini** [comment]
Testé dans Logic, réglé.

**Comment by Normandeau** [comment]
Réglé dans DP aussi.
