### ISSUE TITLE
Dans Logic et Live les changements de presets ne sont pas écrits dans les automations.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#133]
V114
Dans Logic 10.4.8 les changements des presets ne sont pas écrits dans les automations.

Je crée des presets.
Je démarre la séquence en mode Latch.
Je change de preset.
Les changements ne sont pas enregistrés.
Un preset 0 est, je crois, enregistré au moment où je commence à changer de presets.

Voir la vidéo https://www.dropbox.com/s/i5h8ppqczpz1mkd/automations_presets.mov?dl=0

Cela se passe dans Logic et non dans Reaper.
J'ai essayé la version 110 et les presets sont correctement écrits dans les automations.

**Comment by Normandeau** [comment]
V114
Dans DP, seul le premier preset est enregistré. Les suivants ne le sont pas.

**Comment by Normandeau** [comment]
Dans Live, les changements des presets ne sont pas écrits dans les automations.

**Comment by NicolaGiannini** [comment]
Robert t'as utilisé la version 10 de Live ?

Je viens de faire un test avec Live 9.7.7 et je peux enregistrer l'automation du Source Link, sauf que après l'enregistrement elle devient gris, et quand je redémarre la lecture de la séquence elle n'est pas lue par Live. 

Je ne connais pas très bien Live, mais même si j'appuie sur le bouton "Réactiver l'automation", Live ne lit que la première automation. 

https://www.dropbox.com/s/xzqvokkokd56olo/Live.mov?dl=0

**Comment by NicolaGiannini** [comment]
V115
Dans Logic les automations des changements des presets sont maintenant écrites.

**Comment by Normandeau** [comment]
Live 10.1.9
Les presets sont bien écrits et lus.
Je ne peux pas vérifier avec Live 9 car il ne supporte pas les VST3. Et nous n'avons pas de VST2 pour la version 1.15. Il faudrait toujours sortir les trois versions minimum: VST2, VST3 et Component. Et j'espère, bientôt, AAX.

**Comment by SamuelBeland** [comment]
J'ai rajouté le build VST2 au téléchargement pour 1.1.5.

J'ai exploré la question du port AAX aujourd'hui. J'arrive à compiler le plugin en AAX assez facilement, mais il n'est uniquement utilisable qu'à partir d'une version "développeur" de Pro Tools. Nous allons devoir nous créer un compte développeur chez AVID et faire notarier nos releases officielles pour qu'elles soient utilisables dans les versions standards.

**Comment by Normandeau** [comment]
V115, VST2
Ok ça fonctionne dans Live 9.
Je remarque une chose cependant qui pourrait être améliorée. Actuellement quand l'automation de presets est lue, il n'y a rien dans le plugiciel lui-même qui nous dit lequel des presets est sélectionné. Ils sont tous en blanc:
![Capture d’écran, le 2020-09-25 à 15 35 38](https://user-images.githubusercontent.com/8959779/94308652-d08d4680-ff44-11ea-8312-1ef2e1cdf645.jpg)

Il me semble que dans les versions antérieures, le preset choisi était en orange, comme quand on le sélectionne manuellement:
![Capture d’écran, le 2020-09-25 à 15 33 22](https://user-images.githubusercontent.com/8959779/94308551-afc4f100-ff44-11ea-9ba0-7174574b994e.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme que dans Logic, lorsque l'automatisation des changements de presets est lue, le preset choisi ne devient pas orange. 
La même chose se produit lorsqu'un preset est créé. Peut-être que dans ce cas aussi, le preset devrait devenir orange ? Une fois créé, le preset est actif.

**Comment by NicolaGiannini** [comment]
V116
Lorsque l'automatisation des changements des presets est lue, le preset choisi devient orange.
(Quand le preset est créé le preset ne devient pas orange)
Testé en Logic, Live et Reaper.

**Comment by Normandeau** [comment]
V116
Réglé et amélioré.
