### ISSUE TITLE
Tenter de modifier une automation liée au Source Link bloque temporairement Logic et DP

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#134]
V114
Tenter de modifier une automation liée au Source Link bloque temporairement Logic.

J'écris quelques automations pour le paramètre "Source Link". 
J'arrête la séquence.
J'essaie de modifier les automations.
Logic se fige pendant quelques instants et il n'est pas possible de modifier les automations. 
Le blocage se produit surtout si la tête de lecture est positionnée sur l'automation que l'on essaie de modifier. 
Comme vous pouvez le voir dans la vidéo, j'arrive à modifier les automations qui ne sont pas en contact avec la tête de lecture, lorsque j'essaie de modifier celui où la tête de lecture est présente, Logic se fige. 

https://www.dropbox.com/s/odu1nheq839wo4a/SourceLinkAutomation.mov?dl=0

Une note. J'ai essayé de faire plusieurs vidéos, mais je me suis rendu compte, du moins dans mon cas, que Quicktime n'enregistre pas le rouet qui apparaît à la place du pointeur de la souris lorsqu'il y a un bloc.

**Comment by Normandeau** [comment]
V114
Même comportement de blocage dans DP. Si le curseur est sur un point d'automation enregistré de Source Link, la séquence ne démarre pas et la roue de la mort apparaît. Elle tourne pendant un certain temps puis s'arrête.
Il faut déplacer le curseur pour que la séquence se mette à jouer.

**Comment by NicolaGiannini** [comment]
Je ne sais pas si cela sera utile, mais Logic donne parfois ce message lorsque j'essaie de modifier l'automation de Source Link.

![miditimeout](https://user-images.githubusercontent.com/35705913/91204325-e69fb100-e6d1-11ea-9a4f-60b7819608cd.jpeg)

**Comment by NicolaGiannini** [comment]
En continuant à tester dans Logic, il me semble réaliser que pour bloquer temporairement la DAW, il suffit d'écrire une automation de Source Link et d'afficher les automations (pas nécessairement celles de Source Link).

Le temps de blocage semble augmenter si :
j'écris d'autres automations de Source Link sur différentes pistes;
si j'active l'affichage de l'automation du Source Link;
si j'essaie de modifier l'automation de Source Link.

**Comment by NicolaGiannini** [comment]
V115
Testé avec Logic, réglé.

**Comment by Normandeau** [comment]
Testé avec DP, ça semble réglé également.
