### ISSUE TITLE
Seule la première automation de Source Link est lue par DP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#135]
V114
Si on enregistre plusieurs automations de Source Link les unes après les autres, seule la première est lue par DP. Les autres, bien qu'écrites, sont ignorées. Ce problème n'existe pas dans 110.

**Comment by Xon77** [comment]
Je n'observe pas pour l'instant ce problème dans Reaper, tout comme je n'observe pas les issue #134 et #133 dans Reaper.
vais continuer à tester...

**Comment by Normandeau** [comment]
Fonctionne effectivement dans Reaper. Et dans Logic.
Ableton Live affiche une forte activité MIDI. Pourquoi cela? Est-ce que cela a un rapport avec le problème soulevé par Nicola #134 dans Logic? Et chaque automation lue de Source Link désactive la fonction de lecture des automations. Voir vidéo:
https://www.dropbox.com/s/abqeqb4hutlr89i/Live%20D%C3%A9sactivation%20de%20l%27automation.mov?dl=0

J'ai le sentiment d'avoir déjà vécu tout cela, mais je n'en trouve pas la trace...
Donc est-ce que cette manifestation de l'interruption de la lecture de l'automation dans Live serait la même manifestation que celle observée dans DP? Sauf que dans DP, on ne voit pas que l'automation est suspendue! Mais le résultat est le même: seule la première automation est lue.

**Comment by NicolaGiannini** [comment]
Peut-être que il se passait quelque chose de similaire ici https://github.com/GRIS-UdeM/ControlGris/issues/49#issuecomment-545597236 Robert, tu te réfères à ça ?

Maintenant, cependant, si je ferme la fenêtre du plugin, Live continue à ne lire que le premier point de l'automation.

**Comment by Normandeau** [comment]
V115
Problème réglé dans DP.
