### ISSUE TITLE
Activate OSC est fermé par défaut

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#137]
V115
Activate OSC est fermé par défaut. Ça m'a pris un certain temps avant de le découvrir. À mettre à ON par défaut svp.

**Comment by NicolaGiannini** [comment]
V115, confirmé dans Logic.

**Comment by NicolaGiannini** [comment]
V116
Testé dans Logic, Live et Reaper, ça semble réglé.

**Comment by Normandeau** [comment]
V116
Réglé.
