### ISSUE TITLE
Confirmation: la version AAX du plug-in n'est pas reconnu par Pro Tools

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ControlGris#14]
![controlgris_aax_pt_error](https://user-images.githubusercontent.com/13606544/49811356-1d346d00-fd31-11e8-9fce-87d091994d49.png)

**Comment by led78** [comment]
J'ai rapidement regarder sur des forums et il faut effectivement passer par Avid pour développer des plug-in fonctionnels dans Pro Tools.

> ProTools can only load valid code-signed binaries.

Registering & downloading the SDK itself won't work. You'll need to get in touch with Avid and apply for the AAX/audio developer program. Once you've been approved you not only get access to developer versions of ProTools but also can code-sign the binaries with the PACE signing tool.

**Comment by Normandeau** [comment]
On attend la licence.
