### ISSUE TITLE
Problème de mapping entre ControlGRIS et le Patch de Open Stage Control

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#148]
V117
Il semble avoir un problème de mapping en ce qui concerne le positionnement des sources (Azimut Elevation en mode DOME et XYZ en mode CUBE) entre ControlGRIS et le Patch de Open Stage Control. Les autres paramètres semblent bien fonctionner. 
Voir les vidéos : 
ControlGRIS 110 : https://www.dropbox.com/s/r8dwze1bzrnji4n/OSC-110.mov?dl=0
ControlGRIS 117 https://www.dropbox.com/s/vbphd6uouw24x8t/OSC-117.mov?dl=0
ControlGRIS117 en utilisant les sliders Elevation et Azimuth : https://www.dropbox.com/s/hmr1lm2dsgyvbtf/mappingv117.mov?dl=0

**Comment by Normandeau** [comment]
V115 (attention, pas la même version que Nicola, mais les mêmes symptômes)
Confirmation de ce problème. Plus de détails ici. Dans la version actuelle de Open Stage Control 177, les trois axes doivent être programmés de la manière suivante;
Axe des X: min -1 à max 1 (avant: 0 à 1)
Axe des Y: min 1 à max -1 (avant: 0 à 1)

![Capture d’écran, le 2020-12-11 à 11 05 53](https://user-images.githubusercontent.com/8959779/101926225-e653f480-3ba0-11eb-8971-5d6c19c0efb7.jpg)

Axe des Z: min 1 à max -1 (avant: 0 à 1)

![Capture d’écran, le 2020-12-11 à 11 06 09](https://user-images.githubusercontent.com/8959779/101926247-ed7b0280-3ba0-11eb-97bc-f5add35fe2d9.jpg)

Les Spans sont ok: 0 à 1
Les Source Link sont OK: de 1 à 8
Les Source Link Alt sont OK: de 1 à 5

Voici comment l'information OSC de x-y est envoyée au ControlGRIS:
![Capture d’écran, le 2020-12-11 à 11 10 23](https://user-images.githubusercontent.com/8959779/101927486-8bbb9800-3ba2-11eb-9ed0-8fc995d43ee5.jpg)

Voici comment l'information OSC de z est envoyée au ControlGRIS
![Capture d’écran, le 2020-12-11 à 11 19 23](https://user-images.githubusercontent.com/8959779/101927786-d89f6e80-3ba2-11eb-8e5e-2608a63d7085.jpg)

L'élévation ne fonctionne plus. En mode Receive, à partir du iPad, x-y fonctionne correctement avec les nouvelles valeurs. Mais z = y. Autrement dit quand on bouge le fader z, c'est y qui bouge (comme illustré dans le second vidéo de Nicola, lorsqu'il passe en mode CUBE).
En mode bidirectionnel, le ControlGRIS n'envoie aucune information z au iPad.

**Comment by Normandeau** [comment]
Voir l'issue #80 
Est-ce que quelque chose a été modifié dans la communication OSC depuis la version officielle?

À titre de référence, voici les adresses OSC que reconnait ControlGRIS (en entrée comme en sortie):

    /controlgris/traj/1/x value
    /controlgris/traj/1/y value
    /controlgris/traj/1/z value
    /controlgris/traj/1/xyz/1 value
    /controlgris/traj/1/xyz/2 value
    /controlgris/traj/1/xyz/3 value
    /controlgris/traj/1/xy value
    /controlgris/traj/1/xyz value
    /controlgris/azispan value
    /controlgris/elespan value
    /controlgris/sourcelink value => 1 à 6
    /controlgris/sourcelinkalt value => 1 à 5
    /controlgris/presets value => 1 à 50

**Comment by Normandeau** [comment]
En fait, ces messages OSC ne sont pas les bons. Olivier les a modifiés par la suite. Mais grâce à notre merveilleux manuel, voici les bons:
• /controlgris/1/traj/1/x value
• /controlgris/1/traj/1/y value
• /controlgris/1/traj/1/z value
• /controlgris/1/traj/1/xyz/1 value 
• /controlgris/1/traj/1/xyz/2 value 
• /controlgris/1/traj/1/xyz/3 value 
• /controlgris/1/traj/1/xy value
• /controlgris/1/traj/1/xyz value
• /controlgris/1/azispan value
• /controlgris/1/elespan value
• /controlgris/1/sourcelink value => 1 à 8
• /controlgris/1/sourcelinkalt value => 1 à 5 • /controlgris/1/presets value => 1 à 50

La valeur ajoutée après controlgris permet de contrôler plusieurs instances du plugiciel.

**Comment by Normandeau** [comment]
V118
Réglé. On est revenu aux anciens réglages donc, de 0 à 1 pour les paramètres X, Y et Z. Je viens de mettre à jour le patch sur SourceForge.
