### ISSUE TITLE
OSC n'est plus bidirectionnel entre Open Stage Control sur iPad et ControlGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#149]
V1.1.8, Open Stage Control 1.8.2
Maintenant que les réglages des paramètres OSC sont les bons, et que le patch Open Stage Control a été mis à jour, la communication entre le iPad et ControlGRIS est impeccable, autant en réseau local en wi-fi internet.
Par contre, ControlGRIS n'envoie plus de signal OSC au patch Open Stage Control sur le iPad. Autrement dit, si on bouge les paramètres dans ControlGRIS, le iPad n'est plus mis à jour. Ce dernier cependant est bien mis à jour par le serveur Open Stage Control, ce qui démontre que la communication OSC entre le Mac et le iPad est bonne et que les réglages sont les bons.

**Comment by NicolaGiannini** [comment]
V119, Open Stage Control 1.8.12
Je confirme les mêmes comportements aussi avec V119.
La communication entre le iPad (dans mon cas iPhone) et ControlGRIS fonctionne bien. 
Cependant, ControlGRIS n'envoie pas de signal OSC au patch Open Stage Control. Si on bouge les paramètres dans ControlGRIS, le iPhone n'est pas mis à jour. Par contre la communication entre l'iPhone et le serveur OSC sur le Mac fonctionne bien.

**Comment by Normandeau** [comment]
V119, Open Stage Control 1.9.10
La communication est rétablie! Autant DOME qu'en CUBE.
Une précision: il faut utiliser la même adresse IP pour le Receive on port et le Send on port. Avec respectivement les canaux 9000 et 8000 (canaux par défaut de OSC):

![Capture d’écran, le 2021-06-20 à 11 27 19](https://user-images.githubusercontent.com/8959779/122679861-8aef6880-d1ba-11eb-8141-b72e1cd0fea6.jpg)

Server Open Sound Control (OSC):

![Capture d’écran, le 2021-06-20 à 11 34 02](https://user-images.githubusercontent.com/8959779/122680040-6e9ffb80-d1bb-11eb-96a8-c29424e006e9.jpg)

Peut-être une double vérification Nicola?

**Comment by NicolaGiannini** [comment]
La communication fonctionne aussi dans mon cas, en mode DOME et CUBE. 

Je confirme également cela : 

> 
Une précision: il faut utiliser la même adresse IP pour le Receive on port et le Send on port. Avec respectivement les canaux 9000 et 8000 (canaux par défaut de OSC).

**Comment by Normandeau** [comment]
V1.20
Mis dans le manuel.
