### ISSUE TITLE
Fenêtre pop-up pour l'automatisation des sources autre que 1

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/ControlGris#152]
J'essaie d'automatiser le positionnement d'une source stéréo dont les deux canaux sont en mode "independent" (Source Link). 
Je suis capable d'automatiser seulement le canal gauche. Impossible de bouger l'autre.
Est-ce normal? 

(Je suis dans Live 10 - Mac Os High Sierra)

Mélanie

**Comment by Normandeau** [comment]
V119

![Capture d’écran, le 2021-03-05 à 12 19 42](https://user-images.githubusercontent.com/8959779/110150321-20eab900-7dad-11eb-90cc-382f8cac85f3.jpg)
