### ISSUE TITLE
Impossible d'écraser une automation créée par ControlGris

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/ControlGris#154]
ControlGris v118, SpatGris217, Mode Dôme, High Sierra, Live 10.1.3

J'ai fait plusieurs tests aujourd'hui concernant les automations dans Live.

- Si il n'y a pas d'automation, aucun problème, ControlGris enregistre bien les mouvements sélectionnés avec la fonction _Activate_

- Quand une automation est écrite à la souris ou avec un contrôleur, **hors ControlGris**, on peut écraser ces automations avec la fonction _Activate_ (ControlGris reprend le dessus)

- Par contre, quand une automation a été enregistrée grâce à _Activate_ de ControlGris, il est impossible de l'écraser à partir de ControlGris (je peux la modifier à la main, mais si je veux modifier ma trajectoire avec ControlGris, je dois effacer complètement l'automation - peu pratique quand j'ai déjà des automations satisfaisantes sur la même piste)

Est-ce quelque chose que vous avez remarqué sur d'autres DAW? 
À savoir que Live n'a aucun mode d'automation tels Latch, Touch, Write.

**Comment by SamuelBeland** [comment]
Ce n'est pas normal. Il ne devrait y avoir aucune distinction entre une automation enregistrée à la main ou avec les trajectoires.

- Est-ce le problème persiste si tu fermes et ouvres de nouveau Live ?
- Est-ce que le problème peut être évité en essayant diverses façons de mettre fin à l'automation (cliquer sur _Activate_ vs arrêter la lecture vs désactiver l'enregistrement d'automation) ?

Probablement que ControlGRIS n'indique pas la fin de l'enregistrement d'automation lorsque _Activate_ est stoppé. Live doit penser que le plugin est toujours en train d'envoyer des données et bloquer le reste...

**Comment by MelanieFrisoli** [comment]
En refaisant des essais ce matin, je crois que je viens de comprendre ce qu'il s'est passé hier. 
J'essayais d'enregistrer une nouvelle automation sur une ancienne créée avec le ControlGris mais, entre temps, j'ai changé mes sorties, à la fois sur ma piste et dans ControlGris. Et dans ce cas là, il refuse d'écrire par dessus l'ancienne automation.

**Comment by Normandeau** [comment]
V119
Essayé de reproduire cela dans Live et dans DP. Aucun succès. Dans Live, il n'y a que le mode Overwrite (ou Write) qui devrait toujours effacer les données précédentes et c'est ce que je vois. Dans les autres séquenceurs, peu importe le mode (Write, Latch ou Touch), une trajectoire automatisée va toujours également effacer ce qui est déjà écrit.

**Comment by MelanieFrisoli** [comment]
Ok, parfait. 
Un autre comportement bizarre de Live par moments.
