### ISSUE TITLE
Undo dans ControlGris

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/ControlGris#155]
ControlGris v118, SpatGris217, Mode Dôme, High Sierra, Live 10.1.3

Pas essentielle certes, mais une fonction pour revenir en arrière serait pratique dans ControlGris. 
J'ai eu le réflexe plusieurs fois de cliquer sur "Cmd Z" aujourd'hui, notamment pour revenir à une position d'origine et cela faisait des choses étranges. De plus, replacer les points à la main est moins précis. 
J'ai l'impression néanmoins que ControlGris comprend cette fonction mais il réagit très bizarrement, plaçant le point à un endroit où il n'a jamais été mis, en faisant des tout petits sauts.

**Comment by Normandeau** [comment]
V119
Commentaire général sur les raccourcis clavier. La fonction Cmd-Z ne peut pas appartenir à un plugiciel, car elle est réservée aux séquenceurs. Je viens de faire un test rapide avec 4 plugiciels de différentes compagnies, juste pour valider cela, et je le confirme. Donc cela relève des séquenceurs et se situe hors de notre contrôle. Comment ControlGRIS et les différents séquenceurs interagissent les uns les autres, c'est une histoire de relation un peu compliquée... devant laquelle il faut parfois jeter du lest, sinon, on n'avance pas. Il est d'ailleurs clairement écrit dans le manuel que les utilisateurs doivent bien connaître les spécificités de leurs séquenceurs... 
J'ajouterais que la majorité des plugiciels n'ont pas de raccourcis clavier (genre Cmd-Z), seulement des touches de modifications. Par exemple, en appuyant sur la touche Shift tout en sélectionnant un Preset, celui-ci est effacé. Et cela implique le plugiciel soit au premier plan évidemment. On retrouvera certains raccourcis-clavier standard avec les versions Stand Alone de certains plugiciels comme les GRM Tools par exemple.
Donc à moins que Samuel ait quelque chose d'autre à ajouter, on pourra fermer ceci.

**Comment by MelanieFrisoli** [comment]
C'est exact, j'ai tendance à oublier que le Undo est propre au logiciel car dans Live on peut faire des "undo" sur les effets ou les instruments. Dans plusieurs plugiciels (Arturia, FabFilter, Waves), il y a en effet deux petites flèches (une pour les "undo", un pour les "redo"), dans d'autres (Soundtoys pas exemple), il y a juste un bouton "Reset" pour revenir aux réglages par défaut. 
Donc comme prévu, dans Live, ControlGris réagit au raccourci Cmd + z. Parfois il remet le bouton à la bonne position mais souvent il y a beaucoup trop de Cmd + Z à faire pour un résultat qui manque de précision. Donc je me demandais si il s'agissait d'un bug.
Mais j'ai essayé sur Logic et en effet, le Cmd+Z n'est pas reconnu par ControlGris, juste par le logiciel.

Peut-être qu'un bouton "Reset" serait toutefois utile pour permettre à l'utilisateur de revenir aux réglages par défaut en un clic.

**Comment by SamuelBeland** [comment]
J'appuie Robert là-dessus : ce n'est pas vraiment standard pour un plugin d'offrir la fonction undo. Bien que ça serait _théoriquement_ possible, les chances de déclencher des bugs en interférant avec l'hôte sont assez grandes.

En plus, c'est assez complexe à implémenter...

**Comment by MelanieFrisoli** [comment]
Je comprends tout à fait. J'avais oublié m'être habituée à un comportement spécifique à Live.
On peut fermer ce sujet.
