### ISSUE TITLE
La version VST3 ne fonctionne pas

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#157]
V119
La version VST3 ne fonctionne pas. On ne peut pas passer la barrière érigée par Apple, ça ne fonctionne pas avec la VST3. La fonction Ouvrir quand même ne fait rien. Vérifié avec Live, DP et Reaper (Logic ne prend pas les VST3):

![Capture d’écran, le 2021-03-04 à 12 49 32](https://user-images.githubusercontent.com/8959779/110007380-9771b300-7ce8-11eb-9a98-664fdc2d5ec6.jpg)

**Comment by MelanieFrisoli** [comment]
Vérifié dans Live 10.1.3 et 11.0.
Le VST3 fonctionne dans les deux

**Comment by SamuelBeland** [comment]
[La version 1.1.9 a été mise à jour](https://github.com/GRIS-UdeM/ControlGris/releases/tag/1.1.9) et devrait régler ce problème.

**Comment by Normandeau** [comment]
V218 du 5 mars
Réglé
