### ISSUE TITLE
Automation de ControlGris avec automation de tempo -- Conflit

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/ControlGris#158]
J'ai une automation de tempo dans mon morceau (un ralentissement entre 120 et 60BPM) et ControlGris ne comprend pas bien ce qu'il se passe je passe et l'automation devient même un peu "folle".
Comme on peut voir sur la capture d'écran (en bas, les deux traits rouges sont pour le début et la fin de l'automation de tempo)
![Screen Shot 2021-03-04 at 10 29 56 AM](https://user-images.githubusercontent.com/74631914/110012139-3816a180-7cee-11eb-9af3-244126da87c0.JPG)

**Comment by Normandeau** [comment]
V119
La variation de tempo est d'abord et avant tout une fonction MIDI. Lorsqu'il y a un fichier audio, celui-ci n'est pas  affecté par la variation de tempo, car il est lu à la fréquence d’échantillonnage. La variation de tempo utilisée avec de l'audio va faire en sorte que les fichiers audio vont se succéder plus ou moins rapidement. L'automation de ControlGRIS de son côté est une fonction MIDI affectée par la variation de tempo de cette manière... enfin ça dépend!

Trajectoire de base (un cercle) à 120:
![Automation de bse à 120](https://user-images.githubusercontent.com/8959779/110018320-2be21280-7cf5-11eb-891b-9df8270872e4.jpg)

La même trajectoire lue **après** l'ajout d'une variation de tempo — le cercle va ralentir puis accélérer:
![La même automationlue avec variation de tempo](https://user-images.githubusercontent.com/8959779/110018474-516f1c00-7cf5-11eb-8fe5-682d4c66db95.jpg)

La même trajectoire enregistrée **avec** la variation de tempo — le cercle est stable car la variation de tempo est incluse dedans:
![Automation enregistrée avec variation de tempo](https://user-images.githubusercontent.com/8959779/110018784-ae6ad200-7cf5-11eb-97db-44eb6fc48f0c.jpg)

La même trajectoire lue **sans** la variation de tempo — on voit que le cercle varie bien en vitesse, car la variation de tempo n'est plus là pour faire contrepoids:
![Automation lue sans variation de tempo](https://user-images.githubusercontent.com/8959779/110018873-c6daec80-7cf5-11eb-9384-4861e9bbf792.jpg)

D'où ma question: quand as-tu enregistrée la trajectoire pas rapport à l'écriture de la variation de tempo? En tout état de cause, DP ne semble pas se comporter comme Live. Autre cas de comportement spécifique d'un séquenceur...

**Comment by MelanieFrisoli** [comment]
Oui, les deux séquenceurs réagissent bien différemment. J'aurais aimé que Live me donne d'aussi belles courbes que les tiennes dans DP! 
Pour répondre à ta question, l'écriture de l'automation de tempo est là depuis quelques semaines déjà et j'essayais d'écrire la trajectoire mercredi au studio.

**Comment by NicolaGiannini** [comment]
Dans le cas de Logic 10.5.1, le comportement semble similaire à DP en ce qui concerne la vitesse de la trajectoire dans ControlGRIS par rapport aux changements de tempo. Cependant, dans Logic les courbes des automations des pistes semblent avoir un comportement différent. 


Trajectoire de base (un cercle) à 120:
![120Bpm-2-sec](https://user-images.githubusercontent.com/35705913/110983174-6e2fd300-8337-11eb-9cba-4cf5f88f47c1.jpg)


La même trajectoire lue **après** l'ajout d'une variation de tempo — le cercle va ralentir puis accélérer:

Le dessin de l'automation de la rotation ne change pas.

![variation-tempo-après-automation-trajectoire](https://user-images.githubusercontent.com/35705913/110983203-77b93b00-8337-11eb-8ac7-42721d704f3f.jpg)



La même trajectoire enregistrée **avec** la variation de tempo — le cercle est stable car la variation de tempo est incluse dedans:
Le dessin de l'automation suit la variation du tempo. 

![après](https://user-images.githubusercontent.com/35705913/110983243-83a4fd00-8337-11eb-80e4-fa7353ce852e.jpg)


La même trajectoire lue **sans** la variation de tempo — on voit que le cercle varie bien en vitesse, car la variation de tempo n'est plus là pour faire contrepoids.
Le dessin de l'automation de la rotation ne change pas.

![tempo effacé](https://user-images.githubusercontent.com/35705913/110983258-87d11a80-8337-11eb-9645-36069c300258.jpg)

J'ajoute une note : dans mon cas, les changements de tempo rapides et extrêmes produisent toujours des trajectoires non fluides.
