### ISSUE TITLE
Le link X ou Y semble parfois incohérent particulièrement pour les sources de 3 à 8, lorsque l'on modifie le nombre de sources à plusieurs reprises.

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#16]
Le link X et Y semble parfois incohérent pour les sources de 3 à 8, lorsque l'on modifie le nombre de sources à plusieurs reprises.

Exemple : 
- J'instancie 2 sources
- les déplace dans les cadrans, pour les positionner à des endroits différents,
- ajoute une 3ème source.
- link X sur la source 1

Et maintenant le déplacement de la source 3 suit l'extérieur du cercle, alors que la source 2 non.

Si j'avais instancié les 3 sources dès le départ, le déplacement aurait été cohérent;
Si ce n'est pas clair, je vous le montrerai demain, mais ce comportement semble arriver dans certaines circonstances, que je n'arrive pas toutes à identifier pour l'instant.

**Comment by belangeo** [comment]
Caduque!
