### ISSUE TITLE
Source Placement en conflit avec Source Link

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#161]
V119
- Huit canaux en ordre dispersé en mode Independent:

![Capture d’écran, le 2021-03-16 à 14 00 21](https://user-images.githubusercontent.com/8959779/111358601-e7456800-8660-11eb-86ad-8ceed340763d.jpg)

- Source Link: Circular ou Fixed Radius avec Sources Placement: Left Alternate: excellent.

![Capture d’écran, le 2021-03-16 à 14 09 00](https://user-images.githubusercontent.com/8959779/111358842-2ffd2100-8661-11eb-8150-0f66a87a2533.jpg)

- Source Link: Fixed Angle, Fully Fixed et Delta Lock avec Sources Placement: Left Alternate: ordre différent mais erroné:

![Capture d’écran, le 2021-03-16 à 14 00 47](https://user-images.githubusercontent.com/8959779/111359112-7d798e00-8661-11eb-8b9d-a1f3a86677eb.jpg)

**Comment by Normandeau** [comment]
En fait, sur une piste octophonique correctement sauvegardée dans un projet ancien, les pistes 7 et 8 (ici les numéros OSC 23 et 24) sont systématiquement inversées. Et la fonction Sources placement ne les remet pas au bon endroit:
 
![Capture d’écran, le 2021-03-23 à 14 37 45](https://user-images.githubusercontent.com/8959779/112200450-9f38bf00-8be5-11eb-8d0d-58f50dee169a.jpg)

**Comment by NicolaGiannini** [comment]
Testé dans Logic et Reaper. 

Je confirme que :
Source link : Fixed Angle et Fully Fixed avec Sources Placement: Left Alternate : l'ordre n'est pas correct. 

Dans mon cas, Source link : Delta Lock avec Sources Placement: Left Alternate : l'ordre est correct. 

Source Link : Circular ou Fixed Radius avec Sources Placement: Left Alternate: l'ordre est correct.

**Comment by Normandeau** [comment]
Autre observation curieuse. Lorsqu'on utilise Sources Placement avec Left Alternate, si c'est la source 1 qu'on a touché en dernier, c'est toujours les coordonnées de la source 6 qui s'affichent automatiquement. Toutes les autres options (Right Alternate, Top Clockwise, etc.) affichent celles de la source 8. Enfin, si on enregistre la position des sources dans un preset et qu'on ferme la session, en général à l'ouverture suivante, 7 et 8 sont inversés, mais le rappel du preset les replace au bon endroit.

![Capture d’écran, le 2021-03-23 à 16 18 11](https://user-images.githubusercontent.com/8959779/112212651-a070e880-8bf3-11eb-9994-7a7092b897c9.jpg)

**Comment by Normandeau** [comment]
V120
Dans une octophonie, pour arriver à placer les sources dans le bon ordre avec Left Alternate (qui ne fonctionne pas bien), il faut d'abord faire Right Alternate et ensuite Left Alternate. Mais peut-être est-ce corrigé dans la version 1.21!

**Comment by Normandeau** [comment]
En fait, il faut le faire deux fois pour que ça fonctionne...

**Comment by Normandeau** [comment]
V121
Pas corrigé

**Comment by NicolaGiannini** [comment]
V121
Je confirme que dans mon cas que:
avec Fully Fixed ou Fixed Angle + Left Alternate, l'ordre n'est pas correct 

Avec Delta Lock ou Circular ou Fixed Radius + Left Alternate, l'ordre est correct.

Je confirme aussi que "pour arriver à placer les sources dans le bon ordre avec Left Alternate (qui ne fonctionne pas bien), il faut d'abord faire Right Alternate et ensuite Left Alternate."

**Comment by Normandeau** [comment]
V122
Tout semble en bon ordre maintenant. Y compris la source qui s'affiche dans Source Number lorsqu’on utilise Sources Placement. C'est maintenant systématiquement la Source 1 qui apparaît à cet endroit. Lorsqu'on sauve les positions, qu'on ferme la session et qu'on la rouvre, tout est à la bonne place. Excellent.
