### ISSUE TITLE
Position de départ des trajectoires très problématique: Y contrôle Z

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#162]
V119
J'ai mis un no de version, mais cela a toujours été un problème. Je pense qu'il est temps de le résoudre. J'essaie de faire une chose très simple: générer une trajectoire circulaire en mode CUBE.
- Position de départ, enregistrée dans un Preset:

![Capture d’écran, le 2021-03-16 à 14 24 17](https://user-images.githubusercontent.com/8959779/111360818-98e59880-8663-11eb-94b4-d82614b20b03.jpg)

- Trajectory Type: Circle Clockwise et Realtime
- Je mets les deux trajectoires en mode Activate et je démarre la séquence dans laquelle il n'y aucune automation enregistrée. Voici ce que ça donne au départ. Le groupe s'est déplacé d'un coup de -90˚ et l'élévation s'est placée à un peu plus que la mi-hauteur:

![Capture d’écran, le 2021-03-16 à 14 29 17](https://user-images.githubusercontent.com/8959779/111361247-0265a700-8664-11eb-881d-80a5ba7a08a4.jpg)

- Et si je me place ailleurs dans la séquence de manière arbitraire, le groupe s'est déplacé d'un coup de -170˚ et l'élévation s'est placée au tiers de la hauteur:

![Capture d’écran, le 2021-03-16 à 14 34 09](https://user-images.githubusercontent.com/8959779/111362083-c67f1180-8664-11eb-8dbc-0b5bc99a7899.jpg)

Je ne teste pas plus.
Ça ne devrait tout simplement pas faire cela.

**Comment by Normandeau** [comment]
Ballet d'automation. Je passe d'un marqueur à l'autre dans une séquence où il n'y aucune automation écrite:

https://user-images.githubusercontent.com/8959779/111365098-743fef80-8668-11eb-9c78-e1e9e0d15703.mov

**Comment by Normandeau** [comment]
Comment se fait-il que l'Elevation se mette en mouvement avec la séquence alors qu'elle est en Fixed Elevation et Realtime?

https://user-images.githubusercontent.com/8959779/111366671-3217ad80-866a-11eb-8a72-e99a662a4106.mov

**Comment by Normandeau** [comment]
C'est Azimuth-Distance qui «coule» du côté de l'Elevation. Si un seul des Activate est à On (l'un ou l'autre), Elevation ne bouge pas. Mais si les deux deux sont à On, Elevation oscille de haut en bas (ou l'inverse, c'est imprévisible). En Realtime, il ne devrait pas bouger.
- L'ampleur de l'oscillation est imprévisible
- C'est toujours Back & Forth, que celui-ci soit coché ou non.

**Comment by Normandeau** [comment]
Confirmé dans Reaper

**Comment by NicolaGiannini** [comment]
Logic 10.5.1
Regardons le cas décrit par Robert.
Trajectory Type = Circle Clockwise (Azimuth Distance) et Realtime (Elevation)

En ce qui concerne le carré Azimuth-Distance, le point de départ est le bon si avant de démarrer la séquence je positionne les sources avec la souris ou par un preset. 

Voir la vidéo : 



https://user-images.githubusercontent.com/35705913/112198321-5e3fab00-8be3-11eb-92fd-23e6b4df4af2.mov

Si les sources ont été déplacées en raison d'une trajectoire et que le preset n'a pas été rappelé par la suite, lors du redémarrage de la séquence les sources se remettent dans la position enregistrée dans le preset.

Voir la vidéo : 



https://user-images.githubusercontent.com/35705913/112198365-67307c80-8be3-11eb-81a9-6f8028076d7f.mov




En ce qui concerne le carré Elevation et Trajectory Type = Realtime, dans mon cas l'Elevation, donc la valeur Z, est liée à la valeur Y du carré Azimuth - Distance.
Si Activate est à On pour Elevation et que la valeur Y bouge, soit en le déplaçant avec la souris soit par une trajectoire, la valeur Z bouge en conséquence. 

Voir la vidéo : 


https://user-images.githubusercontent.com/35705913/112198465-83341e00-8be3-11eb-9f8a-f25dbd42f347.mov

**Comment by Normandeau** [comment]
Bravo! Belle observation! Donc c'est Y qui commande Z. On aimerait bien que Z soit indépendant!

**Comment by Normandeau** [comment]
V121
Y contrôle Z est réglé. Je vais fermer cette issue à ce sujet. Je pense qu'on a pas mal de boulot à faire pour que les trajectoires fonctionnent vraiment bien.
On pourra se poser la question de ce qui est nécessaire et utile après la sortie officielle.
