### ISSUE TITLE
Dans les sections Trajectories et  Configuration, mettre "Sources" à la place de "Source".

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#168]
Je me demande si, dans Configuration, le terme "Sources" n’est plus approprié. J'ai pensé à cela aussi  parce que dans le manuel à 4.3 on dit "These settings are grouped under three tabs: Settings, Sources and Controllers." 

![Schermata 2021-07-21 alle 13 39 59](https://user-images.githubusercontent.com/35705913/126535179-11c248fe-db5a-48e4-bd56-a789a16316f2.jpg)

**Comment by Normandeau** [comment]
Considérant le fait que Settings et Controllers sont au pluriel, on pourrait aussi passer au pluriel ici également.

**Comment by Normandeau** [comment]
Sources Link:

![Capture d’écran, le 2021-07-22 à 14 20 06](https://user-images.githubusercontent.com/8959779/126689466-5d2a1c84-c63c-404a-844e-be4fc318bf22.jpg)

**Comment by Normandeau** [comment]
V121
Fait dans Trajectories, mais oublié dans Configuration, toujours au singulier.

**Comment by Normandeau** [comment]
V122
Tout est au pluriel. De mieux en mieux! Va falloir refaire les captures d'écran maintenant!
