### ISSUE TITLE
Une fonction de ralenti/accélération des trajectoires dans ControlGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#173]
V130
La priorité no 1 pour une amélioration de ControlGRIS: Une fonction de ralenti/accélération des trajectoires.
Cela a déjà existé dans SpatGRIS1, ça s'appelait Speed. Mais ça fonctionnait tout croche, donc nous l'avions retiré de la première version de ControlGRIS, et cela jusqu'à aujourd'hui.
Essentiellement, la vitesse des trajectoires dans ControlGRIS est déterminée par le réglage Durée par cycle (Dur per cycle). Il suffirait donc d'ajouter un paramètre diviseur/multiplicateur de celui-ci. Cela pourrait prendre la forme d'une réglette assez longue (meilleure résolution), comparable à celles des Spans, placée à 0 au centre par défaut, et qui s'ajusterait vers des valeurs de ralenti (négatives) ou d'accélération (positives).
Il y aurait de la place pour mettre cette réglette à droite de deviation degrees per cycle.

![Capture d’écran, le 2021-09-13 à 15 06 49](https://user-images.githubusercontent.com/8959779/133142609-9d97f1ca-bbdd-4e12-a58d-5b869363820c.jpg)

**Comment by NicolaGiannini** [comment]
Je seconde !

**Comment by NicolaGiannini** [comment]
Dans MapSPAT on a ajouté une fonction LFO qui permet d’obtenir quelque chose de similaire.


https://github.com/GRIS-UdeM/ControlGris/assets/35705913/08bf0db9-353b-4f00-9989-6ff4b32aa6e2

**Comment by Normandeau** [comment]
V200RC2
Un autre souhait du 13 septembre 2021! Exaucé. Et cela a l'air de fonctionner. Pour la première fois!
Mais l'interface est un peu trop discrète à mon avis. Je sais que ce potentiomètre est affecté à la vitesse, mais qui d'autre le sait? Entre la déviation et la fonction Random:

![Capture d’écran, le 2024-12-17 à 16 07 21](https://github.com/user-attachments/assets/7817bbcd-8450-42d6-99a7-c64eee2e1d7a)

Je sais que Gaël pense que l'interface est trop busy, mais ne pourrait-on pas ajouter le mot Speed à gauche du curseur de gauche:

![Speed](https://github.com/user-attachments/assets/d2d9fbe6-7485-422b-ad30-6f5985a92b25)

**Comment by Normandeau** [comment]
V200RC3
La fonction Speed fonctionne bien. Enfin! Et la fonction est maintenant claire dans l'interface. On aime cela!

![Capture d’écran, le 2024-12-30 à 17 03 15](https://github.com/user-attachments/assets/06821f16-9a76-44f9-ad3a-b754ad1d8470)
