### ISSUE TITLE
Elevation: Source Link et Trajectory Type problématiques

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#175]
V130
Nous avons rebaptisé les liens Bottom-Top et Top-Bottom dans Elevation, mais nous n'avons pas questionné leurs modus operandi! Et ça pose problème. Surtout la modification des positions respectives des sources entre Independent et Bottom-Top et Top-Bottom. On peut en effet positionner les sources de manière indépendante avec la première fonction, mais dès qu'on touche aux deux autres, c'est un preset qui prend le dessus. Et celui-ci n'a pas de valeur esthétique  ou mathématique particulière. Le réglage semble tout simplement arbitraire.
Le problème avec ces réglages, c'est qu'on est toujours soit au plafond, soit au plancher. On ne peut pas positionner des sources à des valeurs intermédiaires, par exemple dans la partie centrale du plan Z. Ou tout en haut ou tout en bas.
Enfin, quand on choisit comme Trajectory Type Down-Up ou Up-Down, on n'a pas le choix de l'échelle. il faut toujours parcourir toute l'élévation. Cela devient un cliché alors.
Ce serait bien de pouvoir ajuster ces valeurs.
On peut toujours compenser avec une combinaison de Drawing et de Delta Lock, mais c'est un peu tarabiscoté!

Positions de départ en mode Independent:
![Capture d’écran, le 2021-09-13 à 16 09 14](https://user-images.githubusercontent.com/8959779/133149664-74c8f11f-6cff-43be-befa-d6bc6c7bf391.jpg)

Positions automatiquement modifiées avec Bottom-Top:
![Capture d’écran, le 2021-09-13 à 16 09 33](https://user-images.githubusercontent.com/8959779/133149716-2e2a14cd-325b-4186-a6dd-f656a150a835.jpg)

Positions automatiquement modifiées avec Top-Bottom:
![Capture d’écran, le 2021-09-13 à 16 12 25](https://user-images.githubusercontent.com/8959779/133150011-f5f06bb2-bd63-4726-8881-940f431b57a5.jpg)

**Comment by NicolaGiannini** [comment]
V130
De ce que je comprends dans le cas de deux sources, le Sources Link “Bottom-Top” positionne la source orange (2) à une valeur de Z de + 0.67 par rapport à la source bleue (1). 

Notamment, quand je passe de Source Links “Indipendent” à Sources Link “Bottom-Top” : 

- Si la source 1 est à Z = 0.10, la source 2 va se positionner à Z=0.77. 
- Si la source 1 est à Z=0.20, la source 2 va se positionner à Z=0.87. 
- Si la source 1 est à Z=0.40 la source 2 va se positionner à Z=1. Pour des valeurs de Z supérieures à 0.37 de la source 1, la source 2 sera toujours positionnée à 1. 

Dans le cas de trois sources, la deuxième source est positionnée à +0.33 de la première, la troisième à + 0.67 de la première.

Dans le cas du Sources Link “Top-Bottom” on a le comportement inverse :

- Dans le cas de 3 sources, la deuxième est placée à -0.33 de la première.
- Dans le cas de 2 sources, la deuxième est placée à -0.67 de la première.

Robert :

Enfin, quand on choisit comme Trajectory Type Down-Up ou Up-Down, on n'a pas le choix de l'échelle. il faut toujours parcourir toute l'élévation.

Je suis d'accord qu’il serait pratique de pouvoir avoir le choix de l'échelle.

**Comment by Normandeau** [comment]
V200RC3
Voici l'échelle. En combinant cela avec des spirales Back & Forth on arrive à fabriquer des figiures assez jolies! Faudra faire des vidéos pour vendre notre «produit»!
