### ISSUE TITLE
Mini-erreur de triangulation - Template Dome32(12-10-8-2)Sub2 UdeM UFX+

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/ControlGris#177]
V313
Dans le template Dome32(12-10-8-2)Sub2 UdeM UFX+, il y a une triangulation en trop. 
Je ne sais pas dans quelle mesure cela affecte le rendu. 
C'est le seul template (en dôme) dans lequel j'ai constaté cela. 

<img width="727" alt="Screen Shot 2022-02-03 at 11 33 43 AM" src="https://user-images.githubusercontent.com/74631914/152389758-b530d580-64b3-49f8-a041-4ef3796ffbdb.png">

**Comment by Normandeau** [comment]
Commentaires:
- cette issue ne concerne ControlGRIS mais SpatGRIS3.
- Peux-tu replacer cette issue à la bonne place, en remplaçant cette image avec une image avec les nos de hp. Parce que là on n'est pas capable de valider (quand ça sera fait je l'effacerai ici).
- Enfin de mon côté, tous les templates sont corrects. Je les avais tous vérifié avant leur publication récente.
- Donc: d'où vient ce template? De la version 3.1.3?
