### ISSUE TITLE
Une version compilée de ControlGRIS pour les M1

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/ControlGris#178]
Ce serait super d'avoir une version compilée pour les nouvelles puces M1 à un moment donné.
La version Audio Unit est utilisable malgré quelques bugs (le bouton Activate reste enclenché même quand on stoppe la lecture, quelques soucis avec les Undo). 
Pourtant, il y a une caractéristique mise en place par l'OS pour que tout fonctionne comme il faut, le fameux AUHostingCompatibilityService.

**Comment by Normandeau** [comment]
Pour l'instant rien n'indique dans ControlGRIS sous quel mode il fonctionne, contrairement à certains applications déjà fonctionnelle sous M1. On sait cependant, grâce à la version utilisée dans l'ordi de Mélanie que c'est sous Rosetta. Apple a annoncé deux ans de compatibilité Rosetta. Et les M1 date d'un an et demi déjà...

**Comment by Normandeau** [comment]
V132
Ça fonctionne bien.
