### ISSUE TITLE
Écriture d'automations et ControlGRIS qui se cogne

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/ControlGris#179]
J'ai régulièrement ce problème quand je veux écrire (et non enregistrer) des automations. 
Comme si il avait atteint une limite et qu'il continuait à se "taper" la tête contre le mur (voir vidéo ci-dessous). Le problème c'est que ça se voit (et ça se ressent) dans SpatGRIS. Est-ce qu'il y aurait un moyen pour qu'il reste stable peu importe les valeurs d'automations écrites ? 

https://user-images.githubusercontent.com/74631914/156453594-0cbfb49b-6328-4c95-9cd9-eaa80d924d51.mp4

**Comment by Normandeau** [comment]
C'est quoi la différence entre «écrire» et «enregistrer» des automations?
dans la vidéo, les automations sont bel et bien enregistrées dans le DAW. On a l'impression que ControlGRIS oscille entre deux types de valeur: les valeurs enregistrées d'une part, et d'autres valeurs. Qui viendraient d'où? Y a -t-il une automation enregistrée pour le source 2?

**Comment by MelanieFrisoli** [comment]
Non, je n'ai pas d'automation pour la source 2 et il n'y a pas d'autres valeurs reçues.
Si je précise que les automations sont écrites plutôt qu'enregistrées,  c'est qu'en les écrivant j'ai l'impression qu'on peut avoir des "erreurs" de valeurs. x ne peut pas être au minimum si y n'est pas à 0.5 (je ne sais pas si c'est très clair). 
En tout cas, j'ai essayé de reproduire ce "cognement" des sources et je n'ai pas encore réussi, mais ça m'arrive régulièrement. J'arrive à le corriger en modifiant mon automation.

**Comment by NicolaGiannini** [comment]
Je pense qu'il existe des couples de valeurs des automatisations "recording trajectory x" et "recording trajectory y" pour lesquels la position de la source 1 peut se trouver en dehors du cercle "Azimuth Span" de ControlGRIS en mode DOME.  ControlGRIS essaie en quelque maniere de déplacer la source 1 hors du cercle, ce qui provoque, je pense, les glitchs montrés dans la vidéo de Mélanie. Si par contre nous utilisons le mode CUBE, la source 1 peut sortir du cercle et alors nous n'avons pas des glitches.
Il est possible de générer ces couples de valeurs qui déplacent la source en dehors du cercle en mode DOME, par exemple si après avoir enregistré une automation, nous effectuons des changements sur cette automation. 
Voir la vidéo : https://www.dropbox.com/s/9wkh6fn2qj1g2jk/sources-hors-cercle-.mov?dl=0

On peut aussi créer des glitches si on dessine directement l'automatisation, par exemple avec l'outil crayon. Il me semble que les glitches se produisent lorsque les deux courbes d'automatisation sont opposées et en mouvement (avec des données qui feraient sortir la source du cercle).

Voir la vidéo : https://www.dropbox.com/s/mf4wfmdlb945uc6/crayon-.mov?dl=0

**Comment by Normandeau** [comment]
V132
Bravo, très belle démonstration. Donc pas vraiment un problème, mais plutôt une utilisation «abusive» des valeurs disponibles.

**Comment by MelanieFrisoli** [comment]
En fait, je me demandais si c'était possible que les sources ne se "cognent" pas et ne tremblotent pas quand elles heurtent une limite. Au lieu de ce comportement, elles pourraient rester "collées" sur le bord du dôme peut-être ?
