### ISSUE TITLE
Activation OSC en passant de LBAP à VBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#18]
V 0.001
Lorsqu'on passe du VBAP au LBAP, les sources audio et la transmission OSC continuent de fonctionner normalement.
Par contre, lorsqu'on le fait dans le sens inverse et qu'on passe du LBAP au VBAP, on doit réinitier l'envoi OSC de chacune des sources afin qu'elles redeviennent actives et laissent passer l'audio. Le bouton Activate OSC ne suffit pas, il faut bouger chacune des sources séparément pour les réactiver une à une.
J’imagine qu'il ne sera pas très courant de faire cette manœuvre, mais en tout état de cause ce serait bien de prévoir que l'OSC est réactivée pour l'ensemble des sources lorsqu'on passe d'un mode à l'autre.

**Comment by belangeo** [comment]
Note à moi-même: À tester sous MacOS, je n'arrive pas à reproduire ce problème sou linux.

**Comment by Normandeau** [comment]
V 1.000
Problème réglé.
