### ISSUE TITLE
Les sources octos en mode groupé deviennent indépendantes après être passé par le centre

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#182]
V133
Rapporté par un utilisateur:
«When we make a circle, lock the source positions together and then drag it slowly across 90° the sources suddenly become independent again. The video below will explain better.»

https://user-images.githubusercontent.com/8959779/175329759-9803b74c-670e-4a67-806e-c4c3c78d2ffe.mov

**Comment by Normandeau** [comment]
V134
Le bogue avec le mode Circular Fixed Angle semble bien réglé. À confirmer. Bravo pour la description très précise Nicola. Et pour avoir réglé ce problème Gaël.

**Comment by NicolaGiannini** [comment]
V134
Le bouge décrit semble être réglé aussi dans mon cas.
