### ISSUE TITLE
Passage d'un mode Link à l'autre : les sources ne se regroupent pas bien à partir de la valeur d'Elevation 1 en mode Dome

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#184]
V1.34
Si je déplace la source 1 au centre du cadran rapidement à l'aide des outils dans le tab "Sources", les autres sources ne se placent pas à la bonne place. Cela est encore plus évident si je tape la valeur (1) pour l'élévation (dans le cas DOME).

Cela se vérifie :

- en mode DOME et CUBE
- avec le Source Link Circular et Circular Fixed Angle 
- avec un nombre des sources entre 2 et 8 et seulement avec la source 1.

Si, après avoir placé la source 1 au centre, je touche une des autres sources, elles sont placées au bon endroit.

Vidéo : 

https://user-images.githubusercontent.com/35705913/185660063-9e7aa0a0-7736-4536-8993-d77e29697f2b.mp4

**Comment by Normandeau** [comment]
Il semble y avoir un autre problème dans la vidéo. Lorsque les sources devraient être regroupés au centre par l'ajustement de l'Elevation à 1, elles ne le sont pas. Je n'arrive pas à reproduire cela.
![Capture d’écran, le 2022-08-07 à 10 48 00](https://user-images.githubusercontent.com/8959779/183296790-f902f41f-b3f3-45a2-85f7-227d3447ae38.jpg)

**Comment by NicolaGiannini** [comment]
Robert :

> Il semble y avoir un autre problème dans la vidéo. Lorsque les sources devraient être regroupés au centre par l'ajustement de l'Elevation à 1, elles ne le sont pas.

Je voulais dire exactement cela. Désolé je me suis mal expliqué! 
Et je viens aussi de noter que cela arrive seulement en Source Link Circular Fixed Angle. Désolé pour la confusion. 

En résumant : 
Source Link Circular Fixed Angle, lorsque les sources devraient être regroupées au centre par l'ajustement de l'Elevation à 1 de la source 1, elles ne le sont pas. Cela arrive si on met l'Elevation à 1 grâce aux sliders dans le tab Sources, ou en insérant directement le chiffre 1 dans Elevation. Cela se produit en déplaçant la source 1.

Je décris les étapes qui conduisent à ce comportement, mais il se peut que cela dépende de ma configuration particulière.

- Je mets ControlGRIS sur une piste.
- Je mets Number of Sources à 8.
- Je mets Source Link Circular Fixed Angle
- J'insère le chiffre 1 dans Elevation dans le tab Sources.
Les sources ne sont pas regroupées au centre.

**Comment by Normandeau** [comment]
Autres précisions.
• 1e observation. Effectivement quand on met le 1 dans Elevation, seule la source 1 se déplace au centre. Par contre dès qu'on bouge le potentiomètre, les autres sources se mettent en place.
• 2e observation. Les sources ne se mettent pas toujours en place correctement au centre avec la source 1 selon la vitesse avec laquelle on déplace le curseur. Lorsque qu'on le déplace rapidement, elles ne se positionnent pas correctement. Par contre quand on le fait lentement, elles se mettent toute au centre comme on s'y attend.
• 3e observation. Les autres modes sont impeccables.

Ça semble un bogue assez mineur. À moins que ça ne révèle autre chose? La question est: est-ce que c'est un problème pour l'usager? À priori, je ne le penserais pas. Donc peut-être pas une urgence nationale?

https://user-images.githubusercontent.com/8959779/185177756-5b45e1f9-c384-4303-b42d-412a6b94df61.mov

**Comment by Normandeau** [comment]
Correction.
Le bogue semble bien réel avec Circular comme décrit plus haut. Voici une nouvelle séquences d'actions qui mènent toujours au même résultat.
• Octo
• Circular Fully Fixed et Sources Placement à Left Alternate
• Elevation de la source 1 à 1: toutes les sources se positionnent au centre et si on les bouge avec la souris, elles se déplacent solidairement, comme on s'y attend
• Circular Fully Fixed et Sources Placement à Left Alternate et Elevation de la source 1 à 1 et ensuite passage à Circular: en la bougeant avec la souris ou avec le curseur, la source 1 devient indépendante. Plus moyen de la relier aux autres. 
• Même séquence mais avec un passage de Circular Fixed Angle ou de Circular Fixed Radius à Circular: en la bougeant avec la souris ou avec le curseur, la source 1 devient indépendante. Plus moyen de la relier aux autres.

**Comment by NicolaGiannini** [comment]
Je confirme le comportement décrit par Robert.

**Comment by Normandeau** [comment]
V140
Aucun changement ici au bogue décrit dans la procédure ci-haut. Ça demeure une situation exceptionnelle voire rarissime! Qui veut changer de Source Link au moment où toutes les sources sont réunies au sommet du dôme? Puisque en passant de Fixed Angle-Fixed Radius-Fully Fixed à Circular, ça ne change strictement rien à la position respectives des sources entre elles.
Donc je pense qu'on peut enterrer cela, jusqu'à ce qu'un zombie, dans son sous-sol ne nous la ressorte.
