### ISSUE TITLE
Positions inversées des sources 5 à 8, en ouvrant ControlGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#186]
V 1.3.4
Ceci est un vieux bogue qui refait surface périodiquement. Voir #62 , #104 , #111  et #161 .
Chaque fois on pense que c'est corrigé, mais ça revient comme l'herbe à poux! Dome et Cube sont différents:

Dome. En général, ce sont les sources 7 et 8 qui sont inversées:
![Dome 1-2-3-4-5-6-8-7](https://user-images.githubusercontent.com/8959779/190011755-5f4e41cd-6b38-4f3b-8f7b-150d49046678.jpg)

Cube. En général, ce sont les sources 5 à 8 qui sont inversées:
![Cube 1-2-3-4-8-6-5-7](https://user-images.githubusercontent.com/8959779/190011913-bd1a1e7a-a018-4144-8cb8-5e0260775ce3.jpg)

Solution: positionner les sources adéquatement, enregistrer un preset, et écrire une donnée d'automation pour rappeler le preset avant le début de l'audio.

**Comment by NicolaGiannini** [comment]
V 1.3.4
J'ai essayé de reproduire les issues cités par Robert, mais je n'arrive pas à reproduire ces comportements. 
J'ai essayé avec Logic 10.7.4 et Ableton 10.

**Comment by Normandeau** [comment]
Résultats plus haut: DP11.11
Projet créé avec une piste octo, ControlGRIS Octo, Link Circular Fully Fixed, pas de preset, pas d'automation
Projet sauvegardé et fermé, DAW fermé.
Résultats obtenus à la réouverture.

Testé avec Logic Pro 10.7.4.
Même résultat qu'avec DP (7 et 8 inversés):

![Logic 1-2-3-4-5-6-8-7](https://user-images.githubusercontent.com/8959779/190228411-2bdde473-bef7-47fd-ba08-028581023bda.jpg)


 et Reaper 6.63
Pas de problème.

PS Je ne me souviens plus comment on met un ControlGRIS en octo dans Live!

**Comment by Normandeau** [comment]
V140
J'ai rouvert une dizaine de projets, tous plus ou moins récents avec DP11. Sauf quelques projets sauvegardés très récemment, ils s'ouvrent tous tout croche avec la position des sources 7-8 (Dome) ou 5 à 8 (Cube) inversées. Mais en faisant les corrections, en enregistrant les presets, en sauvant à nouveau les projets, en fermant le séquenceur, en rouvrant celui-ci et en rouvrant les projets, dans la plupart des cas, les sources octophoniques sont bien positionnées.
Mais pas toujours.

J'ai eu quelques cas  de positions 13 à 16 inversées en mode Cube:
![Capture d’écran, le 2022-10-21 à 16 13 33](https://user-images.githubusercontent.com/8959779/197286506-36ba6153-c60c-4d54-9ecb-83449a08b10e.jpg)

Et quelques cas où les numéros sont dans le bon ordre mais où les sources ne suivent pas la source no 1 (ici, le no 9) en mode Dome:
![Capture d’écran, le 2022-10-21 à 16 19 23](https://user-images.githubusercontent.com/8959779/197286684-1d3e9bb3-b812-402b-9e2c-67af1d8d8015.jpg)

Donc grosse amélioration. Situation toujours à suivre.

**Comment by Normandeau** [comment]
Rouvert tous les projets corrigés et sauvegardés hier. Pas mal tout bon. Donc on va fermer cela. Jusqu'à la prochaine fois... puisque c'était la 5e version du même bogue!
