### ISSUE TITLE
Automation de Normal/Extended Top pour Z?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#190]
V140
Je me pose la question de savoir si ce serait pertinent de pouvoir automatiser la fonction Normal/Extended Top?
Pourquoi?
Parce ce que dans un mode ou dans l'autre, la valeur écrite de Z est la même: de 0.00 à 1.00. Alors si un compositeur oublie qu'il a utilisé la fonction Extended Top par exemple et que ControlGRIS retombe en mode Normal, il n'aura plus accès aux anges! Et on ne veut surtout pas cela!!!

**Comment by NicolaGiannini** [comment]
Je seconde !

**Comment by DavidPiazza** [comment]
Je seconde également.

**Comment by Normandeau** [comment]
V200RC2
C'est fait

![Capture d’écran, le 2024-12-17 à 16 00 23](https://github.com/user-attachments/assets/0794eb4f-99ab-4e28-9233-8aba323f2fff)
