### ISSUE TITLE
Max/MSP: Crash avec la version VST3

### ISSUE THREAD

**Issue by DavidPiazza** [GRIS-UdeM/ControlGris#192]
macOS 13.2.1, M2 Max

Max 8.5.3

La version VST3 fait planter Max lorsqu'on en charge une instance. Cela ne se produit pas avec la version VST, AU ainsi qu'avec mes autres plugiciels VST3. Je note que cela n'est pas le cas dans Reaper ou Ableton, le problème survient spécifiquement dans Max.

https://user-images.githubusercontent.com/50223477/230924619-9b692fd7-78cd-45c6-8667-169d541eb763.mov

https://user-images.githubusercontent.com/50223477/230924635-eab64dfd-33ac-4052-9d18-83ec44d5adea.mov

**Comment by Normandeau** [comment]
Mac M2
macOS 13.4.1 (Ventura)
ControlGRIS 1.4.1

Live 11.3.4
Les versions VST et VST3 font crasher Live. Seule la version AU fonctionne.

Reaper 6.81
La version VST fait crasher Reaper. AU et VST3 fonctionne.

DP 11.22
Toutes les versions fonctionnent.

Logic Pro 10.7.9
Seule la version AU est compatible.

**Comment by NicolaGiannini** [comment]
Mac Intel
MacOS 12.6.7 (Monterey)
ControlGRIS 1.4.1

Max 8.5.3

Je confirme que la version VST3 fait crasher MAX. Je confirme aussi que les versions VST et AU ne font pas crasher MAX.

Ableton 11.3.4 et 10.1.43
Dans mon cas, toutes les versions fonctionnent (je suis sur MacIntel).

Logic 10.7.6
Tout est beau pour la version AU.

Reaper 6.81
Dans mon cas, toutes les versions fonctionnent (je suis sur MacIntel).

**Comment by hectorC** [comment]
> Mac Intel MacOS 12.6.7 (Monterey) ControlGRIS 1.4.1
> 
> Max 8.5.3
> 
> Je confirme que la version VST3 fait crasher MAX. Je confirme aussi que les versions VST et AU ne font pas crasher MAX.
> 
> Reaper 6.81 Dans mon cas, toutes les versions fonctionnent (je suis sur MacIntel).

I get the same on my Windows 11 desktop with ControlGRIS (1.4.3): VST3 crashes Max (8.6.2) and both VST and VST3 work fine in Reaper (7.15).

**Comment by Normandeau** [comment]
Version 1.4.4 sur M2, macOS 14.6 (Sonoma)
• Reaper 7.22
AU, VST et VST3: OK.
• Live 11.3.30
AU et VST3 OK. VST Crash.
• DP 11.32
AU et VST3 OK. VST non-compatible.
• Logic Pro 11.0.1
Seule la version AU est compatible.
• Pro Tools 2023.12
Seule la version AAX est compatible.

**Comment by Normandeau** [comment]
V144
David: Malheureusement, Max plante toujours lorsqu’on charge la version VST3 de ControlGRIS 1.4.4. VST aussi; la seule qui ne cause pas de problème est la version audio unit...

**Comment by Normandeau** [comment]
V145
Problème réglé avec le VST3 dans Max. Ça fonctionnait déjà bien partout avec la version 1.44.
