### ISSUE TITLE
ControlGRIS, mode CUBE, on pourrait indiquer X,Y et Z dans l’interface au lieu de Azimuth, Distance et Elevation ?

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#193]
V141

En travaillant sur le manuel, je me suis posé la question suivante. 
Étant donné qu'en mode CUBE, ControlGRIS gère les coordonnées cartésiennes X,Y et Z, serait-il une bonne idée de mettre X et Y dans la fenêtre de droite et Z dans la fenêtre de gauche au lieu de Azimuth, Distance et Elevation ? 

C'est aussi parce que dans l'onglet Sources en mode CUBE, les paramètres disponibles sont XYZ. 

En mode DOME, dans l'onglet Sources, les paramètres disponibles sont Azimut et Distance, et ce sont bien ces paramètres que l'on voit apparaître dans le carré de l'interface DOME.

![Schermata 2023-05-11 alle 14 08 47](https://github.com/GRIS-UdeM/ControlGris/assets/35705913/84144d5e-75f1-40a6-931f-4b52dc4132e5)
Mode CUBE

![Schermata 2023-05-11 alle 14 08 56](https://github.com/GRIS-UdeM/ControlGris/assets/35705913/5f8c3aad-6e69-469b-8891-9de7f48453ad)
Mode DOME

Qu'en pensez-vous ?

**Comment by Normandeau** [comment]
Très bonne observation. À se remémorer lors de la refonte de ControlGRIS.

**Comment by led78** [comment]
Bien d'accord! Je pense que la distinction entre les concepts de coordonnées spatiales sphériques (θ, φ, ρ) et cartésiennes (X, Y, Z) devraient être explicites!

**Comment by Normandeau** [comment]
V200RC2
C'est fait.
