### ISSUE TITLE
⚗️ Vérifier le fonctionnement du Leap Motion Controller 2 avec ControlGRIS

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ControlGris#194]
D'après l'article publié aux JIM 2023, ControlGRIS peut être contrôlé par le Leap Motion. Il serait bien de valider que c'est également possible avec le nouveau model [Leap Motion Controller 2](https://www.ultraleap.com/product/leap-2/).

**Comment by Normandeau** [comment]
Oups! Je ne sais pas où tu as vu cela, mais la Leap n'a jamais été intégré dans nos outils. En tout cas ce n'est certainement pas dans l'article que j'ai présenté il y a deux semaines à Paris... Lemur et Open Sound Control oui.

**Comment by led78** [comment]
Effectivement, lorsque la nouvelle Leap est sortie, je suis allé voir dans le Manuel d'utilisation de SpatGRIS et je n'ai pas lu que la Leap faisait partie des contrôleurs testés avec ControlGRIS. Je n'ai donc pas publié ce billet sur le coup. Ce n'est qu'en lisant l'[article publié aux JIM 2023](https://jim2023.sciencesconf.org/data/pages/1_1_NORMANDEAU_GIANNINI_LEPINE.pdf) que j'ai lu la mention de la Leap Motion... (Section 4. au bas de la page) D'où ma publication. Peut-être était-ce une erreure?

**Comment by led78** [comment]
Reste que c'est toujours bien de l'essayer et de le noter dans le Guide, même si ce n'est pas un feature de ControGRIS à proprement parler.
C'est pour cela que j'ai mis un [Gitmoji](https://gitmoji.dev/) représentant une expérimentation dans le titre :)

**Comment by led78** [comment]
Remercions Mourad qui a testé ce matin ControlGRIS avec la Leap Motion 2 fraichement reçue : ça fonctionne!

Je fermerais donc ce billet et on peut ajouter cela au Manuel si vous voulez.

**Comment by Normandeau** [comment]
Merci À Mourad pour le test. Est-ce qu'il y a une configuration particulière à faire pour que ça fonctionne? ou des instructions spécifiques. Pour Open Stage Control et Lemur, on a rédigé un addendum. Ce n'est pas dans le manuel à proprement parler.
