### ISSUE TITLE
Diameter plutôt que Radius

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#2]
En fait c'est plutôt un Diameter qu'il nous faut comme fonction, plutôt qu'un Radius. Il faut qu'on puisse traverser tout l'espace déterminé par les haut-parleurs, et non pas seulement le rayon de celui-ci.
On vient de changer le nom de Radius pour Distance. Mais cette distance ne peut pas être calculée seulement du centre vers les bords. Il faut pouvoir parcourir soit le diamètre entier du dôme, ou la largeur complète du carré ou du rectangle avec cette fonction.

**Comment by belangeo** [comment]
C'est le rôle des coordonnées X-Y-Z de permettre de traverser l'espace d'un côté à l'autre... En azimuth-elevation-distance, traverser d'un côté à l'autre avec le paramètre distance entre en conflit avec la valeur d'azimuth.
