### ISSUE TITLE
Nombre de décimales pour AudioDescriptors

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#200]
Ça y est, c'est parti! Les AudioDescriptors font partie de nos outils. Pour l'instant sous la forme d'un plugiciel indépendant (baptisé AudioDescriptors: est-ce assez clair...) qui communique des données OSC à ControlGRIS. Cette fonction avait été ajouté dans les souhaits en janvier 2022, issue  #176. Bravo à Hicheme, notre stagiaire, et Gaël, notre programmeur, de nous fournir aujourd'hui la première version de ce projet.
ADV0.0.1
CG1.4.4
Question: Est-ce vraiment nécessaire d'afficher 7 décimales après le point dans les paramètres de AudioDescriptors? Poser la question c'est y répondre? Je ne remets pas en question la précision des calculs (quoique...), mais simplement leur affichage. Est-ce que 2 décimales suffiraient. Même une seule suffirait lorsqu'il est question de la fréquence en Hz par exemple.

**Comment by NicolaGiannini** [comment]
Bravo Gaël et Hicheme !!! ⚡️
Je suis d'accord avec Robert : Même une seule suffirait lorsqu'il est question de la fréquence en Hz par exemple.

**Comment by Normandeau** [comment]
V002
Le nombre de décimales affichées a baissé, mais une seule suffirait en général.

**Comment by Normandeau** [comment]
V200RC2
Le nombre de décimales est excellent comme cela.
