### ISSUE TITLE
La valeur de CG osc id d'AudioDescriptors est toujours remise à 1 et un seul ControlGRIS peut recevoir de l'OSC de ce dernier

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#201]
ControlGRIS 1.4.4, Controllers Receive on port: IP 9000 à On
AudioDescriptors 0.0.1

Une session avec 4 pistes audio mono, un AudioDescriptors et un ControlGRIS par piste. Le même fichier audio est utilisé sur les 4 pistes et les mêmes paramètres - Pitch et Loudness — sont assignés à Azimuth et Elevation en mode DOME.
Je suppose que le paramètre CG osc id correspond à First Source ID de ControlGRIS?
Déjà, ce serait une bonne idée que les noms correspondent.

La valeur de CG osc id, si on la change de 1 à 4 respectivement pour chacune des 4 pistes, est toujours remise à 1 quand on passe d'une piste à l'autre. Les différentes valeurs ne sont pas mémorisées. On ne peut donc pas spatialiser plus de 1 fichier audio à la fois.
De toute manière, un seul ControlGRIS à la fois peut recevoir de l'OSC sur le port 9000. Lorsqu'on coche ce port sur un 2e ControlGRIS, le premier est désélectionné... mais pas toujours! D'où une certaine confusion. Si je passe de la piste 3 à la piste 4 par exemple et que j'oublie de désectionner le port 9000 de la piste 3, il arrive parfois que le le port 9000 de la piste 4, même sélectionné, ne fonctionne pas.

**Comment by NicolaGiannini** [comment]
ControlGRIS 1.4.4, Controllers Receive on port: IP 9000 à On
AudioDescriptors 0.0.1

Je confirme que je ne peux pas non plus spatialiser plus d'une source. Il me semble que seule la première instance de plugin activée fonctionne.

Dans Ableton Live 10, la valeur CG osc id est toujours réinitialisée à 1 si je ferme l'instance du plugin. Si je sélectionne une autre piste, la valeur reste correcte, mais je pense que cela se produit parce que j'ai une option réglée pour que toutes les fenêtres de plugin restent toujours ouvertes.

Dans mon cas, même si la valeur CG osc id est automatiquement réinitialisée à 1, elle semble toujours envoyer au bon canal OSC.
Dans mon cas :
CG osc id =2
Je ferme la fenêtre d'instance du plugin.
CG osc id montré=1
Mais controlGRIS reçoit toujours sur le canal 2.

**Comment by OKGougou** [comment]
Je viens d'ajouter la persistance des données pour AudioDescriptors. Ce sera vraiment plus simple de tester avec les bonnes valeurs affichées...

Sinon «CG osc id» doit correspondre à «OSC output plugin ID» de la section Controllers de ControlGris. Et pour avoir plusieurs instances de ControlGris/AudioDescriptors, chaque couple doit utiliser un port OSC différent.

**Comment by Normandeau** [comment]
AD V002
Réglé
