### ISSUE TITLE
Décalage du Elevation Span en mode LBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#21]
Lorsqu'on active les Spans en mode VBAP, ceux-ci sont toujours centrés sur la source:

![vbap spans](https://user-images.githubusercontent.com/8959779/50057546-d2a05f80-0139-11e9-8199-a217daeabb08.jpg)

Par contre en mode LBAP, le mode Elevation est décalé par rapport à la source:

![lbap spans](https://user-images.githubusercontent.com/8959779/50057552-e8158980-0139-11e9-8c8e-6fab5f6ba7e5.jpg)

Lorsqu'on regarde le résultat dans le ServerGRIS, tout est OK, autant dans la vue 2D que dans la vue 3D:

![servergris elevation span](https://user-images.githubusercontent.com/8959779/50057608-f44e1680-013a-11e9-8fc5-b853926822c8.jpg)

Il y a donc un problème de représentation dans le ControlGRIS. Problème graphique seulement?

**Comment by belangeo** [comment]
Le problème vient du fait que la vue 2D dans le ControlGris, en mode LBAP, affiche azimuth-distance tandis que les spans concernent azimuth-élévation... Je ne sais pas trop ce qu'on peut y faire... On n'affiche pas les spans en LBAP?

**Comment by belangeo** [comment]
C’est réglé.
