### ISSUE TITLE
Mauvaise interaction entre Source Link et Source Placement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#23]
Si je place mes deux sources en Left Alternate dans Configuration -> Source:

![Left Alternate](https://user-images.githubusercontent.com/8959779/61597204-7f185780-abdb-11e9-8fbb-ec7520c3c6a4.jpg)

la position de celles-ci est automatiquement ramenée à Top Clockwise après avoir choisi Circular Fixed Angle ou Circular Fully Fixed (ça ne le fait pas avec Circular, Circular Fixed Radius ou Delta Lock):

![Left Alternate après Cicular Fully Fixed](https://user-images.githubusercontent.com/8959779/61597208-96574500-abdb-11e9-9a11-242a14e0d0a3.jpg)

**Comment by Normandeau** [comment]
En complément d'information, si je change le Ray Length dans l'onglet Source après avoir choisi Left Alternate, la Source sélectionnée se place automatiquement à un angle de 0˚ quelque soit la valeur affichée en Angle (ici à 90˚, soit la valeur normale pour Left Alternate).
C'est probablement relié au fait que les valeurs dans Source ne sont pas mises à jour avec les valeurs affichées dans l'écran graphique (contrairement au SpatGRIS). C'est cela que Nicola a représenté dans sa vidéo:

https://www.dropbox.com/s/27twnl3c6l4nl3w/ray%20angle.mov?dl=0 

![Ray Length](https://user-images.githubusercontent.com/8959779/63116674-351b5b00-bf68-11e9-8677-a2b8fe4c3716.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme le même comportement dans logic.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno gio 15 ago 2019 alle ore 14:31 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V100b3
Résolu
