### ISSUE TITLE
Placement des sources dans Configuration: au lointain en LBAP? Ray Lenght à 0˚

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#26]
Lorsqu'on place les sources avec l'aide de Configuration -> Source, les sources sont automatiquement placées au lointain en LBAP, autrement dit à un Ray Length de 1.00. Est-ce que c'est ce qu'on veut? Je pense que non. Les sources devraient être placées à la périphérie des haut-parleurs par défaut, soit à Ray Lenght de 0.5. Surtout que lorsque la fonction d'éloignement sera activée dans ServerGRIS, cela signifierait que l'on n'en entendrait pratiquement rien à la valeur par défaut actuelle.
À corriger.
Autre bogue: lorsqu'on place les sources avec l'aide de Configuration -> Source et qu'on change ensuite le Ray Length, la source se déplace automatiquement à 0˚:

![Ray Length](https://user-images.githubusercontent.com/8959779/62941653-91358200-bda4-11e9-9fa0-d615dc36eac3.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme que lorsqu'on place les sources avec l'aide de Configuration ->
Source, les sources sont automatiquement placées au lointain en LBAP,
autrement dit à un Ray Length de 1.00. Et je suis d'accord qui devraient
être placées à la périphérie des haut-parleurs.

Pour le second bague, d'après ce que j'ai compris, si on déplace les
sources en les manipulant avec la souris, et après on touche le slider le
Ray Lenght ou Angle, la source est automatiquement déplacée vers les
valeurs indiquées par le Ray Lenght et le Angle. Dans SpatGris on a pas ce
problème parce que "Ray" et "Angle"  suivent toujours les valeurs de la
manipulation par la souris. Donc on pourrait faire le même en Controlgris,
ou pour le moment les deux valeurs ne sont pas à  jour lorsqu'on manipule
la source avec la souris.
Voir la vidéo
https://www.dropbox.com/s/27twnl3c6l4nl3w/ray%20angle.mov?dl=0
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 13 ago 2019 alle ore 08:30 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Excellente remarque.

**Comment by Normandeau** [comment]
V100b3
Résolu
