### ISSUE TITLE
Aucun enregistrement des trajectoires dans Logic

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#27]
Les trajectoires ne s'enregistrent pas ni dans DP ni dans Logic. Seulement dans Live et Reaper.

**Comment by Normandeau** [comment]
V 100 b2
DP
Ça marche dans DP 10, mais seulement une fois. Si, par exemple, on se rend compte que la trajectoire enregistrée n'est pas la bonne et qu'on recommence en faisant Clear, la trajectoire ne fonctionne plus. Et DP n'enregistre que deux lignes plates.
Logic 10
Ça ne fonctionne pas
Live 10
Ça ne fonctionne pas

**Comment by belangeo** [comment]
Je viens d'installer DP10 et je n'ai aucun problème à enregistrer plusieurs fois des trajectoires... Qu'est-ce que tu entends par « Clear ». Le bouton Clear du plugin ou un clear quelconque de l'automation sur la piste? Comme je ne trouve pas la seconde option, j'assume la première... Dans ce cas, as-tu redessiner quelque chose (Drawing ou une trajectory type) ?

**Comment by belangeo** [comment]
Robert: Le App store me demande ton mot de passe pour mettre Logic à jour!

**Comment by Normandeau** [comment]
V 100 b2
Olivier, voici une vidéo qui reproduit toutes les étapes:
1. Session DP 10, ouverture d'un ControlGRIS sur une piste stéréo
2. Passage en mode LBAP et nombres de sources à 2
3. Source Link en Circular Fully Fixed
4. Positionnement des sources à 90˚-270˚: les angles suivent mais pas le rayon: la source 2 est toujours en mode VBAP, en tout cas tel qu'affiché dans le ControlGRIS. Sur le plan de l'élévation, même en mode Fixed Elevation, seule la source 2 bouge. Dans le ServerGRIS par contre, l'affichage est correct.
5. Positionnement des sources en Left Alternate
6. Enregistrement d'une trajectoire Circle Clockwise de 8s répétée 2 fois
7. Arrêt et jeu de la trajectoire enregistrée
8. Undo dans le séquenceur pour effacer l'enregistrement de l'automation
9. Clear dans ControlGRIS pour effacer la trajectoire précédente et Activate
10. Enregistrement d'une nouvelle trajectoire avec les mêmes réglages: il ne se passe rien, c'est à dire que les sources ne bougent pas. Cette «trajectoire» est cependant enregistrée, mais sans changement de valeurs.

Voici la vidéo:
https://www.dropbox.com/s/zolbxw3e4dpud92/Deuxi%C3%A8me%20trajectoire%20impossible%20apr%C3%A8s%20Clear%20en%20LBAP%20DP.mov?dl=0

**Comment by belangeo** [comment]
Le problème des sources au comportement VBAP en LBAP est réglé (issue #33). Sinon, pour ce qui est de l'enregistrement, je ne vois rien d'anormal dans ce vidéo. Clear efface la trajectoire en mémoire dans le plugin (cercle dans ce cas-ci), il n'y a donc aucun mouvement et le séquenceur enregistre des valeurs fixes. En fait, pour ré-enregistrer la même trajectoire, il n'y avait pas lieu d'appuyer sur Clear. Sinon, il faut en dessiner une autre...

**Comment by Normandeau** [comment]
Ok pour Clear. C'est à mettre dans le manuel. Parce que pour moi c'est très loin d'être clair (jeu de mots facile!). En fait, est-ce que la fonction Clear ne devrait pas être utilisée exclusivement pour Drawing? Pour toutes les trajectoires automatisées, si on modifie un ou des paramètres, cela revient à un reset de la trajectoire. Si je passe de Circle Clockwise à Ellipse Counter Clockwise, la trajectoire est automatiquement modifiée. Même chose si je change sa durée. Pas besoin d'utiliser Clear entre les deux.

**Comment by belangeo** [comment]
En effet, le bouton Clear est là uniquement pour effacer la trajectoire courante dans l'interface. Cette opération a aussi lieu lorsque l'on choisi une autre trajectoire ou lorsqu'on en dessine une nouvelle. Je ne me souviens plus exactement dans quel cas de figure je voulais effacer de façon explicite mais ça m'est arrivé! On verra à l'usage si ce bouton est vraiment nécessaire.

**Comment by Normandeau** [comment]
Logic 10.4.6
Appel à tous: je n'arrive plus à enregistrer aucune trajectoire automatisée, ni avec SpatGRIS, ni avec ControlGRIS, ni même avec ZirkOSC3! J'ai beau chercher des réglages ou des préférences, je ne trouve rien. Une idée?

**Comment by led78** [comment]
Il faudrait préciser si le problème se produit que sur piste stéréo et +, mais pas avec une piste mono.

**Comment by led78** [comment]
> Logic 10.4.6
> Appel à tous: je n'arrive plus à enregistrer aucune trajectoire automatisée, ni avec SpatGRIS, ni avec ControlGRIS, ni même avec ZirkOSC3! J'ai beau chercher des réglages ou des préférences, je ne trouve rien. Une idée?

Je n'ai pas la version 10.4.6 puisque je suis toujours sur Sierra (10.12.6).

**Comment by belangeo** [comment]
Il semble, en effet, y avoir un problème avec JUCE et les version récente de Logic (10.4.5 est la première problématique). Un truc étrange est que si je suis en Latch sur une piste avec un ControlGris et que je met un plugin perso sur une autre piste (en Latch aussi), lorsque je bouge un paramètre de cet autre plugin, l'automation du ControlGris s'écrit (seulement lorsque ça bouge), mais pas celle du plugin perso...! J'investigue...

**Comment by NicolaGiannini** [comment]
*Logic 10.4.6*

*MacOs 10.13.6*


*SpatGris*

écriture d’une automation en mode manuel, ça marche.

écriture d’une automation en utilisant les trajectoires ça marche pas


vidéo https://www.dropbox.com/s/myshdicv13b1ec4/SpatGris-automation.mov?dl=0


*SpatGris et ContolGris*

Si j’écris une automation en mode manuel dans SpatGris, ça marche jusqu'à
ce que j'active une trajectoire dans une instance de ControlGris. (en plus
quand j’active la trajectoire en ControlGris  j’obtiens souvent une erreur
de synchronisation)


vidéo  https://www.dropbox.com/s/pii8co1d6wepk9q/SpatContr.mov?dl=0



*SpatGris et ContolGris 2*

Si j’écris une automation en mode manuel dans SpatGris, ça marche jusqu'à
ce que j'active une trajectoire dans une instance de ControlGris. Si la
piste de ControlGris est en mode LATCH, l’automation est écrite sur la
piste de ControlGris


https://www.dropbox.com/s/czmmu03jhkngvb2/SpatContr2.mov?dl=0


Je trouve ça cohérent avec ce qu'Olivier a rapporté :

*Un truc étrange est que si je suis en Latch sur une piste avec un
ControlGris et que je met un plugin perso sur une autre piste (en Latch
aussi), lorsque je bouge un paramètre de cet autre plugin, l'automation du
ControlGris s'écrit (seulement lorsque ça bouge), mais pas celle du plugin
perso...!*


*ControlGris*


je confirme l’écriture si on touche l’interface du plugin avec la souris

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno gio 22 ago 2019 alle ore 10:35 Olivier Bélanger <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V100b3
Les trajectoires automatisées s'enregistrent dans DP10

**Comment by NicolaGiannini** [comment]
V100b3
Dans Ableton Live 9.7.7 les trajectoires sont enregistrées seulement en
mode Drawing, mais pas en Realtime.
Vidèo :
https://www.dropbox.com/s/2naqop8ngndduzw/recording%20ableton.mov?dl=0

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno sab 24 ago 2019 alle ore 11:16 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
> Dans Ableton Live 9.7.7 les trajectoires sont enregistrées seulement en mode Drawing, mais pas en Realtime.

1) Activate doit être allumé pour enregistrer, même en mode realtime.
2) C'est la trajectoire qu'il faut bouger, pas une source (c'est la trajectoire qui est enregistrée)!

**Comment by Normandeau** [comment]
V100b4
Réussi une fois à enregistrer de l'automation (X, Y et Z) dans une piste stéréo (en bas). Pas en octo (en haut)! On voit cependant que Logic «perçoit» l'automation, car il enregistre une valeur fixe dans la piste octo.

![Capture d’écran, le 2019-09-02 à 11 20 11](https://user-images.githubusercontent.com/8959779/64123960-c0bc2680-cd73-11e9-81f4-6aa346c3286e.jpg)

**Comment by NicolaGiannini** [comment]
V100b4
Si j'ai bien compris ton test Robert, il me semble que je peux enregistrer
à la fois la piste stéréo et la piste octophonique. La différence que j'ai,
c'est toujours la même. En mode realtime, je peux enregistrer correctement,
en mode drawing je peux enregistrer seulement si je touche l'interface.
realtime:
https://www.dropbox.com/s/amq3hq6ehbk5clb/recording-realtime.mov?dl=0
drawing:
https://www.dropbox.com/s/k3anbqyhxlu1izg/recording-drawing.mov?dl=0
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 2 set 2019 alle ore 11:22 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
Je viens de faire l'update de Logic à 10.4.7 et  ce problème semble réglé! Je vous laisse confirmer et fermer cet issue! Je fais un release de la version 1.0.3 cet après-midi...

**Comment by Normandeau** [comment]
V103
Réglé
