### ISSUE TITLE
Presets sauvegardés incorrectement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#28]
Voici l'était d'un preset au moment de sa sauvegarde. Les positions de la source 1 sont au bon endroit, mais pas celles de la source 2:

![Preset Save](https://user-images.githubusercontent.com/8959779/63107403-e4e5ce00-bf52-11e9-9b67-36202a56e8ed.jpg)

Et au moment de son rappel:

![Preset Recall](https://user-images.githubusercontent.com/8959779/63107430-ee6f3600-bf52-11e9-8e42-4c172e009b4b.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme le même comportement en modalité LBAP, mais si je fais du
browsing entre le presets et je reviens sur celui, il affiche la position
correcte.

Voir la vidéo.
https://www.dropbox.com/s/ez3r59m6m59h8qw/presets.mov?dl=0

En modalité VBAP c’est correct.

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno gio 15 ago 2019 alle ore 12:06 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Merci pour la vidéo. Malheureusement tu sauves ton preset avec ses défauts: les deux canaux sont asymétriques. Donc lorsque tu le rappelles, il est correct. Il faudrait faire un preset vierge, symétrique. Et voir comment il est rappelé. Comme dans l'expérience décrite ci-haut.

**Comment by NicolaGiannini** [comment]
En essayant de créer un preset symétrique, j'ai réalisé que dans mon cas,
la deuxième source est déplacée incorrectement lorsqu'elle est sauvegardée.
Les deux : save et save as.
Cela se produit aussi avec les trajectories type : delta lock, et circular
fixed angle

Voir la vidéo
https://www.dropbox.com/s/tq6wy5lf9e9xjo2/preset.mov?dl=0

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno ven 16 ago 2019 alle ore 07:21 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V100b4
Preset sauvegardé:

![LBAP Preset Save 100b4](https://user-images.githubusercontent.com/8959779/64116732-1cc97f80-cd61-11e9-914b-d462db0d13dd.jpg)

Preset rappelé:

![LBAP Preset Open 100b4](https://user-images.githubusercontent.com/8959779/64116747-25ba5100-cd61-11e9-8442-ed41190acd6b.jpg)

Ce qui n'est pas sauvegardé:
- Trajectory Type
- Dur per Cycle
- Source Placement
Le reste semble être sauvegardé correctement

**Comment by NicolaGiannini** [comment]
Je confirme, en plus de que je comprends , ce qui n'est pas sauvegardé est
aussi le Source Link en élévation. Il est bien affiché dans l’onglet, mais
les sources retournent toutes à zero quand je rappel le preset.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 2 set 2019 alle ore 09:12 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Xon77** [comment]
En récapitulant, pour moi, ce qui n’est pas sauvegardé dans les presets dans Reaper :
- Trajectory Type
- Dur per Cycle
- la flèche entre le link Azimuth Span & Elevation
- les positions des sources autres que la source 1, dans un mode autre qu’indépendant ou Delta Lock (dans le cas ou l’on ait bougé la source 1 avec un source link circulaire).

Concernant, source placement, pour moi, il ne devrait pas être rappelé, puisque que le preset rappelle déjà la position (modifiée à la main) de toutes les sources en indépendant ou de la source 1 en groupé.

**Comment by Normandeau** [comment]
V101
Pas mal tout est maintenant sauvegardé dans les nouveaux Presets. Ce qui ne l'est pas, c'est le preset qui était en usage au moment de la sauvegarde de la session. Il faudrait corriger cela. Tous les autres plugins sauvent les valeurs avec la session.
Voici ce qui était ouvert:

![Capture d’écran, le 2019-10-09 à 13 52 59](https://user-images.githubusercontent.com/8959779/66507290-ef2cd000-ea9c-11e9-8a0b-cba05e720ba5.jpg)

Voici comment ça s'ouvre après avoir fermé et ouvert la session Il faudrait valider cela, mais il semble que ce soit toujours le dernier preset qui s'ouvre par défaut, ici le 16):

![Capture d’écran, le 2019-10-09 à 13 55 29](https://user-images.githubusercontent.com/8959779/66507317-feac1900-ea9c-11e9-999e-2b26f1bb553b.jpg)

**Comment by Xon77** [comment]
Je confirme qu'à la réouverture, les positions des sources du cadran XY se retrouvent toutes dans le coin inférieur gauche. L'élévation du preset en usage au moment de la sauvegarde de la session semble être bien rappelé, mais le preset sélectionné affiche toujours par erreur le dernier preset enregistré dans la liste.

**Comment by Normandeau** [comment]
V102
Preset sauvegardé:

![Preset sauvegardé 102](https://user-images.githubusercontent.com/8959779/67327918-b18d6580-f4e6-11e9-92c9-72dadbbb8504.jpg)

Preset rouvert:

![Preset rouvert 102](https://user-images.githubusercontent.com/8959779/67327958-be11be00-f4e6-11e9-9450-594321718dfb.jpg)

— Source Link n'est plus sauvegardé.
— Nombre de sources remis à 2 systématiquement voir #55

**Comment by Normandeau** [comment]
V102
Le numéro du preset sauvegardé se rouvre correctement

**Comment by belangeo** [comment]
> — Source Link n'est plus sauvegardé.

Ce problème est en fait relié au nombre de sources qui n'est pas mis à jour correctement. Réglé en même temps que #55 .

**Comment by Normandeau** [comment]
V103
Source Link n'est toujours pas sauvegardé dans les Presets.
55 n'est pas réglé complètement non plus. Plus d'infos sur 55.

**Comment by NicolaGiannini** [comment]
Je confirme que le Source Link n'est toujours pas sauvegardé dans les
Presets.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 4 nov 2019 alle ore 11:48 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
De quels presets on parle exactement? Ceux du plugin (gérés par le DAW) ou ceux des positions (1 à 50, géré par le plugin) ? Ici, sous Reaper, les Source Link sont bel et bien sauvegardés si je rappelle un preset géré par le DAW. Les presets de positions n'ont aucun effet sur les Source Link puisque ces derniers sont des paramètres automatisés par le DAW.

**Comment by NicolaGiannini** [comment]
Je parlais, et je crois aussi Robert, des presets géré par le plugin (1 à
50). Mais si on veut que le source link soit géré par les automations et
les presets du DAW, c'est correct comment-ça, j'immagine.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mer 6 nov 2019 alle ore 11:22 Olivier Bélanger <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
Yep, d'ailleurs, il est possible de vouloir appeler plusieurs fois un preset de position avec un source link différent à chaque fois (possible parce que ce dernier est contrôlé par le DAW).

**Comment by Normandeau** [comment]
V104
Réglé
