### ISSUE TITLE
Décalage de position à Stop après enregistrement d'une trajectoire

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#29]
Les sources d'un fichier octophonique sont déplacées d'environ 60˚ vers la gauche après qu'une trajectoire se soit arrêtée, au moment précis où on stoppe le séquenceur. Testé avec DP pour le moment. À confirmer avec les autres séquenceurs.

Voir le film:

https://www.dropbox.com/s/f8h257legciaxgw/D%C3%A9calage%20de%20position%20%C3%A0%20Stop.mov?dl=0

**Comment by NicolaGiannini** [comment]
J'ai testé avec Logic 10.4.6 et Ableton Live 9 et cela ne se produit pas,
voir la vidéo :

https://www.dropbox.com/s/jp6rcmtjd7mpy30/stop%20logic.mov?dl=0

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno gio 15 ago 2019 alle ore 12:30 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Nicola, il semble que c'est parce que tu ne fais pas la même expérience. Ta trajectoire dure 8s (4 X 2), mais on dirais que tu l'arrêtes en chemin. En tout état de cause, si on regarde attentivement ta vidéo, on voit que ta source 1 est toujours à un endroit différent après chacun des multiples arrêts que tu fais. Alors qu'elle devrait être à la position de départ.
Ce n'est pas cela que je décrivais. Il faut aller au bout de la trajectoire. Et seulement ensuite, après que la trajectoire se soit arrêtée d'elle-même, arrêter le séquenceur. 
Dans Logic, quelque soit la relation choisie entres les sources, par exemple Left Alternate, aussitôt qu'on part la trajectoire, c'est toujours Top Clockwise qui est choisie.
Et je ne crois pas que l'on puisse valider cela avec Live, car il ne lit pas les fichiers octophoniques.

**Comment by NicolaGiannini** [comment]
Voici une vidéo sans interruption (en fait en Ableton j'avais essayé avec 2
sources).
https://www.dropbox.com/s/dn025spasnk1wcs/stop%20logic2.mov?dl=0

Petite note: Je n'ai pas encore trouvé comment commencer la trajectoire
quand je veux, mais c'est peut-être lié à ce que David a indiqué?

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno sab 17 ago 2019 alle ore 18:12 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
La même situation prévaut lorsqu'on se place en mode Realtime. Lorsqu'on démarre le séquenceur DP, les sources se décalent vers la gauche dès le départ. De plus le X gris disparaît au même instant. On peut cependant le réactiver si on clique dans le fenêtre à l'endroit on sait qu'il se trouve:
https://www.dropbox.com/s/q1nilnr0og3iegf/Manual%20Automation%20DP%20Octo%20100b3.mov?dl=0

**Comment by Normandeau** [comment]
V101
Réglé
