### ISSUE TITLE
Décalage au passage de 180˚

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#3]
Olivier (rapporté de ServerGRIS #104):
C'est réglé. Le problème est que le SpatGRIS envoit ses coordonnées dans un vieux format (je suppose que c'est pour être compatible avec le Zirkonium). Ces coordonnées (-1 à 1 en azimuth et 0 à 0.5 en zénith sur une adresse OSC "/pan/az") ne correspondent pas avec la nouvelle nomenclature, celle qui figure dans le manuel. La conversion dans le ServerGris était erronée.

Il faudrait pouvoir spécifier directement dans le SpatGRIS où on veut envoyer les coordonnées et utiliser automatiquement le bon format. Pour l'instant, j'ai patché le ServerGris pour que ça fonctionne. On réécrira au propre quand on va re-travailler le ControlGRIS.

**Comment by belangeo** [comment]
Dans la section Settings, le menu "OSC format" servira à spécifier la cible où envoyer les coordonnées OSC. Le format sera adapté en conséquence.
