### ISSUE TITLE
Source Link problématique en octo

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#31]
V 1.000
Vérifié dans DP et dans Reaper.
Le comportement des sources en mode octo est très problématique. Surtout en LBAP. En VBAP:
• Circular ne fonctionne pas non plus: seule la source 1 est active; 
• Circular Fixed Radius: les sources ont bien le même radius, mais la source 1 est libre sur le plan angulaire;
• Circular Fixed Angle: les sources ont bien le même angle , mais la source 1 est libre sur le plan radial;
• Circular Fully Fixed et Delta Lock fonctionne comme prévu.

Voir la vidéo pour le VBAP:
https://www.dropbox.com/s/lfe2lrm7rz8zx9h/Source%20Link%20Octo%20VBAP.mov?dl=0

La vidéo est encore plus explicite en LBAP.
Remarquez particulièrement Delta Lock, qui fait toujours référence à un cercle ici:
https://www.dropbox.com/s/hhgikebn2gv2mk0/Source%20Link%20Octo%20LBAP.mov?dl=0

**Comment by NicolaGiannini** [comment]
V 1.000
Vérifié dans Logic 10.4.6

VPAB

Je confirme le même comportements indiqués par Robert.
Même chose avec une source stéréo, voir la vidéo
https://www.dropbox.com/s/8eowbn301givodc/sourcesVBAP.mov?dl=0
Même chose dans Ableton 9 (testé en stéréo)

Dans la modalité LBAP le comportement de ControlGris en Logic est un peu
different mais le résultat dans ServerGris, de que je comprends, est
similaire.
Voir la vidéo :

https://www.dropbox.com/s/vg3sp7jqwc3zay9/sourcesLBAP.mov?dl=0

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno ven 16 ago 2019 alle ore 08:59 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
> La vidéo est encore plus explicite en LBAP.
Remarquez particulièrement Delta Lock, qui fait toujours référence à un cercle ici

Je crois que ce cas particulier est relié à l'issue #33 car je ne peux reproduire ce comportement après avoir corrigée cette dernière...

Pour ce qui est de Circular, Circular Fixed Radius et Circular Fixed Angle, quel est le comportement souhaité? Présentement, ça fait ce qui me semblait le plus logique, c'est-à-dire que Fixed Radius gèle le radius des sources sur celui de la source 1 mais ne fait fait rien quant à l'angle. Inverse pour Fixed Angle... Circular n'impose aucun gel...

**Comment by NicolaGiannini** [comment]
Le comportements souhaités en Circular, Circular Fixed Radius et Circular
Fixed Angle sont (je crois) les comportements que on avait avec SpatGris,
voir la vidéo :
https://www.dropbox.com/s/h28hll8fs6khp3c/comportement.mov?dl=0

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mer 21 ago 2019 alle ore 14:34 Olivier Bélanger <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
Got it!

**Comment by Normandeau** [comment]
Merci Nicola. C'est encore plus explicite quand on compare les comportements de SpatGRIS vs ControlGRIS en repassant toujours par le mode Independent afin de remettre les sources en disposition aléatoire. C'est là qu'on voit comment chacun des modes repositionne les sources. Dans SpatGRIS, les modes groupés font en sorte que toutes les sources sont toujours solidaires quelle que soit la source sélectionnée: 1) en position aléatoire avec Circular; 2) en Rayon égal avec Fixed Radius; 3) en angle égal avec Fixed Angle. 
Dans ControlGRIS, on a plutôt: 1) aucun groupement avec Circular; 2) rayon égal avec Fixed Radius, mais pas de mouvement circulaire: seul le rayon peut-être modifié, et la source 1 est indépendante des autres sur le plan angulaire; 3) angle égal avec Fixed Angle, mouvement circulaire à partir de la source 1, mais pas à partir des autres (est-ce que cela correspond à notre idée qu'il n'y a plus de source maître?) et toutes les sources sont indépendantes sur le plan du rayon; 3) mode circulaire en Fully Fixed à partir de la source 1 seulement, aucune activité à partir des autres sources:

https://www.dropbox.com/s/ezjig22s19unvy3/Source%20Link%20SpatGRIS%20vs%20ControlGRIS.mov?dl=0

**Comment by Normandeau** [comment]
V100b3
Résolu
