### ISSUE TITLE
Sauf en mono, toutes les trajectoires sont des cercles

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#32]
V 1.000
Vérifié dans Reaper
Ellipse et Spiral ne font que des cercles avec une source stéréo ou octo. Seul un fichier mono adopte la forme préconisée.

**Comment by NicolaGiannini** [comment]
Je confirme la même chose en Logic.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno ven 16 ago 2019 alle ore 09:20 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Xon77** [comment]
V 1.0.0-b4
En effet, une ellipse (ou une spirale) font des cercles (de vitesses plus ou moins variables) s'il y a plus de 2 sources et que l'on ait dans un mode groupé.
Je peux créer une ellipse ou une spirale seulement pour la source 1, lorsqu'on a plusieurs sources et qu'on est en mode indépendant. Dès que l'on passe en mode groupé, la trajectoire est altérée.

**Comment by Normandeau** [comment]
V101
Réglé
