### ISSUE TITLE
Delta Lock ne fonctionne plus en LBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#34]
V100b3
Lorsqu'on bouge les sources dans un coin avec Delta Lock, elles ressortent du coin groupées ensemble. Il n'y a plus le fameux effet Delta Lock, où elles ressortissaient du coin, comme un ressort, en reprenant leurs positions respectives.

**Comment by belangeo** [comment]
Sur Reaper, je n'ai pas ce problème... Je vais voir avec DP10.

**Comment by Normandeau** [comment]
De plus, les sources se «souviennent» qu'elles ont été regroupées si on reste en Delta Lock, même après les avoir repositionnées avec Left Atltenate par exemple. Illustré ici en octo, mais c'est pareil en stéréo.

https://www.dropbox.com/s/prt8y35lcltei9c/Delta%20Lock%20100b3.mov?dl=0

**Comment by belangeo** [comment]
Bon, j'ai réussi à le reproduire une fois, ça a quelque chose à voir avec une inittialisation incomplète lorsque l'on appuie sur play. À suivre...

**Comment by Normandeau** [comment]
Delta Lock fonctionne bien en VBAP. J'ai modifié le titre de l'issue pour être plus clair.

**Comment by NicolaGiannini** [comment]
Je confirme le même comportement que dans la vidéo de Robert. Mais quelque
chose d'étrange m'arrive. Si j'ouvre un projet Logic (10.4.6) où il y a un
canal avec une instance ControlGris, le plugin s'ouvre avec le champ "OSC
format" vide. Dans ce cas, le comportement Delta Lock est différent.
Voir la vidéo
https://www.dropbox.com/s/mgc0gpu7hgwmjnq/deltalock.mov?dl=0

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno sab 24 ago 2019 alle ore 09:59 Olivier Bélanger <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
> Si j'ouvre un projet Logic (10.4.6) où il y a un canal avec une instance ControlGris, le plugin s'ouvre avec le champ "OSC format" vide. 

Cette instance a été créée avec la version beta 2 ! Les index de ce menu ont changés, à l'interne, entre les deux versions.

**Comment by Normandeau** [comment]
V100b4
Réglé
