### ISSUE TITLE
Source Link problématique en mode VBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#36]
V100b3
Les Source Link problématiques ont été réglés en mode LBAP #31  mais une partie du problème persiste en mode VBAP. Les sources sont bien groupées entre elles, mais la source 1 est toujours libre sur le plan du rayon, même en Fixed Radius:
https://www.dropbox.com/s/fx8nx2bzlzxv9ho/Source%20Link%20VBAP%20100b3.mov?dl=0

**Comment by NicolaGiannini** [comment]
Je confirme la même chose dans Logic.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno sab 24 ago 2019 alle ore 10:09 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V100b4
Réglé
