### ISSUE TITLE
Incohérence de la valeur unitaire entre SpatGRIS et ServerGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#4]
La valeur unitaire de SpatGRIS pour le Rayon est de 2:
![31525928-b318c44a-af91-11e7-88e9-46467ce95b3e](https://user-images.githubusercontent.com/8959779/47955192-6216f800-df6a-11e8-839a-0e0cbfeb2a13.jpg)

Alors que dans le Server cette valeur se nomme Radius et elle est de 1:
![31525947-d7b2c1a2-af91-11e7-9c00-6a76521ca7b1](https://user-images.githubusercontent.com/8959779/47955196-680cd900-df6a-11e8-8dc7-778c19ed2879.jpg)

Cette valeur de 2 du SpatGRIS est héritée du mode PanSpan où le cercle des hp est situé à 1 et le Far à 2. C'est lorsqu'on utilise la fonction OSC que cela devient incohérent.

Donc  à corriger:
la valeur unitaire devrait être de 1 dans les deux cas

**Comment by belangeo** [comment]
D'accord.
