### ISSUE TITLE
VST3 failed in DP10

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#41]
100b4, après suppression des caches
DP10
La version VST3 ne passe pas le test de DP10, mais comme on peut le voir, ce n'est pas la seule. Je ne sais pas si c'est important.
Par contre, les versions AU et VST2 passent bien.

![Capture d’écran, le 2019-08-31 à 07 51 57](https://user-images.githubusercontent.com/8959779/64063607-544ef500-cbc4-11e9-8846-9cf534708e40.jpg)

Logic X
Ok pour les AU

Reaper 5
Test rapide, toutes les versions fonctionnent: AU, VST et VST3
La version VST3 s'affiche comme mono, mais fonctionne normalement:

![Capture d’écran, le 2019-08-31 à 08 16 34](https://user-images.githubusercontent.com/8959779/64063915-1c967c00-cbc9-11e9-95e5-7d5ce96db095.jpg)

Ableton Live 10.1
La nouvelle version de Live, 10.1 supporte les VST3
Test rapide, ça fonctionne. Ainsi que les versions AU et VST2.

**Comment by Xon77** [comment]
La version AU a depuis longtemps de nombreux bogues avec Reaper.
J'utilise constamment la version VST sous Reaper pour ne pas avoir de problème.

**Comment by NicolaGiannini** [comment]
La version AU fonctionne correctement dans Logic.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mer 13 nov 2019 alle ore 14:06 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Ok c'est dans le manuel
