### ISSUE TITLE
Delta Lock passe en Linear Min en LBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#43]
V100b4
La situation: LBAP, Enregistrement de trajectoires, fichier octo, Circular Fully Fixed, Circle Clockwise avec une particularité: je place toutes les élévations de manière indépendante et en Realtime:

![Capture d’écran, le 2019-09-01 à 10 22 14](https://user-images.githubusercontent.com/8959779/64077859-63a47000-cca2-11e9-9a05-8c73650e81eb.jpg)

Question: comment assujettir les élévations asymétriques comme un groupe? En utilisant Delta Lock. Malheureusement, dès que je démarre le séquenceur (et pas avant), Delta Lock passe en Linear Min:

![Capture d’écran, le 2019-09-01 à 10 24 26](https://user-images.githubusercontent.com/8959779/64077896-c564da00-cca2-11e9-865e-de9f62d016f6.jpg)

**Comment by NicolaGiannini** [comment]
De que je comprends, dans Reaper dès que je démarre le séquenceur ça reste
en Delta Lock, mais ça change la position des sources en élévation.

Avant
[image: avant.jpeg]

après
[image: après.jpeg]

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno dom 1 set 2019 alle ore 10:27 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
> De que je comprends, dans Reaper dès que je démarre le séquenceur ça reste
en Delta Lock, mais ça change la position des sources en élévation.

Ce comportement est causé par la variation de la position de la trajectoire au moment de démarrer la séquence et la position où elle se trouvait au moment de choisir "Delta Lock" (c'est ce moment qui gèle les positions). Le problème de Robert doit être sensiblement le même (quand Delta Lock a été sélectionné, les sources étaient probablement dans une position Linear Min).

Je n'ai pas encore trouvé une façon d'automatiser la gestion des "Fixed Sources" qui fonctionne dans tous les cas de figure... Je me suis d'ailleurs demandé si je ne devrait pas enlever la génération automatique des "Fixed Sources" et obliger l'utilisateur à appuyer sur le bouton "Fix Sources" quand il veut geler les positions à un temps donné... Je crois que c'est un sujet qu'il faudra éventuellement débattre de vive voix!

**Comment by Xon77** [comment]
Si je comprends bien, si on voulait automatiser la gestion des « Fixed Sources », il faudrait que la manipulation des positions relatives des sources soit toujours mis à jours dans fixed sources et non pas seulement lors du choix du type de lien, puisque l’on peut modifier la position des sources après…. (Ce qui créerait beaucoup d’éditions de points fixes)

Ou plutôt que la fixation des positions des sources n’ait lieu qu’au moment de lancer et d’arrêter la lecture du séquenceur.

Je cherche naïvement une façon d’automatiser ce processus…

**Comment by belangeo** [comment]
En ce moment, un Fixed Sources s'écrit au départ de la séquence si Activate est allumé et lorsque l'on change de Source Link (il me semble).... Clairement, il y a des cas de figure qui ne fonctionnent pas avec ces choix!

**Comment by Xon77** [comment]
Un Fixed Sources s'écrit bien lorsque l'on change de source link.
Mais que veux tu dire par au départ de la séquence si Activate est allumé ?
car moi je ne vois pas cela dans Reaper...

**Comment by belangeo** [comment]
Ha non, en effet, cette partie du code est commenté par qu'il n'y a que Reaper qui garde une valeur de temps cohérente lorsque la séquence ne joue pas... Dans le cas de DP, par exemple, au moment où on appuie sur play, la valeur de temps est toujours celle du moment où la séquence a été arrêtée (et non là où se trouve le curseur). Je l'ai donc retiré puisque ça écrivait des Fixed Sources au mauvais endroit.

Je ne sais pas si ça va être possible de tout automatiser avec un taux d'erreur nul... Peut-être que la solution est vraiment de forcer l'utilisateur à écrire les Fixed Sources quand il en veut un... À suivre...

**Comment by Xon77** [comment]
Donc, s'il n'y avait que Reaper, il serait possible d'envisager une automatisation de ce processus.
Mais en considérant les autres séquenceurs, cela risque en effet d'être fortement improbable.

**Comment by Normandeau** [comment]
V101
Ce problème est réglé. Les autres points pourraient faire l'objet d'autres issues. Mais Fixed Sources étant maintenant disparu, et qu'on a choisi une autre stratégie, je ne vois pas l'intérêt.
