### ISSUE TITLE
Fixed Angle et Fully Fixed ne fonctionnent plus

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#44]
V100b4
Fixed Angle et Fully Fixed ne fonctionnent plus. Vérifié en stéréo et en octo. Les comportements diffèrent selon qu'on est en LBAP ou en VBAP. Voici quelques exemples:

Fully Fixed LBAP:
![Fully Fixed LBAP](https://user-images.githubusercontent.com/8959779/64123100-628e4400-cd71-11e9-867f-3b36e25232a5.jpg)

Independent VBAP:
![Independant VBAP](https://user-images.githubusercontent.com/8959779/64123128-73d75080-cd71-11e9-8b65-6182ec3f5f95.jpg)

À partir de là, Fixed Angle VBAP:
![Fixed Angle VBAP](https://user-images.githubusercontent.com/8959779/64123153-85205d00-cd71-11e9-9fac-91e4f9a0ead1.jpg)

Et ensuite, Fully Fixed VBAP. Fully Fixed n'ajuste que le rayon:
![Fully Fixed VBAP](https://user-images.githubusercontent.com/8959779/64123160-923d4c00-cd71-11e9-8d37-f8cca1e3485d.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme le comportement
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 2 set 2019 alle ore 11:07 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
C'est réglé!

**Comment by Normandeau** [comment]
V101
Réglé
