### ISSUE TITLE
Le popup menu "Source Placement" devrait permettre la resélection

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#45]
Comme le titre l'indique, le popup menu "Source Placement" dans l'onglet Source devrait permettre la resélection.

0. J'initalise 2 sources.
1. Je sélectionne un source Placement, par exemple "Right Alternate", 
2. Je modifie la position des sources dans l'éditeur.
3. Je re-sélectionne "Right Alternate" -> le placement des sources n'est pas effectif.

Il faut sélectionner un autre source placement, puis recalculer sur "Right Alternate", pour que cela soit effectif.

**Comment by belangeo** [comment]
Juce ne permet pas de sélectionner l'item déjà sélectionné dans un ComboBox. Par contre, après avoir choisi un item, je peux automatiquement effacer la sélection (ce qui a pour effet que le menu affiche toujours "Choose a source placement...") et là on peut la re-sélectionnée. Je viens d'essayer et cette solution fonctionne. Est-ce convenable?

**Comment by Normandeau** [comment]
Oui, je n'osais pas encore mettre cette issue sur la table, mais il est vrai que de devoir repasser chaque fois par une autre sélection pour en avoir une active est un peu boguant. Bon il est vrai qu'on est en mode de tests, mais quand même. J'essaierai cette solution.

**Comment by belangeo** [comment]
Ok, c'est fait!

**Comment by Normandeau** [comment]
V101
Partiellement réglé seulement. Voir Issue #50

**Comment by Normandeau** [comment]
V102
Réglé
