### ISSUE TITLE
Placement des sources à l'ouverture du plugin mode LBAP

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#46]
V100b4 - 
Lorsque on ajoute une source en LBAP, elle est toujours placée loin (en bas à droite du cadran).
Si je touche la source en mode VBAP et je passe en mode LBAP la source est dans la position correcte. 
Voir la vidéo 

https://www.dropbox.com/s/cb9l2o39omevqbq/ouverture.mov?dl=0

**Comment by Normandeau** [comment]
V101
Réglé
