### ISSUE TITLE
Initialisation et répartition des sources automatiques

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#47]
Afin d'accélérer l'ergonomie du Plugin, actuellement, lorsqu'on initialise des sources, elles se retrouvent toutes les unes sur les autres en haut.
Il pourrait être utile (enhancement) qu'une répartition par défaut automatique comme Left Alternate ou Top Clockwise soit mis en place, dès qu'on modifie le nombre de sources.

**Comment by NicolaGiannini** [comment]
Je suis d'accord.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno ven 6 set 2019 alle ore 15:33 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
Done.

**Comment by Normandeau** [comment]
V101
Réglé
