### ISSUE TITLE
Écriture de l'automation des presets

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#49]
V1.01
54 hp LBAP
• Dans DP 1001, si j'ai 4 presets en mémoire par exemple, seule l'automation deux premiers presets écrits est lue, quels qu'ils soient. Si l'automation est écrite: 1-2-3-4-3-2-1, seulement 1 et 2 sont lus. Toutes les autres valeurs sont ignorées. Si j'ai 2-4-3-1-4-3-2-1, seules 2 et 4 sont lues (j'ai essayé jusque avec 16 presets):

![Capture d’écran, le 2019-10-08 à 14 21 17](https://user-images.githubusercontent.com/8959779/66422022-ebcf1100-e9d6-11e9-885b-897c6c2e5a90.jpg)

• Dans Reaper 598, ça fonctionne relativement bien, une fois.
Car je ne suis plus capable d'ouvrir la séquence après l'avoir sauvée et fermée. Ça bloque Reaper à tous les coups. Je pense que cela a à voir avec le fait que Reaper commande automatiquement 128 inputs à ServerGRIS. Avec les 54 hp du Cube, ça fait disjoncter Jack qui bloque Reaper (voir l'issue no 157 dans ServerGRIS). Jack affiche 125% d'activité au moment où Reaper essaie d'ouvrir la session. J'ai fait deux sessions différentes à partir de 0 et c'est le même résultat chaque fois. Seule solution: Force Quit.

• Dans Logic 1047 (nouvelle version aujourd'hui), ça fonctionne très bien, malgré le fait que Logic commande aussi 128 inputs à ServerGRIS.

**Comment by Normandeau** [comment]
Dans Reaper, les presets sont vraiment mélangés. Non seulement on peut en choisir plusieurs à la fois, mais quand on veut en sélectionner un, ça ne marche pas toujours. Parfois c'est le suivant qui est sélectionné, parfois aucun, parfois plusieurs:

![Capture d’écran, le 2019-10-09 à 12 59 31](https://user-images.githubusercontent.com/8959779/66503189-c274ba80-ea94-11e9-9c00-90205eeb7379.jpg)

**Comment by Xon77** [comment]
Dans Reaper, je n'arrive pas à reproduire le ménagement des presets, même en rouvrant la session (hormis l'issue 157 du ServerGris). Je n'ai pas encore constaté un problème spécifique avec l'automation des presets dans Reaper dans mes premiers tests avec 2 sources.

**Comment by Xon77** [comment]
Dans Reaper, je n'ai pas pu reproduire cela les premières fois en sauvegardant et rouvrant la session, mais en jouant avec l'automation des presets et plusieurs réouvertures de sessions, je suis incapable de rouvrir le projet à un certain moment.
Comme @Normandeau , Seule solution: Force Quit.

**Comment by Xon77** [comment]
Parmi les bogues divers sur l'automation des presets dans Reaper, hormis le fait que le projet ne peut plus être réouvert, certains N° de Presets ne peuvent jamais être enregistrés. En l'occurence, dans mon cas, je ne peux curieusement enregistrer les Presets N° 6, 11, 16, 21, 24, 28, 31, 41, 44, 47, 50.

**Comment by Xon77** [comment]
@Normandeau , dans Reaper, je ne sais pas comment tu as fait pour sélectionner plusieurs presets et les mettre en jaune ? Je n'ai pas encore réussi à reproduire ce comportement particulier.

**Comment by Normandeau** [comment]
V101
Après une séance d'essai à VTech avec ControlGRIS, j'ai dû me résigner à l'enlever de tous mes projets. Trop instable, surtout au plan des paramètres sauvegardés et de ceux qui sont effectivement chargés au moment de l'ouverture de la session et lorsque le plugiciel est en arrière-plan. C'est très difficile à documenter cependant, car c'est très différent d'une fois à l'autre. De plus chaque fois que j'ouvre une session, ControlGRIS place toutes sources dans le coin inférieur gauche:

![Preset sauvegardé rouvert](https://user-images.githubusercontent.com/8959779/66880655-d424f900-ef91-11e9-824f-5cf4346bde36.jpg)

**Comment by Normandeau** [comment]
V102
Multiples sélections: réglé

**Comment by Normandeau** [comment]
V102
Même problème avec l'écriture de l'automation dans DP.
Reaper et Logic: ça semble bien fonctionner.

**Comment by NicolaGiannini** [comment]
V102
Ableton 9.7
Dans Ableton le reproduction des automations des presets désactive les
automation de la piste. Cela ne se produit pas avec la reproduction des
automations des trajectoires.
Afin de rendre possible la reproduction des automations des presets, il
faut fermer la fenêtre du plugin.

Vidèo : https://www.dropbox.com/s/yn91oge3iyb7s5d/presets-live.mov?dl=0
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 22 ott 2019 alle ore 16:58 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V103
Problème réglé dans DP 10.01
Problème réglé dans Ableton Live 10.1
Problème apparemment réglé aussi dans Ableton Live 9.77 mais je laisse Nicola le confirmer avant de fermer cette issue.

**Comment by NicolaGiannini** [comment]
Je confirme que le problème est réglé dans Ableton Live 9.7.7.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 4 nov 2019 alle ore 11:22 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Réglé
