### ISSUE TITLE
SpatGRIS est limité à 96 canaux en mode OSC Spatialisation 

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#5]
Je teste les limites du SpatServerGRIS et lorsque j'essaie de dépasser 96 canaux d'envoi OSC à partir du plugiciel SpatGRIS dans DP, ce qui signifie 12 pistes octophoniques (canaux 1 à 96), le 97e canal ne veut tout simplement pas être validé dans le plugiciel SpatGRIS.
Confirmé dans Reaper
(On peut pas traiter plus qu'une piste octophonique dans Logic, donc on ne peut pas tester cela).
Pourquoi cette limitation?
C'est un oubli certainement.
En tout cas il faut monter cela disons à 128 au moins pour le moment.

**Comment by belangeo** [comment]
Il n'y a pas de limite dans le ControlGris.
