### ISSUE TITLE
Presets et Source Placement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#50]
V101
En octo, peu importe le preset, si je passe de Settings à Source dans Configuration, ControlGris remet automatiquement les sources en mode Left Alternate, sans qu'aucun choix n'ait été fait dans Source placement. Validé dans DP, Reaper et Logic.

**Comment by Normandeau** [comment]
C'est probablement suite à la demande d'avoir les sources ajoutées à un endroit cohérent, à savoir Left Alternate, que cela s'est produit. Voir #47 (Solved). Je comprends l'idée, mais c'est un peu intrusif, non?

**Comment by Xon77** [comment]
Que veux tu dire par c'est un peu intrusif ? @Normandeau 
Le placement automatique ne devrait pas avoir lieu quand on change simplement le menu dans Configuration de Settings vers Source, comme c'est le cas actuellement.
Mais je trouvais que le placement automatique était utile, seulement quand on change le nombre de sources...

**Comment by belangeo** [comment]
En effet, ce placement automatique est supposé d'être appliqué seulement au changement du nombre de sources. Quand la fenêtre prend le focus, ça c'est un bogue!

**Comment by Normandeau** [comment]
V102
Réglé
