### ISSUE TITLE
Bogue graphique avec les Presets

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#51]
V101
Si je joue avec l'ouverture de la fenêtre de ControlGRIS, les Presets ne reprennent pas leur place. Validé dans tous les séquenceurs, AU et VST:

![Capture d’écran, le 2019-10-08 à 15 14 31](https://user-images.githubusercontent.com/8959779/66425786-79622f00-e9de-11e9-9925-8dd92c601730.jpg)

**Comment by Xon77** [comment]
En effet, la barre est fixe et ne s'adapte pas, quand on modifie la taille de la fenêtre.

**Comment by Normandeau** [comment]
V102
Réglé
