### ISSUE TITLE
Activate: On/Off pas dans Logic

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#52]
V101
Activate button automatically turned off after a recording pass.

• Logic
Les deux boutons Activate reste toujours en fonction, même après l'arrêt de l'enregistrement de l'automation

• DP: Ok

• Reaper: Ok

**Comment by belangeo** [comment]
C'est réglé. Par contre, dans Logic, lorsqu'il n'y a plus de son sur les pistes, le callback audio arrête automatiquement mais aucun message n'est envoyé au plugin pour lui signifier l'arrêt. Dans ce cas particulier, le bouton ne se met pas à off tout seul...

**Comment by Normandeau** [comment]
V102
Réglé. Mettre une note dans le manuel pour Logic.

**Comment by Normandeau** [comment]
Mis dans le manuel.
