### ISSUE TITLE
Le n° de port de réception OSC se remet toujours par défaut à 8000 lors de la réouverture de la fenêtre du plugin

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#53]
Comme je suis en train de mettre en place un petit contrôleur avec le Lemur, j'ai pu remarquer qu'à chaque réouverture de la fenêtre du plugin, le n° de port de réception OSC se remet toujours par défaut à 8000, ainsi que la case pour activer la réception OSC (testé sur Reaper).

Il serait nécessaire que le N° du port OSC et la case l'activant soit conservé lors de la réouverture de la fenêtre du plugin (comme les autres infos principales), afin de pouvoir contrôler facilement plusieurs plugins en même temps.

**Comment by Xon77** [comment]
Le n° de port de réception OSC n'est toujours pas sauvegardé dans la 1.0.2, mais il ne s'agit pas d'un problème urgent.

**Comment by Xon77** [comment]
En réessayant, je m'aperçois que le n° de port de réception OSC est bien sauvegardé à la réouverture de la fenêtre du plugin, mais seulement quand la case pour activer la réception OSC est enclenchée.

**Comment by Xon77** [comment]
Je confirme que le n° de port de réception OSC est sauvegardé en toutes circonstances à la réouverture de la fenêtre du plugin.

**Comment by belangeo** [comment]
Excellent!
