### ISSUE TITLE
Lors de la fermeture et de la réouverture de la fenêtre du plugin, le nombre de sources affiché dans le champ "Nombre de sources" est toujours 2.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#55]
ControlGRIS 1.0.2
Lors de la fermeture et de la réouverture de la fenêtre du plugin, le nombre de sources affiché dans le champ "Nombre de sources" est toujours 2.

- J'ouvre une instance de ControlGris, et j'indique un nombre qui n'est pas 2 dans le champ "Number of Sources".

- Je ferme et rouvre la fenêtre du plugin. Le nombre affiché est 2 dans "Number of Sources".

- Les sources affichées dans le visualiseur graphique sont correctes. Si avec le pointeur de la souris je touche "first source id" puis "Number of sources", le nombre de sources affichées dans le visualiseur graphique devient deux.

Testé avec Reaper et Logic. Cela arrive même si je ferme et rouvre le projet.

**Comment by Normandeau** [comment]
Confirmé dans DP. De plus, si on sélectionne Source dans Configuration, on passe aussi à 2 sources. Si on rappelle un preset Octo, les sources sont seulement au nombre de 2 également.

**Comment by Xon77** [comment]
V.1.0.3, testé dans Reaper 5.98, le nombre de sources reste identique : 
- à la réouverture de la fenêtre du plugin,
- si on sélectionne Source dans Configuration,
- au rappel d'un preset.

**Comment by Normandeau** [comment]
V103
Le Number of Sources est bel et bien celui qui est sauvegardé. En octo par exemple, le nombre est bien de 8. Mais dans les espaces graphiques, il n'est toujours que de 2. Cela se passe si j'enlève ControlGRIS de la piste, puis que je le replace et que je rouvre un preset sauvegardé. De plus si j'essaie de replacer 8 sources en tapant à nouveau le chiffre 8 dans Number of Sources, il ne se passe rien. Il faut que je tape un autre chiffre, 4 par exemple, et ensuite 8 pour retrouver les 8 sources. Qui sont d'ailleurs disposés au bon endroit.
Validé dans DP et Logic:

![Capture d’écran, le 2019-11-04 à 11 50 42](https://user-images.githubusercontent.com/8959779/68140172-5baeb980-fef9-11e9-8bb2-ddf202adb532.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme, et validé avec Reaper aussi.

**Comment by Xon77** [comment]
En effet, les Position Preset (à la droite) n'initialisent et ne modifient pas le nombre de sources.
Ceci dit, quand on écrit pour une piste, on part avec un nombre de sources déterminé dès le départ. Le nombre de sources (des preset positions) n'est pas censé changer au cours de la piste.

Il en tout autrement des presets globaux du plugin, qui devraient pouvoir rappeler un nombre de sources différents et qui n'initialisent actuellement pas le nombre de sources au départ avant de rappeler les presets.

Concernant le fait que les pop up menus ne puissent sélectionner de nouveau l'élément sélectionné semble être un problème lié à Juce, il me semble? J'avais déjà soulevé le problème concernant un autre pop up menu.

**Comment by belangeo** [comment]
Le problème de rafraichissement du GUI est réglé.

> De plus si j'essaie de replacer 8 sources en tapant à nouveau le chiffre 8 dans Number of Sources, il ne se passe rien. Il faut que je tape un autre chiffre, 4 par exemple, et ensuite 8 pour retrouver les 8 sources.

Le fait qu'il ne se passe rien quand on entre le nombre déjà présent dans la boîte du nombre de sources prévient le rappel de LEFT ALTERNATE lorsque le panneau Source reçoit le focus. Ça ne devrait pas poser problème puisque si le plugin se comporte correctement, on ne devrait jamais avoir besoin de redemander le même nombre de sources!

**Comment by Normandeau** [comment]
V104
Réglé.
