### ISSUE TITLE
Dans Logic, en déplaçant les sources pendant que le séquenceur est en mode PLAY, elles retournent à la dernière position où le séquenceur était en mode STOP.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#56]
ControlGRIS 1.0.2
Logic 10.4.7

J'appuie sur PLAY sur le séquenceur.
Je déplace les sources.
J'appuie sur STOP.
Les sources retournent à la dernière position où le séquenceur était en mode STOP.
Cela se produit si je n'enregistre pas l'automation.
Cela ne se produit pas dans Reaper ou Ableton.

**Comment by belangeo** [comment]
Dans ce cas particulier, c'est sous Reaper et Live que le comportement n'était pas correct! Le but étant qu'après une trajectoire (cercle, spirale, dessin, etc.), les sources reprennent leur position initiale...
Maintenant, ce que j'en comprend, c'est qu'on ne veut ce comportement que si Activate est allumé. Dans une configuration de base, on s'attend à ce que les sources restent là où elles ont été placées, right?

**Comment by NicolaGiannini** [comment]
Bonjour,

Je suis désolé, mais je n'ai pas été précis.


Je me réfère pas à une trajectoire, mais au mode independent et real time


J'appuie sur PLAY sur le séquenceur.

Je déplace les sources.

J'appuie sur STOP.

Les sources retournent à la dernière position où le séquenceur était en
mode STOP.

Testé en Logic et Reaper (apparement aussi en Reaper), en Ableton cela ne
se produit pas.



Est qu’on veut qu’en mode independent et real time, si on change des
paramètres sans en enregistrer les automations pendant le playback, lorsque
lorsqu’on arrête le séquenceur, ces paramètres retournent à la position de
départ ? Si on déplace un panning ou un volume dedans un séquenceur pendant
le playback, quand on met en stop, le paramètre s’arrête à la dernier
valeur et il ne retourne pas à la position de départ.


video : https://www.dropbox.com/s/ysm2grlmrjk9v1m/panspat.mov?dl=0


Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mer 30 ott 2019 alle ore 15:23 Olivier Bélanger <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
Ok, c'est ce que j'ai fait. Si activate est allumé, les sources reprennent leur position d'origine à l'arrêt de la séquence, sinon, elles restent à leur dernière position.
