### ISSUE TITLE
En Octo Independent, sélectionner une source déplace la source 1

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#57]
V102, LBAP, AU (DP) et VST (Reaper)
Lorsqu'on déplace les sources d'une octophonie en mode Independent, le seul fait de toucher à une des autres sources (2 à 7) déplace la source 1.
Les sources au départ:

![Départ Independent](https://user-images.githubusercontent.com/8959779/67323604-b2bb9400-f4e0-11e9-85f7-882af0a94576.jpg)

Et après avoir touché chacune des 7 autres sources:
![Arrivée Independent](https://user-images.githubusercontent.com/8959779/67323631-c109b000-f4e0-11e9-80fc-02f88e7b3d32.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme la même chose en Logic, AU, mode independent. Dans mon cas cela
arrive pas seulement en octo, mais avec chaque configuration oùle nombre de
sources est de 2 à 8..

En VBAP il y aussi parfois de comportements similaires, par exemples si je
déplace d'abord la source numéro 2, puis la source 1 et enfin la source 3,
la troisième déplace toujours la source numéro 1.
Cela se produit pour tout nombre de sources supérieur à 2.

Vidéo https://www.dropbox.com/s/a6518or5h51nsvy/source1.mov?dl=0
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 22 ott 2019 alle ore 15:31 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Xon77** [comment]
La V103 règle cet issue pour moi dans Reaper.

**Comment by NicolaGiannini** [comment]
La V103 règle cet issue pour moi dans Logic.

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 4 nov 2019 alle ore 13:34 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Même chose dans DP
Réglé
