### ISSUE TITLE
Problème de démarrage des séquenceurs avec l'écriture de l'automation

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#59]
V101
Parfois ControlGRIS bloque le démarrage de la séquence DP s'il y a une écriture d'automation de presets mais ce n'est pas systématique et je ne suis pas encore arrivé à reproduire cela à tous les coups, mais c'est fréquent.

**Comment by Normandeau** [comment]
V102
Je viens d'avoir le même problème dans Logic. Cependant celui-ci m'informe du problème:

![Capture d’écran, le 2019-10-22 à 16 42 30](https://user-images.githubusercontent.com/8959779/67332693-632f9500-f4ed-11e9-8bda-bc0b395d1dd1.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme le problème, j'ai eu le même message en Logic.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 22 ott 2019 alle ore 17:00 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V103
Problème réglé avec DP 10.01
Problème réglé aussi avec Logic 10.4.7 mais je laisse Nicola confirmer avant de fermer l'issue

**Comment by NicolaGiannini** [comment]
Je confirme, réglé en Logic 10.4.7.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 4 nov 2019 alle ore 11:38 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Réglé
