### ISSUE TITLE
Contrôle des sources stéréo et automation de Movements

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#6]
Salut à tous,
Est que vous pensez qu'un mode de contrôle de sources stéréo peut être utile dans ControlGris? 
En ce qui concerne le déplacement des sources stéréo, moi j'utilise beaucoup dans la même piste des mouvements circulaires, en avant / en arrière, mais aussi de rapprochement et d'éloignement entre les deux sources. Ce que Logic appelle Spread. Vous pouvez voir le vidéo https://www.dropbox.com/s/zlj9rgy3kph1yml/spread.mov?dl=0

Maintenant dans ControlGris, si j'ai bien compris, il n'y a pas le moyen de faire tous ces types de mouvements dans la même piste. 
Je pense que cela pourrait être utile.

Qu'en pensez vous?

**Comment by NicolaGiannini** [comment]
On parlait hier avec Robert de la possibilité de considérer un seul point central au lieu de 2 sources différents. En contrôlant un seul point on pourrait bouger la source sur le plan x et y, mais aussi éloigner ou rapprocher le deux sources avec un paramètre spread. Qu'en pensez vous?

**Comment by Normandeau** [comment]
Pour être plus précis, un des problèmes majeurs de SpatGRIS est que l'on ne peut pas automatiser les mouvements. Nous avions fait le choix, il y a plusieurs années, de privilégier le concept de source maître et de sources esclaves. Il est peut-être temps de réaliser que ce concept est très limité, voire même erroné.
La plupart de spatialisateur utilise effectivement, comme le mentionne Nicola, le concept de point de contrôle central dans le cas de la stéréo (voir les vidéos de Nicola). Ce concept a le mérite d'éliminer l'idée de source maître et esclave. Les deux (ou plus) sources sont liées au même point.
Deux paramètres d'ajustement pourrait être ajoutés alors:
- largeur de la source
- angle des sources
Je reviens avec des graphiques plus explicites.

**Comment by Normandeau** [comment]
Trois exemples graphiques (ne tenez pas compte du Span ou de la position des hp):

Point central, Ouverture de la source à 90˚, Rayon à 0.66, Position à 0˚:
![point central position a 0 ouverture a 90 rayon a 0 66](https://user-images.githubusercontent.com/8959779/48647026-b1244a80-e9b8-11e8-8ca9-da082e041b47.jpg)

Point central, Position à 270˚, Ouverture à 135˚, Rayon à 0.33 :
![point central position a 270 ouverture a 135](https://user-images.githubusercontent.com/8959779/48647119-06605c00-e9b9-11e8-8350-e4586ba6dcb7.jpg)

Point central, Position à 45˚, Ouverture à 180˚, Rayon à 1.0:
![point central position a 45 ouverture a 180 rayon a 1 0](https://user-images.githubusercontent.com/8959779/48647318-a1593600-e9b9-11e8-883d-c63410b30936.jpg)

**Comment by Normandeau** [comment]
Cela signifie que notre paramètre Source Link (anciennement Movements) est changé assez radicalement.  Il faudra ajouter des valeurs de réglages pour établir la position du point central et la relation des sources:
- Position (de 0˚ à 359˚)
- Overture (de 0˚ à 359˚)
- Radius (de 0 à 1)
Je ne suis pas encore certain des termes (chez Logic c'est vraiment bizarre comme terminologie: Angle, Diversity, Spread). D'ailleurs le modèle Logic est défectueux à bien des égards, notamment si on veut déplace une source stéréo d'avant en arrière. Logic fait croiser les sources au centre et les inverse par la suite ce qui est problématique. Cela peut à la rigueur fonctionner ne mode VBAP mais pas en LBAP.

On aurait ainsi les Source Link suivants:
- Independent
- Symmetric: toutes les sources sont également réparties autour du point central et bougent de façon symétrique. Les sources peuvent être Stereo, Quad, 5.1, 6.1, ou Octo. Contrairement au mode Circulay Fully Fixed actuel, on pourrait faire varier les paramètres Position, Angle et Rayon.
- Asymmetric: toutes les sources sont inégalement réparties autour du point central. Pour y arriver, il faut d'abord se placer en mode Independent, placer les sources n'importe où, puis les solidariser avec Asymmetric. Cela correspondrait plus ou moins au mode Circular actuel.
- Lock: toutes les sources sont inégalement réparties autour du point central. Pour y arriver, il faut d'abord se placer en mode Independent, placer les sources n'importe où, puis les solidariser avec Lock. Au lieu de se déplacer en mode circulaire, les sources se comporteraient comme un bloc qui viendrait éventuellement s'écraser dans un coin.

Ainsi plus besoin des modes actuels:
- Fixed Radius
- Fixed Angle
- Fully Fixed
Puisque ces modes sont inclus avec la notion de point central.
Plus besoin de:
- Symmetric X
- Symmetric Y
Puisque ces deux modes sont possibles avec la notion de point central.

Est-ce que c'est clair?
Suffisant?
Possible?
Compatible VBAP/LBAP?

**Comment by belangeo** [comment]
Très clair pour moi!

**Comment by Normandeau** [comment]
Dans Reaper, rien à signaler, puisque selon ma recherche, le plugiciel Cockos qui permet de spatialiser, ReaSurround, ne permet pas de grouper les sources.

**Comment by Normandeau** [comment]
V101
Ces positions, telles qu'on les voit dans Logic, ne sont pas encore possibles. Avec le Delta Lock, on a plutôt du Symmetric X ou du Symmetric Y. À méditer.

**Comment by Normandeau** [comment]
V105
Voir issue #30 
Quand on aura la possibilité de bloquer les sources selon l'axe des X ou des Y, cela ouvrira bien d'autres avenues.
Je ferme celle-ci qui est un doublon en fait et elle commence à dater.
