### ISSUE TITLE
Affichage graphique des menus déroulants dans 2e écran

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#61]
V102
Lorsqu'on place ControlGRIS sur un 2e écran, les menus déroulants (Source Link, Trajectory Type, OSC Format, OSC Source) apparaissent tous isolés sur l'écran principal:

![Capture d’écran, le 2019-10-22 à 17 19 37](https://user-images.githubusercontent.com/8959779/67334449-2618d200-f4f0-11e9-83a0-b3963a95a7cf.jpg)

**Comment by NicolaGiannini** [comment]
Dans mon cas les menus déroulants apparaissent tous isolés, si j’ouvre le
menu et puis déplace la fenêtre du plugin. J'ai essayé, et la même chose
arrive avec SpatGRIS.


vidèo : https://www.dropbox.com/s/yyi4n44i796zzvl/fenetre.mov?dl=0
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 22 ott 2019 alle ore 17:20 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V104
Cela a l'air réglé.
