### ISSUE TITLE
Affichage incohérent de la position des sources à l'ouverture du plugin

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#62]
C'est vraiment un infime détail, mais à l'ouverture du plugin, la source 1 se trouve à droite (au lieu d'être à gauche, théoriquement) et inversement pour la source 2.
Si j'initialise avec 1 source, puis ensuite avec 2 sources, comme au départ, la source 1 se trouve bien à gauche, ce qui est la position correcte selon la 1ère règle de source placement, qui est Left alternate.

**Comment by Normandeau** [comment]
V103
Je confirme

**Comment by NicolaGiannini** [comment]
Je confirme moi aussi.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 4 nov 2019 alle ore 11:39 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Xon77** [comment]
Problème réglé sur Reaper

**Comment by Normandeau** [comment]
V104
Réglé
