### ISSUE TITLE
Lien des spans: automation défecteuse

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#63]
V103
Il existe bien 2 cases de link pour l’Azimuth et l’Elevation, ainsi qu’une autre reliant les 2, mais ce sont des éléments de l’interface graphique, qui ne sont pas enregistrés en automation et rentre même en conflit (lorsqu'ils sont différents, flickering) avec les courbes d’automation des spans enregistrés individuellement pour chaque source.

**Comment by Normandeau** [comment]
V104
Il n'y a plus de Link pour les Spans. Réglé.
