### ISSUE TITLE
Préservation du lien en Circular et Circular Fixed Angle en VBAP

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#64]
Le lien entre la source 1 et les autres sources n’est pas préservée dans certaines configurations de source link en mode VBAP : Circular et Circular Fixed Angle (lorsque l'on bouge la source 1).

V 1.0.3 testé sur Reaper :

1. J’initialise 8 sources (le source link est au départ en mode indépendant)
2. Je place la source 1 dans le cercle/carré intérieur près du centre
3. Je passe en source link : Circular ou Circular Fixed Angle
4. Je déplace la source 1 vers les extrémités, puis je la rapproche de nouveau du centre.
5. Résultat : Le lien d’élévation initial entre la source 1 et les autres n’est plus préservée, puisque toutes les sources se retrouvent maintenant avec la même élévation, alors qu’au départ le lien d’élévation était différent.

Ce problème de préservation du lien n’a pas lieu en LBAP.

**Comment by NicolaGiannini** [comment]
Je confirme, testé aussi sur Logic 10.7.4
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 4 nov 2019 alle ore 13:05 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Je confirme dans DP aussi.

**Comment by Normandeau** [comment]
Je l'ai fermée par erreur. Réouverte. Bravo, belle trouvaille!

**Comment by Xon77** [comment]
Juste pour préciser, la préservation du lien n'a pas lieu non seulement quand je déplace la source 1 vers les extrémités, mais aussi quand on la rapproche du centre : 

0. Initialisation par défaut à 2 sources :
1. Je place la source 2 au centre
2. Je passe en source link : Circular ou Circular Fixed Angle
3. Je déplace la source 1 vers le centre
4. Résultat : la source 2 ne devrait pas bouger. Lien rompu

**Comment by Xon77** [comment]
En mode LBAP, la manipulation que je viens de décrire ci-dessus conserve le lien, mais produit un parcours étrange pour la source 2 (par rapport à ce que faisait le Spatgris). La source 2 ne devrait pas bouger quand je me rapproche du centre. Je ne sais pas si je dois faire une nouvelle issue ou changer le titre de celle-ci en incluant LBAP.

**Comment by NicolaGiannini** [comment]
Je confirme ces autres deux comportements.

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 4 nov 2019 alle ore 17:23 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V104
Cela semble réglé. Je laisse à Christophe le soin de confirmer.

**Comment by Xon77** [comment]
Problème réglé pour moi dans Reaper (V104)
