### ISSUE TITLE
Comportement limité avec le lien delta lock

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#65]
Je parle ici d’une amélioration possible dans le contrôle du lien delta lock.

En considérant l’élévation en LBAP par exemple :
1. Soit 2 sources, la 1 en bas et la 2 en haut,
2. Je passe en lien delta lock,
3. La Croix étant au centre et opérant de manière relative simple permet de placer soit la source 1 au centre, soit la source 2 au centre.

Il serait selon moi intéressant d’aller au delà ce cette limite afin de pouvoir écraser complètement les 2 sources vers le haut ou le bas, si on le souhaite.
Il faudrait que le delta ne soit pas simplement relatif, mais opère une multiplication avec une certaine courbe ou que le range pour l’ancrage X soit plus grand que celui des sources...

Ceci est aussi valable pour l’Azimuth/Distance.
A discuter ensemble pour voir si utile et faisable.

**Comment by Normandeau** [comment]
Très bonne suggestion.

**Comment by NicolaGiannini** [comment]
Je suis d’accord.
Une solution partielle pourrait être cela de gérer les marges du carré Elevation en LBAP comme on l'a fait pour le carré Azimuth-Distance. Mais il faudrait changer quelque chose en SpatGRIS2. Présentement on peut pas placer les sources au-delà de 1 en Z (Elevation DOME à 90°)

Je me rappelle d’un courriel de Robert dont il disait quelque chose comme “Il faudrait donner la possibilité d’envoyer les sources loin dans le ciel” mais je n’arrive pas à le trouver :)
