### ISSUE TITLE
Problème majeur de position par défaut en arrière-plan

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#66]
V103
Je m'essaie avec un projet de composition avec la V103 dans DP10.01. Premier problème majeur: lorsqu'on ouvre une séquence sauvegardée avec plusieurs ControlGRIS en mode LBAP (25 occurrences stéréo ici), toutes les sources se retrouvent en haut du dôme, alors qu'elles ont toutes été positionnées à des endroits spécifiques et sauvegardées comme telles. On voit que seules les sources 1 et 2 sont placées ailleurs, mais c'est parce que la fenêtre du plugiciel pour cette piste est ouverte. Donc lorsque les fenêtres de ControlGRIS sont fermées, celui-ci n'envoie pas les bonnes données OSC, mais une valeur générique par défaut qui est:
Ray Length: 0.00
Angle: 90.00
Par ailleurs, on voit qu'il y a quelques Spans en usage. Ceux-ci avaient été positionnés selon l'axe 270˚-90˚ mais il se retrouvent selon l'axe 180˚-0˚, donc décalés de 90˚.
Toutes les sources se repositionnent au bon endroit lorsque les fenêtres des ControlGRIS sont ouvertes. Mais c'est une situation impossible dans la réalité. Il faut que les données OSC envoyés par le plugiciel soient conformes aux données sauvegardées en tout temps, bien évidemment.

![Capture d’écran, le 2019-11-05 à 12 54 20](https://user-images.githubusercontent.com/8959779/68232805-e3fd8f00-ffcb-11e9-8144-78554f66967f.jpg)

**Comment by Xon77** [comment]
Il est vrai que je n'ai pas essayé avec 25 occurrences stéréo, mais avec plusieurs instances, mais je n'ai pas pour l'instant observé dans Reaper que ControlGRIS n'envoie pas les bonnes données OSC quant aux positions lorsque les fenêtres du plugin sont fermées.

**Comment by Normandeau** [comment]
Testé avec Reaper 5.98 et 8 pistes stéréo: même résultat qu'avec DP.
Christophe: as-tu fermé et rouvert la session? Voire carrément fermé et rouvrir Reaper (ce qui est une situation de travail réel)?
(Il faut aussi resetter les Input Position de ServerGRIS)

![Capture d’écran, le 2019-11-05 à 15 29 23](https://user-images.githubusercontent.com/8959779/68243689-11086c80-ffe1-11e9-8f39-5689aeec6c56.jpg)

J'obtiens le même résultat avec Logic:

![Capture d’écran, le 2019-11-05 à 15 37 46](https://user-images.githubusercontent.com/8959779/68244177-45c8f380-ffe2-11e9-8213-cfaa378863ed.jpg)

**Comment by Normandeau** [comment]
Comparaison avec SpatGRIS: la même séquence avec 25 plugiciels, sans ouvrir une seule fenêtre d'édition:

![Capture d’écran, le 2019-11-05 à 15 40 14](https://user-images.githubusercontent.com/8959779/68244429-d0a9ee00-ffe2-11e9-8af3-76c017cae892.jpg)

**Comment by Xon77** [comment]
oui, j'ai même redémarré mon ordinateur. Mais, je vais recommencer le test, il doit y a avoir qqch que je fais mal... j'avais testé avec 4,5 sources stéréo...
Positions à l'ouverture du séquenceur Reaper :
<img width="607" alt="Capture d’écran, le 2019-11-05 à 15 58 13" src="https://user-images.githubusercontent.com/1010040/68245614-41520a00-ffe5-11e9-86ac-232caac5e0e1.png">

**Comment by Normandeau** [comment]
Je ne sais si cela a un rapport, j'ajoute cette information: la position des sources est mémorisée dans un preset dans chacune des instances de ControlGRIS. Autrement dit, et je pense que c'est un peu cela l'idée, mettre en mémoire des paramètres pour que ceux-ci soient reconnus à l'ouverture de la séquence.

**Comment by Xon77** [comment]
Cela doit être donc lié aux preset positions, puisque que dans mon cas, j'avais juste des trajectoires XY et des source link, mis en mémoire. Je vais retester avec les preset positions.

**Comment by NicolaGiannini** [comment]
J'ai pu reconstruire le problème.
Dans mon cas, cela se produit lorsque le preset actif est le numéro 1, que
j'aie enregistré des automations ou non.

Si le preset actif est le numéro 1, lors de la fermeture et de la
réouverture du séquenceur, les données envoyées sont incorrectes et les
sources ne sont pas affichées correctement dans ServerGRIS. Si le preset
actif n'est pas le numéro 1, les données envoyées sont correctes.

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 5 nov 2019 alle ore 16:57 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
Ha, relié à l'issue #67 . Le paramètre nèest pas appelé à l'initialisation si identique à la valeur par défaut... Ça doir pouvoir se contourner!

**Comment by Normandeau** [comment]
Bravo Nicola, belle trouvaille.
Je confirme le fait que c'est relié au preset no 1. Lorsque je mets les mêmes valeurs dans le preset no 2, que je sauvegarde et que je rouvre le tout, les positions sont bel et bien remises au bon endroit.

**Comment by belangeo** [comment]
Oui, c'est réglé en initialisant le paramètre d'automation à 50 plutôt que 1. Mais j'ai un autre fix en tête qui permettrait de régler aussi l'issue #68). À suivre...

**Comment by Normandeau** [comment]
V104
Réglé
