### ISSUE TITLE
L’automation Preset Position n’est pas enregistrée si c’est le preset N°1 au départ

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#67]
Comme le dit le titre, je dois forcément passer et enregistrer par un preset différent du N° 1 pour enregistrer le 1er preset en tant que courbe d’automation. Le plugin doit peut-être estimer que la valeur est déjà à 1 et qu’il n’est pas nécessaire de l’enregistrer en automation.

(V 103) Testé sur Reaper : 

1. Je bouge les positions de mes sources
2. J’enregistre le preset position N°2
3. Je passe en enregistrement d’automation.
4. J’appelle le preset position N°2
5. Résultat correct : une courbe d’automation apparait avec un point pour le preset N°2.

Si je fais la même opération avec le preset N°1, rien est enregistré.
Je dois obligatoirement passer par un autre numéro pour enregistrer la courbe d'automation du preset 1.

**Comment by Xon77** [comment]
Problème réglé dans Reaper

**Comment by Normandeau** [comment]
V104
Réglé.
