### ISSUE TITLE
Les sources reviennent toujours à la position du dernier preset actif, lorsque la fenêtre du plugin est fermée et rouverte, même si les sources ont été déplacées après l'enregistrement du preset.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#68]
V103
Les sources reviennent toujours à la position du dernier preset actif, lorsque la fenêtre du plugin est fermée et rouverte, même si les sources ont été déplacées après l'enregistrement du preset.

J'active un preset.
Je déplace les sources.
Je ferme la fenêtre.
Je rouvre la fenêtre.
Les sources retournent toujours à la position du preset actif.

Je m'attendrais à ce que les sources restent où je les ai laissées. Une solution pourrait être que lorsqu'on déplace les sources, le preset est automatiquement désactivé.

**Comment by Xon77** [comment]
Je confirme. En effet, le fait qu'un preset soit toujours sélectionné pose problème. D'autant plus que les presets de position ne sont pas appelés si le plugin est déjà sur cette valeur.

**Comment by belangeo** [comment]
Ok, maintenant il est possible de n'avoir aucun preset sélectionné (c'est la valeur 0 dans l'automation, les presets commencent à 1). Ça règle cet issue ainsi que les issue #66 et #67. Je ne crois pas avoir brisé quoi que ce soit dans l'opération mais ça sera à mettre à l'épreuve!

**Comment by Xon77** [comment]
V 104 Problème réglé dans Reaper

**Comment by NicolaGiannini** [comment]
V 104 Problème réglé dans Logic aussi.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 12 nov 2019 alle ore 14:33 Christophe Lengelé <
notifications@github.com> ha scritto:
