### ISSUE TITLE
L'écriture de l'automation du paramètre Source Link ne marche pas en Logic ni dans DP.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#69]
V1.0.3
Logic 10.4.7
L'écriture de l'automation du paramètre Source Link ne marche pas en Logic.
Le paramètre est correctement sauvegardé dans le presets du DAW

En Ableton (9.7.7) et Reaper, tout marche correctement (presets DAW et automations).

**Comment by Normandeau** [comment]
Dans DP, je ne peux enregistrer le Source Link que manuellement, point par point, mais pas pendant que la séquence enregistre de l'automation (il ne se passe rien). Dans Reaper on peut le faire facilement.
Pour ce qui est de sauvegarder la valeur de Source Link, il ne semble pas que cela soit possible de la sauvegarder ailleurs que dans la séquence elle-même. Faites le test suivant:
- Mettre une valeur de Source Link, par exemple Fixed Radius
- Sauvegarder à la fois le preset (no 2 par exemple) et le preset du DAW
- Changer le Source Link, pour Delta Lock par exemple
- Fermer la fenêtre du plugin
- Fermer la séquence après l'avoir sauvegardée.
Que se passe-t-il à l'ouverture de celle-ci?
C'est le dernier Source Link qui est rappelé, Delta Lock, et non pas celui est sauvegardé, Fixed Radius, exact?
Validé dans DP, Reaper et Logic.

**Comment by NicolaGiannini** [comment]
J'ai fait le test en Logic et c'est le dernier Source Link qui est rappelé,
Delta Lock, et non pas celui est sauvegardé, Fixed Radius.

Pour moi le comportement est correct, parce que je m'attend que la dernier
Source Link soit rappelé. Ce qui, par exemple, ne passe pas dans le issue
68 https://github.com/GRIS-UdeM/ControlGris/issues/68

En Logic, par example, les paramètres rappelés sont les derniers et non
ceux du preset.


   - Je sauvegarde un preset d'un plugin
   - Je change des paramètres du plugin
   - Je sauvegarde la session.
   - J'ouvre la session.
   - Les paramètres rappelés sont les derniers et non ceux du preset.




Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mer 6 nov 2019 alle ore 16:56 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
> C'est le dernier Source Link qui est rappelé, Delta Lock, et non pas celui est sauvegardé, Fixed Radius, exact?

Ça me semble logique puisque c'était la dernière valeur, elle fait partie du « state » du plugin. Si tu appelles le preset que tu as enregistré dans le DAW, SOurce Link devient bien Fixed Radius ?

**Comment by Normandeau** [comment]
Exact.

**Comment by Normandeau** [comment]
V104
L'écriture de l'automation de Source Link fonctionne maintenant dans DP
La valeur de Source Link est bien enregistré dans le preset du DAW

**Comment by Normandeau** [comment]
À valider dans Logic

**Comment by Normandeau** [comment]
Ça fonctionne dans Logic
