### ISSUE TITLE
Rendre les sources secondaires non sélectionnables

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#7]
Quand on utilise des mouvements comme "circular fixed radius" où il y a une source "master" et les autres "slave" moi je donnerai la possibilité de rendre les sources "slave" non sélectionnables, comment-ça il n'y aura pas le problème que si je sélectionne la source slave, l'automation ne marche plus.

**Comment by Normandeau** [comment]
Si on va de l'avant avec le concept de point central, cet issue est caduque, car cela implique que les notions de source master et salve disparait. Attendons de voir comment cela sera implementé dans ControlGRIS.

**Comment by belangeo** [comment]
Dans le ControlGris, les sources ne sont plus automatisables, seule la source « trajectoire » l'est. En mode groupé, on peut bouger les sources dans les plans, mais seulement en manipulant la source 1 (puisqu'en mode groupé, la position des autres sources est généralement calculée en fonction de la source 1).

**Comment by led78** [comment]
Est-ce que l'écriture de trajectoires indépendantes pour les pistes stéréo (sources 1 et 2) demeurera possible? Puisque ce ne sont pas tous les DAW qui permettent d'avoir plusieurs pistes multicanales on remplace le contrôle indépendant de chaque source par un contrôle groupé. Mais, il serait tout de même pertinent de conserver le mode classique d'écriture d'automatisation indépendante pour les sources 1 et 2, puisque tous les DAW offrent des pistes mono ou stéréo. Le mode groupé serait donc imposé à toute piste ayant au delà de 2 sources/canaux. Est-ce possible?
