### ISSUE TITLE
Les presets positions peuvent ne pas être bien rappelés, si le rapport des sources a changé dans un même source link

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#70]
Je donne un exemple en VBAP (V104, testé dans Reaper) :

0. Intialisation par défaut à 2 sources.
1. J’enregistre 1 preset N°1, avec les 2 sources localisés respectivement à gauche et à droite
2. Je me mets en enregistrement d’automation
3. J’appelle le preset N°1 pour enregistrer la courbe d’automation
4. Je passe en Source Link circular
5. J’enregistre une automation et déplace la source 1 vers le haut en suivant le cercle, puis une fois en haut me rapproche du centre.
6. J’arrête l’enregistrement et lance la lecture de l’automation.

Résultat : Le preset position 1 (avec les 2 sources respectivement à gauche et à droite) n’est plus rappelé correctement car la source 2 n’est plus à sa position de départ.

**Comment by NicolaGiannini** [comment]
Je confirme. Dans mon cas, la source 2 reste dans la dernière position où elle se trouvait après l'enregistrement de l'automation (c'est-à-dire plus proche du centre, par rapport à l'exemple de Christophe).

Je peux rappeler la position correcte de la source 2 en cliquant sur le preset avec la souris, mais dès que le séquenceur lit l'automation de la trajectoire, la source 2 revient à la dernière position où elle se trouvait après l'enregistrement de l'automation.

**Comment by Normandeau** [comment]
Je confirme dans DP

**Comment by Normandeau** [comment]
V105
C'est réglé, mais cela génère un autre bogue. Je fais une nouvelle issue.
