### ISSUE TITLE
En source link Delta lock, l’ancrage x, qui permet décrire l’automation de la trajectoire, peut apparaître en dessous de la source 1

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#71]
Je donne un exemple en VBAP (V104, testé dans Reaper) :

0. Intialisation par défaut à 2 sources
1. Je me mets en enregistrement d’automation
2. Je passe en source link Circular
3. Je déplace la source 1
4. Je passe en source link Delta Lock
5. Résultat : Le x de l’ancrage apparaît en dessous de la source 1.

Il serait préférable que l’ancrage apparaisse au dessus de la source 1, car la source 1 dans ce source link spécifique « Delta lock » ne permet pas d’écrire l’automation. Et c’est trompeur… on est obligé de déplacer la source 1, pour récupérer le x et écrire l’automation…

**Comment by NicolaGiannini** [comment]
Je confirme, même chose en Logic.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 12 nov 2019 alle ore 17:19 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Je n'arrive pas à reproduire ce comportement dans DP. Le X de l'ancrage apparaît toujours au cendre de l'écran. Peut-être est-ce dû à Reaper qui commence à enregistrer des données d'automation dès que tu passes en mode d'enregistrement? Ce qui n'est pas le cas de DP, qui attend que le séquenceur démarre.

**Comment by belangeo** [comment]
C'est déjà corrigé... Il suffit simplement de dessiner le X après avoir dessiner les sources en Delta Lock.

**Comment by Normandeau** [comment]
V105
Réglé
