### ISSUE TITLE
Le preset position n’est pas rappelé lorsque l’on est déjà sur le même n° de preset

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#72]
Je donne un exemple en VBAP (V104, testé dans Reaper) :

0. Intialisation par défaut à 2 sources
1. Je me mets en enregistrement d’automation
2. J’enregistre un preset N°1, avec les 2 sources localisés respectivement à gauche et à droite
3. J’appelle le preset N°1 pour enregistrer la courbe d’automation
4. J’enregistre une automation et déplace la source 1
5. Je fais pause (suis toujours enregistrement d’automation) 
6. J’appelle le preset N°1.
7. Je passe en lecture d’automation et relis la séquence.
8. Résultat : Le preset position 1 (étape 6), qui aurait dû être rappelé à la fin de l’automation, n’est pas rappelé, car on est déjà sur le preset n°1.

Bien que cet exemple soit très particulier et ne représente pas forcément un cas pratique de composition, ce phénomène risque de poser problème dans des projets de composition plus complexes. 
Je pensais que cet issue était aussi à l’origine de l'issue #70  mais apparemment non, en faisant d’autres tests, appelant plusieurs preset positions à l'étape n°3 de l'issue #70.

**Comment by NicolaGiannini** [comment]
Je confirme. Un preset n'est pas rappelé par l'automation si on est déjà
sur ce preset. Par contre il est rappelé en y cliquant.

Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 12 nov 2019 alle ore 18:34 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
En effet, si la valeur d'automation ne change pas, le DAW ne fait rien... Pour régler l'issue #70, j'ai fait en sorte que lorsque l'on démarre la lecture, si un preset position est sélectionné, il est automatiquement rappelé pour mettre les positions à jour. C'est pas mal le mieux que l'on peut faire ici...

**Comment by Normandeau** [comment]
C'est un cas d'espèce un peu étrange je dois avouer. Pourquoi vouloir rappeler le preset sur lequel on travaille? Dans DP ça ne pose pas de problème. Une solution simple est d'enregistrer deux fois le même preset et de les rappeler alternativement si on a besoin de remettre les pendules à l'heure.
