### ISSUE TITLE
Perte du contrôle de la position de la source 2 avec certains source links

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#73]
Comment bloquer la source 2 dans les coins ? 
V104, testé dans Reaper

Je donne un exemple en LBAP (mais des anomalies existent aussi en VBAP)  :

0. Je passe en mode LBAP à 2 sources
1. Je rapproche la source 1 du centre
2. Je passe en source link Circular ou Circular Fixed Angle
3. Je sélectionne la source 2 et essaye de la déplacer
4. Résultat : la source 2 reste bloqué dans le coin et en modifiant la source 1, je positionne la source aux 4 coins du carré

Pour régler le problème, je suis obligé de repasser en mode indépendant.

**Comment by Xon77** [comment]
Le même expérience avec 8 sources produit un manège des sources au coins très colorés..

**Comment by NicolaGiannini** [comment]
Je confirme.


Testé aussi avec Logic.

En Vbap :

1 Je ouvre le plugin à 2 sources.

2 Je rapproche la source 1 du centre

3 Je passe en source link circular

4 Je sélectionne la source 2 et essaye de la déplacer vers le centre

5 La source 2 disparaît, et réapparaît en bas.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mar 12 nov 2019 alle ore 19:49 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
Ceci entre en conflit avec le fix pour l'issue #64... Ça ne sera pas simple de conserver les deux comportements (avant cet issue et après le fix de #64). Je vais voir ce que je peux faire, ça va peut-être demander de revoir toute la logique des liens entre les sources...

**Comment by NicolaGiannini** [comment]
V105 ça semble réglé.

**Comment by Normandeau** [comment]
Oui c'est réglé, mais cela a fait apparaître un nouveau bogue. Je fais une nouvelle issue.
