### ISSUE TITLE
Quelques petites remarques graphiques

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ControlGris#74]
Juste 2 petites choses, concernant l’interface graphique :

1. La case Activate pour Azimuth / Distance pourrait être en dessous de « Realtime » pour le Trajectory Type, afin d’être aligné, au lieu d’être complètement à gauche. 

2. Le nombre de sources est sélectionné (avec une barre clignotante), quand on bascule d’onglet, par exemple de Settings vers Source, alors que je n’ai rien changé.
Je peux l’enlever en validant return, mais il serait préférable que cette barre clignotante n’apparaisse pas si cela est possible si je n’ai rien changé.
Je me demande d’ailleurs concernant le nombre de sources, si un pop up menu, à l’instar de source placement, ne serait pas préférable, étant donné qu’on ne peut avoir que 8 sources ou éléments sélectionnables.

**Comment by NicolaGiannini** [comment]
Je suis d'accord que cette barre clignotante n’apparaisse pas si cela est
possible si je n’ai rien changé.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno mer 13 nov 2019 alle ore 11:47 Christophe Lengelé <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V105
Réglé
