### ISSUE TITLE
L'enregistrement de l'automation de la valeur recording trajectory X commence toujours de 0.5, si la source 1 n'a pas été déplacée avant de l'enregistrement.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#75]
V104
L'enregistrement de l'automation de la valeur recording trajectory X commence toujours de 0.5, si la source 1 n'a pas été déplacée avant de l'enregistrement.

Testé dans Logic and Reaper.

En Logic
J'ouvre une instance de ControlGRIS 
J'active la fonction Latch 
J'appuie sur play
Je déplace la source 1 vers le centre
J'appuie sur stop
La courbe d'automation de la de la valeur recording trajectory X part de 0,5, même si la source 1 est à 0. Cela provoque un saut. 

Dans Reaper
J'ouvre une instance de ControlGRIS 
J'active la fonction Latch
Je fais avancer la tête de lecture de quelques secondes (sans appuyer sur play)
Je touche la source 1 avec la souris
Une courbe d'automation est tracée pour la valeur recording trajectory X de 0,5 à 0.

**Comment by Normandeau** [comment]
Je n'ai pas ce problème dans DP.

**Comment by Normandeau** [comment]
V105
Réglé
