### ISSUE TITLE
Un Ray Length de 0 rammène Angle à 0 automatiquement

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/ControlGris#76]
Dans Configuration -> Source tab.

Peu importe l'angle spécifié, toucher le 0 avec Ray Length rammène automatiquement Angle à 0. Ça ne devrait pas.

**Comment by NicolaGiannini** [comment]
Je confirme cela.

**Comment by NicolaGiannini** [comment]
V. 1.0.5 réglé.
