### ISSUE TITLE
Écriture d'un Preset 0 pendant l'écriture de l'automation

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#77]
V105
J'ai repris tel quel la procédure décrite par Christophe dans l'issue no 70:
Je donne un exemple en VBAP (V104, testé dans Reaper) :
Intialisation par défaut à 2 sources.
    J’enregistre 1 preset N°1, avec les 2 sources localisés respectivement à gauche et à droite
    Je me mets en enregistrement d’automation
    J’appelle le preset N°1 pour enregistrer la courbe d’automation
    Je passe en Source Link circular
    J’enregistre une automation et déplace la source 1 vers le haut en suivant le cercle, puis une fois en haut me rapproche du centre.
    J’arrête l’enregistrement et lance la lecture de l’automation.

J'ai ajouté le fait d'enregistrer 4 presets, et d'automatiser le passage de l'un à l'autre en même temps que l'automatisation d'une trajectoire manuelle. Lorsqu'on enregistre celle-ci, un preset 0 s'écrit en même temps! Cela ne déclenche pas de presets à la lecture puisque ceux-ci commence à 1, mais ça encombre le fenêtre d'automation pour rien.
Vérifié sur DP, Reaper et Logic.

DP:
![DP Preset 0](https://user-images.githubusercontent.com/8959779/75054250-03fd8380-54d3-11ea-9282-78607e07c6a6.jpg)

Logic:
![Logic Preset 0](https://user-images.githubusercontent.com/8959779/75054278-0cee5500-54d3-11ea-8895-56a25f7f6714.jpg)

Reaper:
![Reaper Preset 0](https://user-images.githubusercontent.com/8959779/75054292-15469000-54d3-11ea-8aeb-b308942a0b1d.jpg)

**Comment by belangeo** [comment]
Le problème est qu'un point d'automation ne génère pas nécessairement un événement dans le plugin si la valeur est identique à la position précédente. Alors, si on écrit une automation de preset, par exemple, au début de la séquence, et qu'ensuite les sources changent de position via une automation, l'automation de preset ne sera probablement pas rappelée lorsque la séquence sera remise en marche à partir de 0. Le fait d'écrire un preset 0 (qui n'a aucune incidence sur le preset lui-même) lorsque les sources changent de position par rapport au preset sélectionné assure que le preset sera rappelé si on stop/start par exemple.

Je ne vois pas d'autre façon d'assuré que ça fonctionne à tout coup, peu importe le DAW.

**Comment by Normandeau** [comment]
Une question alors: est-il nécessaire d'effacer toutes les données de preset lorsqu'on enregistre les positions xy?
Si j'enregistre des positions de presets:

![Capture d’écran, le 2020-02-28 à 15 59 27](https://user-images.githubusercontent.com/8959779/75560357-4aa82c00-5a45-11ea-8820-c84f05869c43.jpg)

Et qu'ensuite j'enregistre des déplacements en xy (bon d'accord c'est un peu tordu comme procédure, mais tant qu'à tester...), ces dernières remplacent les valeurs de preset précédentes par la valeur 0 en même temps que les données xy:

![Capture d’écran, le 2020-02-28 à 16 00 21](https://user-images.githubusercontent.com/8959779/75560480-85aa5f80-5a45-11ea-87cb-a52ee7a8815b.jpg)

Vérification dans DP, Reaper et Logic en mode Latch.

**Comment by belangeo** [comment]
À partir de la version 1.0.6, un seul 0 dans l'automation de preset devrait être écrit lorsqu'une automation modifie la position des sources. Cela permet au plugin de savoir que les sources ne sont plus dans la position sauvegardé dans le preset mais que c'est « normal », c'est une écriture d'automation qui a provoqué le changement.

**Comment by Normandeau** [comment]
V107
À expliquer clairement dans le manuel. L'écriture de l'automation x-y-z efface l'automation des presets en remplaçant cette dernière par un preset 0.

**Comment by Normandeau** [comment]
V109
Mis dans le manuel
