### ISSUE TITLE
Circular Fully Fixed et Circular Fixed Radius sont inexacts

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#78]
V105
Mode CUBE
On place 8 sources en mode Circular Fully Fixed.
On passe en Independant et on déplace la source 1.
On repasse en Circular Fully Fixed.
La source 1 n'est pas à la bonne place.
Le rayon n'est pas le bon: 70 pour 1 et 76 pour tous les autres (dans cet exemple):

![Capture d’écran, le 2020-02-21 à 18 11 47](https://user-images.githubusercontent.com/8959779/75055745-e2ea6200-54d5-11ea-98f7-ce371e1b5f0c.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme, même chose en Circular Fixed Radius.

**Comment by Normandeau** [comment]
V106
Réglé

**Comment by Normandeau** [comment]
V106
J'ai été un peu vite en affaire en écrivant que c'était réglé. En fait, cela semble réglé en mode orthophonique, mais en stéréo on a toujours le même problème. Quand on passe de Independent, en plaçant les deux sources de manière asymétrique, à Fixed Radius, ou Fully Fixed, aucun des deux ne remet les deux sources en position symmétrique.
Petit film:
https://www.dropbox.com/s/k9ll7220yazd8l2/Fully%20Fixed.mov?dl=0

**Comment by belangeo** [comment]
Mmm... Je n'arrive pas à reproduire...

**Comment by Normandeau** [comment]
V107
Le mode Circular Fully Fixed ne fonctionne plus du tout, ni en octo, ni en stereo.

**Octo**
Independent:
![Capture d’écran, le 2020-03-13 à 09 29 34](https://user-images.githubusercontent.com/8959779/76625300-4da72000-650d-11ea-9d4a-af59e6ca78c9.jpg)

Circular Fully Fixed:
![Capture d’écran, le 2020-03-13 à 09 29 47](https://user-images.githubusercontent.com/8959779/76625319-58fa4b80-650d-11ea-8020-e9e0f25022a7.jpg)

Stereo
Independent:
![Capture d’écran, le 2020-03-13 à 09 32 09](https://user-images.githubusercontent.com/8959779/76625452-9eb71400-650d-11ea-9d7c-b8d83460ebbb.jpg)

**Comment by Normandeau** [comment]
Le message est parti trop vite de Github. Il manque la 4e image et le fait que la situation est la même sur DOME ou CUBE.

**Comment by belangeo** [comment]
Mmm... On dirait que j'ai brisé quelque chose en ajoutant les modes symétriques. Je vais y voir...

**Comment by NicolaGiannini** [comment]
Je confirme le comportement.

**Comment by Normandeau** [comment]
V108
Cela semble réglé. À confirmer.

**Comment by NicolaGiannini** [comment]
testé en Logic, cela semble réglé.
