### ISSUE TITLE
Bouton Span Link ni mémorisable, ni automatisable

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#79]
V105
Le bouton qui relie Azimuth Span et Elevation Span n'est ni automatisable, ni mémorisable dans les Presets.
L'un ou l'autre serait utile, surtout mémorisable dans les Presets.

**Comment by NicolaGiannini** [comment]
je suis d'accord, j'ajouterais aussi un texte au-dessus du bouton : "Link Span".
Au premier abord, la double flèche pourrait faire penser à une inversion des paramètres, plutôt qu'à un lien entre les paramètres.

**Comment by Normandeau** [comment]
V106
Réglé
