### ISSUE TITLE
OSC bidirectionnel

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#80]
V105
OSC n'est actuellement pas directionnel, c'est à dire que si on utilise une interface de type iPad, celle-ci n'est pas mise à jour lorsque le ControlGRIS est actif. Dans l'esprit où on voudrait reprendre la main sur le iPad pendant qu'une séquence automatisée joue, cela poserait un problème.
À ajouter donc.

**Comment by belangeo** [comment]
Les données de la trajectoire 1 en OSC sont maintenant bidirectionnelles. Les prochains contrôles (spans, source links et presets) seront ajoutés dans les deux sens.

**Comment by belangeo** [comment]
À titre de référence, voici les adresses OSC que reconnait ControlGris (en entrée comme en sortie):

- /controlgris/traj/1/x value
- /controlgris/traj/1/y value
- /controlgris/traj/1/z value
- /controlgris/traj/1/xyz/1 value
- /controlgris/traj/1/xyz/2 value
- /controlgris/traj/1/xyz/3 value
- /controlgris/traj/1/xy value
- /controlgris/traj/1/xyz value
- /controlgris/azispan value
- /controlgris/elespan value
- /controlgris/sourcelink value => 1 à 6
- /controlgris/sourcelinkalt value => 1 à 5
- /controlgris/presets value => 1 à 50

**Comment by Xon77** [comment]
Je suis en train de mettre en place l'OSC bidirectionnel pour le Lemur.
Et j'ai quelques questions pour toi, Olivier :

1. L'OSC bidirectionnel fonctionne avec les adresses spécifiées au dessus. Un problème apparait lors de l'utilisation à la fois du moteur physique du Lemur et la bi-directionalité, car dès que je ne touche plus la tablette, les données de la tablette ne sont pas reçues par le plugin, bien qu'elles soient modifiées algorithmiquement par la tablette, car le plugin reprend le contrôle. 
En clair, est ce possible que la bi-directionalité fonctionne uniquement lorsque les données X,Y ou Z des sources du plugin sont modifiées via le DAW ?

2. A quoi correspond exactement ces adresses avec 1, 2 et 3 ?
/controlgris/traj/1/xyz/1 value
/controlgris/traj/1/xyz/2 value
/controlgris/traj/1/xyz/3 value

**Comment by belangeo** [comment]
Salut Christophe,

1. Es-tu certain que le Lemur envoie bien des messages OSC lorsqu'il est en mode algo? Je demande parce que le ControlGris ne sait pas quand, ni comment les données sont modifiées dans le Lemur, tout ce qu'il connait, c'est les messages OSC reçus sur son port d'écoute. Pour ce qui est de la bi-directionnalité, ControlGris envoie un message seulement lorsque la valeur d'un paramètre a changée, soit manuellement, soit via une automation.

2. Un multislider à trois sliders dans TouchOSC, nommé "/controlgris/traj/1/xyz", envoie un message à l'adresse "/controlgris/traj/1/xyz/1" pour le premier slider, "/controlgris/traj/1/xyz/2" pour le second, etc. Perso, je m'attendais à un message à l'adresse "/controlgris/traj/1/xyz" avec une liste de trois valeurs mais ce n'est pas ce que TouchOSC fait. J'ai donc laissé les deux options.

**Comment by Xon77** [comment]
Quelques questions pour clarifier certaines choses car je ne vois pas pour l’instant comment faire fonctionner en même temps la bidirectionalité et le moteur physique, qui permet de lancer un geste sur la tablette, envoyant des données au plugin, tout en ne touchant plus la tablette.

Pour la bidirectionalité, il faut bien utiliser Send on Port pour envoyer les données du plugin à la tablette ?
Est ce que le numéro de port d’entrée et de réception de la source doit être obligatoirement différent ?

Si j’utilise le même port pour l’entrée / sortie, par exemple 8000, avec les 2 cases Receive and Send cochées, la bi-directionalité fonctionne bien des 2 côtés. Mais malheureusement le moteur physique s’arrête dès que je ne touche plus la tablette.

Si je décoche Send Port, je ne peux plus contrôler le Lemur via le plugin, mais je les données générées par la tablette contrôlent bien le plugin, même quand je ne touche plus la tablette.
Donc, pour l’instant, pour moi, il faut choisir entre la bi-directionalité et le moteur physique (quand on ne touche plus la tablette), en cochant ou décochant send on Port IP.

Si l’on doit utiliser des ports différents, cela se complexifie et je t’écrirai directement.

**Comment by Xon77** [comment]
Excuse moi, Olivier, le N° de port de sortie dépend de l'application (Lemur), mais je ne vois toujours pas comment et si on peut utiliser simultanément la bidirectionalité et le moteur physique, spécifique au Lemur, en fonction de ce que j'ai dit précédemment.

**Comment by Xon77** [comment]
Peut-on actuellement contrôler la bidirectionalité de plusieurs plugins en même temps (plusieurs sources 1) ?
car, dans ce cas, il faudrait des adresses différentes pour chaque plugin ou source 1 ?
et pour l'instant, il n'y en a qu'une : /controlgris/traj/1/xyz
Désolé de toutes ces questions, j'essaie de comprendre le fonctionnement, les possibilités et limites de la bidirectionalité.

**Comment by Normandeau** [comment]
V106
La bidirectionnalité dans Open Stage Control fonctionne très bien.

**Comment by Normandeau** [comment]
Sauf Source Link et Source Link Alt

**Comment by belangeo** [comment]
> il faudrait des adresses différentes pour chaque plugin ou source 1 ?

En effet, il faudrait qu'un ID unique soit associé à chaque instance du plugin et que cet ID apparaisse dans les adresses OSC. Ex:

- /controlgris/1/traj/1/x value
- /controlgris/1/azispan value

Une possibilité serait d'utiliser la valeur de "First Source ID", qui doit être différente pour chacune des instances du plugin dans une session ?

Par contre, ça implique que l'utilisateur doit modifier toutes les adresses d'envoie (et de réception) dans une patch Open Stage Control (ou peu importe le soft utilisé pour le contrôle)... C'est moins drôle ça.

**Comment by Xon77** [comment]
Mon patch originel dans le Lemur pouvait contrôler jusqu'à 8 plugins attribuées aux adresses à partir de 8000. 
Veut-on contrôler l'écriture de plusieurs plugins en même temps ? 
car sinon, je vais le simplifier pour le contrôle d'un seul plugin, puisque la bidirectionalté n'est pas accessible pour plus d'un plugin ?

**Comment by belangeo** [comment]
Mmm... En effet, les ports de réception et d'envoie constituent l'ID unique par instance du plugin! Où est alors le problème avec la bidirectionalité pour plus d'un plugin?

**Comment by Xon77** [comment]
Chaque application (Lemur, Open Stage...) a ses propres structures.
Par exemple, les "1" dans l'adresse me posent quelques problèmes pour le Lemur et suis obligé un adressage spécifique, car un objet dans le Lemur ne peut se nommer "1", mais au moins "_1"....
Pour la bi-directionalité, j'ai dû donc changer la structure et utilise actuellement : /controlgris/1/traj/1/x value...
Lorsque que j'avais essayé des ports réception et d'envoi uniques, j'avais eu des problèmes. Je vais réessayer.

**Comment by NicolaGiannini** [comment]
V107 
Avec Open Stage Control je peux contrôler aussi Source Link et Source Link Alt.

**Comment by Xon77** [comment]
V109 & Reaper : 
Je le place ici car il s'agit d'un très léger problème concernant la bi-directionalité, qui a lieu aussi bien dans Open Stage Control que dans le Lemur : 
L'élévation de la source 1 n'est pas mis à jour dans les contrôleurs externes, lorsqu'on modifie dans le plugin le Source Link Alt, notamment quand on utilise Linear Min ou Linear Max.

**Comment by Normandeau** [comment]
DP
Même comportement dans OpStaCon. Seul Delta Lock remet l'élévation de la source 1 à la bonne place sur le iPad en bidirectionalité. Du côté de Azimuth-Distance, la source 1 est toujours à la même place dans tous les modes, donc elle n'en change pas. Sauf avec Delta Lock où elle est remplacée par le X qui se place automatiquement au centre. Et sa position est bel et bien ajustée dans le iPad. De même lorsqu'on revient avec un des autres modes.

**Comment by NicolaGiannini** [comment]
Je confirme que en Logic "L'élévation de la source 1 n'est pas mis à jour dans les contrôleurs externes, lorsqu'on modifie dans le plugin le Source Link Alt, notamment quand on utilise Linear Min ou Linear Max."

**Comment by Normandeau** [comment]
V110
Réglé
