### ISSUE TITLE
Sans utiliser les presets, la source 1 ne revient pas à sa position initiale

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#81]
v105
Je mets ControlGRIS sur une piste.
Je mets le séquenceur en mode enregistrement.
J'appuie sur play
Je laisse passer quelques secondes
J'enregistre une automation
J'appuie sur Stop.
Je déplace la tête de lecture au début de la séquence
La source 1 ne revient pas à sa position initiale.
La source se mette à la bonne place seulement quand l'automation commence. 
Testé avec Logic et Reaper, je crois lié au issue https://github.com/GRIS-UdeM/ControlGris/issues/77

Voir la vidéo

https://www.dropbox.com/s/5b2exb1p8wxdham/source1b.mov?dl=0

Petite note, dans mon cas en Logic une automation "position preset" à 0 est crée, tandis que en Reaper non. 

Petite note 2: je ne sais pas si c'est connecté, mais quand je bouge ma tête de lecture (sans être en play) les plugins normalement mettent à jour les paramètres suite aux automations, ControlGRIS ne le fait pas toujours.

**Comment by Normandeau** [comment]
DP
Je pensais que c'était une fatalité. Mais en fait je viens de faire toute une série de tests avec toutes sortes de plugiciels fabriqués par différentes compagnies, et ils sont tous le même comportement: lorsque la séquence est remise au début, ils remettent tous les pendules à l'heure (valeurs de départ). Sauf ControGRIS.
De plus, lorsqu'on place le curseur n'importe dans la séquence, lorsqu'on s'arrête, tous les plugiciels testés mettent à jour leurs valeurs, même SpatGRIS (le plugiciel). Sauf ControlGRIS.
Il y a certainement place à l'amélioration.

**Comment by Normandeau** [comment]
V106
Réglé.
