### ISSUE TITLE
Comportement figé des presets: Azim-Dist vs Elev

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#83]
V106
Le comportement des presets est étrange et se comporte comme si l'élévation ne s'enregistre plus.
Je fabrique deux presets, que je charge ensuite (Load) l'un après l'autre.

Preset 1:
![Capture d’écran, le 2020-03-11 à 10 27 33](https://user-images.githubusercontent.com/8959779/76428176-b5316400-6383-11ea-964e-463484a638c2.jpg)

Preset 2
![Capture d’écran, le 2020-03-11 à 10 28 13](https://user-images.githubusercontent.com/8959779/76428198-bb274500-6383-11ea-878c-8ddda67b7e4d.jpg)

Lorsque je reviens sur le Preset 1, la position Azimuth-Distance est la bonne, mais l'Elevation est celle du preset 2:
![Preset 1 après rappel](https://user-images.githubusercontent.com/8959779/76428563-3557c980-6384-11ea-977e-675929231997.jpg)

L'Elevation sera la bonne seulement si je démarre le séquenceur. Mais elle reviendra à la valeur du preset 2, dès que je l'arrête. Comme si une automation était enregistrée, ce qui n'est pas le cas.
La section Azimuth-Distance a aussi un autre comportement étrange. À l'arrêt, après un rappel de preset, on ne peut pas bouger la source, elle revient toujours à la position enregistrée du preset. Ce n'est pas le cas avec l'Elevation.
Petit film:
https://www.dropbox.com/s/5lp37argj145s2g/Comportement%20des%20presets.mov?dl=0

**Comment by belangeo** [comment]
J'arrive à reproduire le premier bug (élévation qui ne répond pas instantanément aux presets).

Pour le deuxième comportement, ça me semble être le cas où la session est en mode "read" et qu'il y a une automation sur la séquence. Tu bouges la source 1 et ensuite elle reprend la position que l'automation lui indique. Normalement, en passant en mode "latch", la source devrait rester où tu l'a déplacée. Ce comportement vient de la correction de l'issue #81, où la source 1 doit suivre l'automation, même lorsque la séquence est à stop...

**Comment by Normandeau** [comment]
L'automation est effectivement en mode Read mais il n'y a pas d'automation enregistrée. En fait, j'ai enregistré de l'automation sur cette piste, mais j'ai tout effacé. Et là je rejoue la même séquence et ça fonctionne sans problème. J'ajoute que je modifie les paramètres avec Open Stage Control. Est-ce que c'est cela qui perturbe le fonctionnement?
Il me reste à investiguer cela de manière plus systématique.

**Comment by belangeo** [comment]
J'investigue en ce moment même...

**Comment by Normandeau** [comment]
Il semble que ce soit seulement lorsque j'active le ControlGRIS à partir de Open Stage Control que les deux situations apparaissent. Les options Source Link et Source Link Alt sont déterminantes à cet égard. Lorsque je les change, c'est à ce moment-là qu'on se retrouve avec une situation de sources gelées. Si je reprend la main directement dans le ControlGRIS, ça rétablit le comportement presque normal.
Si je désactive Open Stage Control dans ControlGRIS, alors il se comporte normalement. Et si je réactive Open Stage Control, tout revient à la normale... enfin presque. Il reste parfois des scories. Si je ferme la fenêtre de ControlGRIS après avoir désactivé Open Stage Control, et que je la rouvre, là tout redevient normal, même la position des Elevation dans les Presets.
En résumé, la séquence pour reproduire la situation est la suivante:
• Ouvrir ControGRIS
• L’assujettir à Open Stage Control
• Changer de preset
• Changer un Source Link ou un Source Link Alt
• Bouger le source 1
Je remarque une chose: les Source Link et Source Link Alt ne sont pas bidirectionnels. Le iPad n'est pas informé par ControGRIS des changements apportés dans celui-ci? Se peut-il qu'il y ait conflit entre les deux? D'où l'hésitation ou le flicking qu'on voit dans le vidéo?

**Comment by belangeo** [comment]
Je n'arrive pas à reproduire après les changements que j'ai fait hier... À vérifier si c'est réglé avec la prochaine version.

**Comment by Normandeau** [comment]
V107
Les deux problèmes semblent réglés.

**Comment by NicolaGiannini** [comment]
même dans mon cas, problèmes réglés.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno ven 13 mar 2020 alle ore 11:28 Robert Normandeau <
notifications@github.com> ha scritto:
