### ISSUE TITLE
Receive on port: Source? Ou adresse manuelle?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#84]
V107
Il y avait un text box dans Controllers nommé Source dans la version précédente qui était inactive et qui a disparue. Mais je me retrouve dans une situation où elle serait sans doute utile.
La situation:
• J'ai une console Artist Mix branchée avec un câble ethernet sur le Mac dont je me sers pour le mixage (protocole Eucon);
• J'ai un iPad que je veux utiliser sur un réseau wifi local avec Open Stage Control pour activer ControlGRIS.
• ControlGRIS détecte automatiquement le réseau du Mac et l'indique dans Receive on port, mais priorise l'adresse du câble ethernet au détriment du wifi. Donc je ne peux pas utiliser en même temps un appareil sur RJ-45 et un autre en wifi. En effet, cette adresse est statique, on ne peut pas la modifier manuellement.

Est-ce que l'option Source serait ici une solution? Où l'on pourrait assigner l'adresse du wifi à Receive on port dans ControlGRIS?
Ou remplacer la détection automatique de Receive on port au profit de l'écriture manuelle du réseau souhaité (comme dans le Send on port)?

**Comment by belangeo** [comment]
Je ne voyais pas à quoi pouvait servir ce menu mais on semble bien avoir ici un beau cas de figure!

**Comment by NicolaGiannini** [comment]
V108, je crois que on peut pas toujours changer le "receive on port" , si jamais on voudrait le éditer.

**Comment by belangeo** [comment]
Il n'y a aucun moyen en JUCE de changer l'adresse IP de réception (pour le cas où le wifi et un câble serait branché). Je suppose qu'il y a une hiérarchie qui est définie au niveau de l'OS et que JUCE regarde les messages entrant sur les ports de l'adresse IP en priorité.

La boîte « Receive on port » n'est qu'une indication de l'adresse IP de la machine afin de ne pas avoir à la chercher lorsque l'on configure un contrôleur. Dans l'état actuel des choses, il n'y a aucune raison de l'éditer puisque c'est une valeur fixe.

**Comment by Normandeau** [comment]
Revoir mon commentaire plus haut où on a une machine branché en ethernet et un patch OpStaCon en wifi. On ne peut pas utiliser ce dernier, car ControlGRIS reçoit en priorité le IP du port ethernet. Si Olivier dit que ce n'est pas possible de modifier l'adresse de réception, ni de mettre un text box nommé Source, où on aurait la possibilité de lire les adresses IP qui sont actives, comme c'était le cas avant, voici la manière de contourner le problème que je mettrai dans le manuel. 
Il faut désactiver le port ethernet, activer le wifi et activer la communication IP dans ControlGRIS. L'adresse IP du wifi reste ainsi bloquée. Puis activer le port ethernet et charger le contrôleur ethernet (Eucon ici).
Malheureusement cette solution ne fonctionne qu'une fois. Si je ferme la communication IP du ControlGRIS, afin d'en ouvrir un autre, ce dernier reprend automatique l'adresse IP du réseau ethernet...

**Comment by Normandeau** [comment]
V109
Mis dans la manuel.
