### ISSUE TITLE
Ajout de Symmétric X et Y dans Open Stage Control

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#85]
V107
Added SYMMETRIC_X and SYMMETRIC_Y in source link popup menu
Yeah!
Possible de les ajouter dans le patch Open Stage Control?

**Comment by belangeo** [comment]
Déjà fait!

https://github.com/GRIS-UdeM/ControlGris/find/master

Click droit sur ControlGrisOSC.json et "Save link as..."

**Comment by Normandeau** [comment]
Message d'erreur:
![Capture d’écran, le 2020-03-13 à 09 50 41](https://user-images.githubusercontent.com/8959779/76626850-49303680-6510-11ea-8b4b-11bc7de6c987.jpg)

**Comment by belangeo** [comment]
Oups, le download corrompt le fichier... Je te l'envoie par courriel.

**Comment by belangeo** [comment]
Le voilà!

**Comment by Normandeau** [comment]
Oups! Rien d'attaché...

**Comment by belangeo** [comment]
Ho, dans tes courriels!

**Comment by Normandeau** [comment]
Done!
