### ISSUE TITLE
Commentaires graphiques (deux)

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#86]
V107
Lorsqu'on rapetisse les dimensions de ControlGRIS au minimum, ce serait bien qu'on conserve la fenêtre x-y au complet. Actuellement, les presets viennent «manger» de l'espace:

![Capture d’écran, le 2020-03-13 à 13 33 21](https://user-images.githubusercontent.com/8959779/76645630-c323e800-652f-11ea-8e9d-ccc218f13e54.jpg)

**Comment by Normandeau** [comment]
Deuxième commentaire graphique
Il n'y aucune barre de défilement dans le ControlGRIS (contrairement au SpatGRIS2) qui s'affiche quand on rapetisse les dimensions du plugiciel. Quand on a beaucoup de ControGRIS ouverts, on doit redimensionner ou repositionner fréquemment les données, alors ce serait apprécié.

**Comment by belangeo** [comment]
> Lorsqu'on rapetisse les dimensions de ControlGRIS au minimum, ce serait bien qu'on conserve la fenêtre x-y au complet.

Ha... C'est ce qui était implémenté... Avant d'ajouter les presets!

**Comment by Normandeau** [comment]
Exact... C'est que je fais une première tentative de remplacer les SpatGrIS1 par ds ControlGRIS dans un projet qui contient 24 instances stéréo, alors j'ai besoin d'être efficace sur le plan de l'espace occupé par les fenêtres!

**Comment by NicolaGiannini** [comment]
Je suis d'accord, et dans le mode CUBE on peut perdre toute la fenêtre
Elevation.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno ven 13 mar 2020 alle ore 13:37 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
Pour les barres de défilement, c'est peut-être pas urgent. Après vérification, il n'y en avait pas non plus dans SpatGRIS1.

**Comment by Xon77** [comment]
V108 Reaper
En rétrécissant le plugin, la fenêtre x-y reste au complet et n'est plus masquée par les presets.

**Comment by NicolaGiannini** [comment]
V108 Logic,
Je confirme, la fenêtre Azimut - Distance reste au complet et n'est plus masquée par les presets.
