### ISSUE TITLE
Dampening: observation, question et bogue

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#88]
V107
• Question: pourquoi le dampening est-il exclusivement réservé à Back & Forth?
Il faudrait d'ailleurs mettre back & forth en majuscules, comme le reste.
Si c'est une vrai amortisement, il pourrait aussi fonctionner en mode CW et CCW. D'ailleurs cela ouvre la porte à une fonction dont on a parlé fréquemment. Pourquoi ne pas mettre plutôt une fonction Accel/Ralen avec des valeurs positives et négatives.

**Comment by Normandeau** [comment]
• Est-ce que c'est vraiment cela que tu avais en tête (ce qu'on voit dans le film)?
Jusqu'à présent, le seul dampening qu'on avait était associé au pendule. Cela correspondait à un amortissement calqué sur la réalité. Alors qu'ici, c'est plutôt difficile à saisir. On voit que la trajectoire initiale est raccourcie et tronquée, mais sur le plan de la vitesse, alors qu'on s'attend à un ralentissement progressif, on a plutôt des a-coups, des changements brusques, plutôt associés à des rebonds qu'à un amortissement:
https://www.dropbox.com/s/rim1es16xva68tp/Dampening%20Square.mov?dl=0

**Comment by NicolaGiannini** [comment]
En ce qui concerne la fonction pendule, si nous prenons l'exemple du SpatGRIS 1, nous voyons qu'à la fin de chaque oscillation, la vitesse diminue, tandis que lorsque le mouvement reprend, la vitesse augmente progressivement. 

Dans le ControlGRIS, surtout dans les derniers d'oscillations, nous voyons que lorsque le mouvement recommence, il décélère au lieu d'accélérer progressivement, et comme Robert dit, il semble un rebond.

**Comment by Normandeau** [comment]
Drawing, Shift, Back & Forth (simulation de pendule)
La valeur temporelle du Dampening est difficilement prévisible.
Si je met une trajectoire de 4 sec(s), et un dampening de 4 (Number of cycles dampening), ce qui devrait correspondre à 16 sec(s), je n'obtiens que 8 sec(s) d'amortissement (parfois moins selon le DAW). De plus, comme illustré ici dans Logic, il est impossible de prévoir à quel endroit la Source 1 va se positionner au début de la trajectoire (il n'y a aucune automation enregistrée ici, c'est live):

https://www.dropbox.com/s/zx7sdkiyiw053ob/%20Dampening%20Logic%208s%20au%20lieu%20de%2016s.mov?dl=0

**Comment by belangeo** [comment]
> De plus, comme illustré ici dans Logic, il est impossible de prévoir à quel endroit la Source 1 va se positionner au début de la trajectoire

Ce problème est réglé.

**Comment by NicolaGiannini** [comment]
En ce qui concerne la simulation du pendulum, afin de obtenir une chose semblable a ce que on peut faire avec SpatGRIS (v1), la vitesse devrait se réduire quand la source est proche des extrémités du mouvement, et augmenter quand est loin ? N’est pas? 

Maintenant avec ControlGRIS est possible de raccourcir progressivement la trajectoire, qui est quelque chose de nouveau et d'intéressant, mais je donnerais la possibilité d’avoir aussi le même comportement de SpatGRIS.
Voir la vidéo
https://www.dropbox.com/s/7gmjsxfm59fn884/pendulum.mov?dl=0

Petite note: Parfois comme vous pouvez voir à 0:23 il y a de glitches dans le back & fort.

**Comment by Normandeau** [comment]
En fait, le mouvement d'un pendule, dans la réalité physique, est une vitesse constante. Par contre, ce qui change, c'est l'amplitude du mouvement car la gravité (ou l'inertie) ralentit progressivement le processus. Le pendule se déplace toujours à la même vitesse, mais de moins en moins loin. Pour voir la différence, il aurait fallu que tu ajoutes le dampening dans SpatGRIS 1.
C'est ce que j'aimerais que le mouvement de pendule reproduise ici.

**Comment by NicolaGiannini** [comment]
V108
Je pense que maintenant le problème soit réglé, mais je laisse à Robert de le confirmer.

**Comment by Normandeau** [comment]
V108
Oui le comportement étrange du dampening semble réglé.
Mais je reviens à la première question: pourquoi le dampening est-il exclusivement réservé à Back & Forth? Si c'est un vrai amortisement, il pourrait  fonctionner aussi bien en mode CW qu'en mode CCW. La réponse à cela (peut-être): c'est qu'on a toutes les trajectoires en mode CW et CCW. Donc si on veut du dampening en mode CW on n'a qu'à se mettre sur CCW et utiliser Back & Forth, right?
Mais n'est-ce pas un peu tordu comme logique? Il faut donc faire de la double négation pour arriver à quelque chose de simple... Je fais comment pour expliquer cela dans le manuel?
Reste le cas de Drawing qui est particulier. Je vais ouvrir une autre issue..

**Comment by Normandeau** [comment]
DP10, Mode CUBE, Octo ou stereo, Back & Forth
La durée du Dampening est encore difficile à saisir. Si je comprends bien, l’amortissement se réalisera au cours d'un certain nombre de cycles (Number of cycles dampening). Donc si je mets 4 et que le cycle dure 6 secondes, je devrais avoir un amortissement au bout de 4 x 6 = 24 secondes, exact? Or cela en prend 36.
Autre exemple ici: 2 x 8 = 16. Cela en prend 18. De plus ça jumpe toujours au début:

![Dampening Jump et durée](https://user-images.githubusercontent.com/8959779/77318237-21488c00-6ce3-11ea-9401-8d87e05f0b77.jpg)

Reaper 6, CUBE, Stereo, Back & Forth
Dampening 3, Cycle 10. Résultat: 45 sec. Et ça jumpe aussi au début:

**Comment by Normandeau** [comment]
V109
Le jump du début est réglé et la durée du dampening fait l'objet d'une autre issue #89 
Donc je ferme celle-ci pour éviter les doublons.
