### ISSUE TITLE
Dampening x duration: valeur globale erronée

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#89]
V107
Fonction Dampening, Automation en mode Latch
• Dans Reaper ça fonctionne.
• Dans DP, la trajectoire est faite en un temps record et seulement en partie puis ça s'arrête:
https://www.dropbox.com/s/aoyk4af1deaok6x/%20Dampening%20DP.mov?dl=0
• Dans Logic, la source se place n'importe où au départ, et la trajectoire n'est que partiellement réalisée:
https://www.dropbox.com/s/6ne655wvuapof4g/%20Dampening%20Logic.mov?dl=0

**Comment by Normandeau** [comment]
Dans Logic on voit aussi dans la vidéo que la source 1 disparaît de la fenêtre Azimuth-Distance. Elle réapparaît soit lorsqu'on touche la source 1 dans la fenêtre Elevation, soit lorsqu'on appuie sur Activate.

**Comment by NicolaGiannini** [comment]
Je confirme que dans mon cas en Logic la source se place n'importe où au
départ.
Nicola Giannini
+1 514 550 3856
nicolagiannini.com <http://www.nicolagiannini.com/>


Il giorno lun 16 mar 2020 alle ore 10:33 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by NicolaGiannini** [comment]
Dans Logic le problème se pose en playback, si Activate est appuyé quand le séquenceur est déjà en play, ou si on se déplace sur la timeline, sans positionner la source avant d’appuyer sur play. 

Si on appuie Activate avant d’appuyer play, le comportement est correct.
Si on appuie Activate après avoir appuyé sur Play  la source ne part pas de la bonne place.
Si on se déplace sur la timeline il faut  positionner la source en la touchant, sinon la source ne commence pas le mouvement du bon endroit, 
Voir la vidéo
https://www.dropbox.com/s/ysh7ku1qatv4yqp/activate2h.mov?dl=0

**Comment by belangeo** [comment]
Appuyer sur le bouton Activate initialise la source virtuelle automatisable en fonction de la trajectoire dessinée. Si vous appuyez sur ce bouton pendant que le sequenceur en en train de jouer, l'initialisation aura lieu là où le pointeur est rendu dans le timeline... 

> Si on appuie Activate après avoir appuyé sur Play la source ne part pas de la bonne place.

Je ne comprend pas ce que l'on entend par « bonne place » ici. La source part bien du point de départ de la trajectoire. 

> Si on se déplace sur la timeline il faut positionner la source en la touchant, sinon la source ne commence pas le mouvement du bon endroit

La lecture des trajectoires est fonction du temps écoulé entre la valeur de temps au point d'arrêt et la valeur de temps courante lorsqu'en marche. Aucun DAW ne gère le temps de la même façon (certains se mettent constamment à jour comme Reaper et d'autres mettent la valeur de temps à jour seulement lorsqu'en mode play). La façon la plus sûre de gérer une trajectoire est de positionner le curseur au bon endroit en premier, et ensuite d'ajuster la trajecoire.

**Comment by NicolaGiannini** [comment]
"Si vous appuyez sur ce bouton pendant que le sequenceur en en train de jouer, l'initialisation aura lieu là où le pointeur est rendu dans le timeline." Je voulais dir ça. On pourrait donc l'indiquer dans le manuel. 

" La façon la plus sûre de gérer une trajectoire est de positionner le curseur au bon endroit en premier, et ensuite d'ajuster la trajecoire." Je mettrai aussi cela dans le manuel.

**Comment by Normandeau** [comment]
V109
CUBE, différentes trajectoires.
L'écriture se passe bien maintenant pour le Dampening. Mais la durée n'est toujours pas la bonne.
Je fais une trajectoire circulaire de 6 secondes et un dampening de 4 cycles. Cela devrait donner 24 secondes. En fait, cela en prend 36. Même résultat avec 12 et 2. Devrait être 24, donne 36.
Testé dans DP, Logic et Reaper: mêmes résultats.

**Comment by belangeo** [comment]
La durée totale, en back-and-forth, correspond à la durée d'un cycle multipliée par le nombre de cycles x 2 (une fois aller et un efois retour). Lorsque le dampening est activé (plus grand que 0), l'accélération en fin de parcours réduit la durée totale, qui devient durée d'un cycle multiplié par le nombre de cycles x 1.5.

**Comment by Normandeau** [comment]
Vive les maths! Je mets cela dans le manuel.
