### ISSUE TITLE
Les trajectoires fonctionnent mal en mono dans DP en enregistrement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#90]
V107
Automation en mode Latch
En mode Play les trajectoires fonctionnent comme prévu.
En mode d'écriture de l'automation, cela ne fonctionne plus. Seule une petite partie de la trajectoire est jouée et elle est répétée rapidement en boucle (illustration en mode Square ici, mais le comportement est le même pour toutes):
https://www.dropbox.com/s/0t36wb223ozhqvw/Square%20DP.mov?dl=0

**Comment by Normandeau** [comment]
Même constat avec le mode Drawing dans lequel j'ai testé la méthode Shift. En mode Play ça fonctionne mais en mode record, ça ne joue qu'une partie de la trajectoire en boucle.

**Comment by Normandeau** [comment]
Drawing dans Logic
La trajectoire enregistrée en Latch ne correspond pas à celle dessinée en mode Drawing-Shift:

https://www.dropbox.com/s/iuzqa7f3uju6zd7/Drawing%20Logic.mov?dl=0

**Comment by belangeo** [comment]
Je n'arrive pas à reproduire... Possible que le fix pour l'issue #89 est aussi réglé ce problème. À valider...

**Comment by Normandeau** [comment]
Aujourd'hui, les trajectoires fonctionnent bien dans DP et Logic!!!
En fait, un peu par hasard, je me rends compte que ce qui ne fonctionne pas, c'est lorsqu'on travaille avec une piste mono. En stéréo et en octo, ça fonctionne très bien. Seuls DP et Logic permettent des pistes mono (Live et Reaper ne le peuvent pas).

**Comment by NicolaGiannini** [comment]
Dans mon cas avec Logic et ControlGRIS en mono, je n’arrive pas à reproduire le problème 
https://www.dropbox.com/s/vg8lya86xbu0wiy/drawing%20mono.mov?dl=0
on va voir si cela se reproduit!

**Comment by Normandeau** [comment]
V108
Enregistrement d'une trajectoire automatique, Square CCW en mono avec Back & Forth et Dampening..

Ça fonctionne bien en mono dans Logic Mono Square CCW Cycle 6 Damp 2 Pas de Preset 0. Par de jump:

![Logic Mono Square CCW Cycle 6 Damp 2 Pas de Preset 0](https://user-images.githubusercontent.com/8959779/77324542-493ced00-6ced-11ea-87f6-c77e4b321614.jpg)

Dans DP en mono avec les mêmes réglages DP Mono Square Cycle 6 Damp 2 Preset 0. On remarquera que le Preset 0 s'écrit ici. C'est le seul cas de figure où un Preset 0 s'écrit. Que ce soit dans DP, Logic ou Reaper, en mono, en stéréo ou en octo, seul DP en mono écrit un Preset 0. Est-ce que c'est cela qui interdit l'écriture de l'automation?:

![DP Mono Square Cycle 6 Damp 2 Preset 0](https://user-images.githubusercontent.com/8959779/77325185-40005000-6cee-11ea-86ed-9ca3a7f05218.jpg)

Sinon, en stéréo, DP jump au début:
![DP Jump](https://user-images.githubusercontent.com/8959779/77325006-f283e300-6ced-11ea-8db8-fa790fc52bf0.jpg)

Comme Reaper:
![Reaper Jump](https://user-images.githubusercontent.com/8959779/77325040-00d1ff00-6cee-11ea-9b85-4a02054b1b4c.jpg)

**Comment by belangeo** [comment]
Je n'arrive pas à reproduire le problème avec DP en mono... Par contre, le saut en stéréo est causé par DP qui appelle plusieurs fois la fonction prepareToPlay (dans laquelle certaines initialisations sont effectuées), dont quelques-unes alors que la séquence est en marche. Ce problème est réglé.

**Comment by Normandeau** [comment]
V109
Cela semble réglé. Fait plusieurs tests. Il ne faut vraiment pas essayer avec une ancienne séquence de DP. Mais en créant une séquence vierge, ça fonctionne. Pas de saut, pas de preset 0, trajectoires en B&F et Dampening efficace. Je ferme cela et on se croise les doigts!
