### ISSUE TITLE
Autre commentaire graphique: check √ pas bidirectionnel

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#91]
V107 en relation avec Open Stage Control
Ce n'est pas un commentaire qui demande une attention urgente, mais j'aimerais tout de même le signaler. En fait, je n'avais jamais remarqué que dans ControlGRIS (comme SpatGRIS avant), tous les menus déroulants (Source Link, Trajectory, Sec/Beat) s'affichent avec un check √ à côté de l'option choisie. C'est un pléonasme, dans la mesure où l'option choisie est celle qui est affichée. Là où ça pose problème c'est dans Open Sound Control. Les Source Link sont bidirectionnels mais pas le menu coché. Donc si on change le lien dans ControlGRIS, il change bien dans OSC mais le menu affiché n'est pas celui qui est coché dans la liste. Cela peut induire de la confusion.
• Question donc: est-ce que le check √ est nécessaire, autant dans ControlGRIS que dans OSC?

![Capture d’écran, le 2020-03-18 à 12 26 17](https://user-images.githubusercontent.com/8959779/76984344-1671ae00-6915-11ea-9700-89276efdfc01.jpg)

**Comment by belangeo** [comment]
Je ne peux parler pour OSC... Dans le cas du ControlGris, c'est très simple alors j'ai retiré le crochet de sélection.

**Comment by Normandeau** [comment]
Ok. Bon hasard, Jean-Emmanuel Doucet, le créateur de OSC m'a écrit aujourd'hui, pour me dire qu'il avait appris que nous l'utilisions avec le ControlGRIS. Il est venu à la fac il y a quelques années. Donc je pourrai lui poser directement la question!

**Comment by belangeo** [comment]
Oui, j'ai aussi reçu son courriel. Je me souviens bien de Jean-Emmanuel, il était bon dans mes cours!

**Comment by Normandeau** [comment]
V108
Check mark enlevé et synchronisation corrigé dans OpStaCon 0.49.12
