### ISSUE TITLE
Dimension de l'espace de travail: relation avec la dimension de la fenêtre

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#92]
Nicola a écrit:
Je me demandais s'il ne serait pas plus pratique que la taille de la trajectoire soit redimensionné en fonction de la dimension de la fenêtre. Par exemple, si je trace une trajectoire dans une fenêtre qui a été agrandie précédemment, cette trajectoire sort de la fenêtre.

**Comment by Normandeau** [comment]
C'est une bonne question, mais je ne mettrais pas cela en mode priorité.
Pour une raison très simple: la trajectoire en mode Drawing  est destinée à une vie éphémère. En effet, on la dessine, on la valide, puis on enregistre l'automation dans le DAW. Et on l'efface. Toutes ces opérations peuvent se faire avec une fenêtre qui ne change pas de dimensions, non?

**Comment by Normandeau** [comment]
Par contre ce que cela met en valeur, c'est toute une série de problèmes graphiques quand on redimensionne la fenêtre de ControlGRIS (testé ici dans DP10).

• Pas de sources dans Azimuth-Distance:
![Pas de sources](https://user-images.githubusercontent.com/8959779/77010787-e17b5080-6940-11ea-939e-6c3e74ea6986.jpg)

• Square au lieu de Circle:
![Square au lieu de Circle](https://user-images.githubusercontent.com/8959779/77010830-f22bc680-6940-11ea-90df-8bb9c70940b9.jpg)

• Et le petit carré qui ne se remet pas en place:
![Petit carré vs fenêtre](https://user-images.githubusercontent.com/8959779/77010937-2bfccd00-6941-11ea-9bd2-66b0de8f2f37.jpg)

**Comment by NicolaGiannini** [comment]
ça semble réglé !

**Comment by Normandeau** [comment]
V108
Réglé
