### ISSUE TITLE
OSC format

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#93]
Vraiment un petit détail, mais il faudrait mettre “SpatGRIS” à la place de “ServerGRIS” dans les deux modes dans l'onglet OSC Format. 
![osc-format](https://user-images.githubusercontent.com/35705913/77207143-000f5200-6acf-11ea-984a-d060e09728c7.jpeg)

**Comment by belangeo** [comment]
Done!

**Comment by Normandeau** [comment]
V109
Réglé
