### ISSUE TITLE
Drawing et Back & Forth

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#94]
V108
Pour compléter le commentaire de l'issue #88 je fais une nouvelle issue au sujet de Drawing en mode dampening. Actuellement cet effet n'est disponible qu'en mode Back & Forth. Contrairement aux autres trajectoires qui existent en CW et en CCW, Drawing n'existe que dans le sens de sa création. Si on veut du dampening ici, il faut le faire fonctionner en Back & Forth. **Pourquoi du dampening seulement à l'envers?**
Dans le cas du Drawing, cela génère un comportement qui a l'air d'un bogue. Comme l'automation part dans le sens contraire, la source a toujours l'air mal placée parce qu'elle jumpe d'un coup de sa position «naturelle» de départ, à celle imposée par le Back & Forth. C'est très évident quand on simule un pendule en traçant une ligne droite avec Shift-Drawing. La source part toujours à l'autre bout de la droite par rapport à sa position initiale.

Je rapporte un échange qui a eu lieu du Google group mais pas ici.
Nicola a écrit:
Je me demande pourquoi le forth est avant le back. J'ai la tendance à penser qu'il serait peut-être plus intuitif d'avoir avant le "Forth" et après le "Back". 
Je dessine une trajectoire dans une certaine direction, et je m'attendrais, dans la version "doublée" à ce que le premier mouvement soit dans la direction de ce que j'ai dessiné. 

Robert:
Le Back & Forth est une expression en anglais qui veut dire aller-retour ou va-et-vient.
Comme tu l'observes très justement, Olivier l'a pris au sens littéral et effectivement on a plutôt du Retour-Aller ou du Vient-et-Va.
Je propose que ça soit plutôt de l'Aller-Retour.

**Comment by Normandeau** [comment]
Peut-être que plutôt que Back & Forth, on aurait tout simplement Return. Cela aurait le mérite de lever toute ambiguïté. La trajectoire commence dans le sens nommé par Cw ou CCW et revient su Return est cochée. Et elle est amortie ou pas.

**Comment by NicolaGiannini** [comment]
Je suis d'accord.

**Comment by belangeo** [comment]
> Dans le cas du Drawing, cela génère un comportement qui a l'air d'un bogue. Comme l'automation part dans le sens contraire, la source a toujours l'air mal placée parce qu'elle jumpe d'un coup de sa position «naturelle» de départ, à celle imposée par le Back & Forth. C'est très évident quand on simule un pendule en traçant une ligne droite avec Shift-Drawing. La source part toujours à l'autre bout de la droite par rapport à sa position initiale.

J'avoue que je ne vous suis pas sur cette discussion... D'abord, comme Robert l'a expliqué, « back & forth » c'est seulement une expression assez commune pour dire « aller - retour ». Ensuite, l'option back&forth fait bien un aller-retour, et non un retour-aller (enfin, pour tous les tests que je peux faire). Par exemple, en mode Circular CW, avec le back&forth activé, la source part bien dans le sens des aiguilles d'une montre et revient par la suite. Le contraire se produit bien en CCW... En mode Drawing, en effet, il n'y a pas la notion de CW ou CCW, la trajectoire existe telle qu'elle a été dessinée. Si on veut une ligne droite avec le départ en bas, il suffit simplement de dessiner la droite en partant d'en bas.

**Comment by Normandeau** [comment]
Étrange! Nicola l'a décrit très précisément et moi aussi. Je viens de vérifier dans Reaper, Logic et DP. Dans Reaper et Logic, le comportement est normal. Nicola: peux-tu revalider dans Logic? Il n'y a que dans DP que le back & Forth est inversé. J'ai aussi pensé que cela pouvait être dû à la version: AU pour DP et Logic et VST pour Reaper. J'ai testé les deux dans Reaper et ça fonctionne normalement...
Dans DP, j'ai à nouveau effacé la cache, créé une nouvelle session, mis un ControlGRIS «vierge», testé en mono, stéréo et octo, rien à faire: avec Back & Forth, ça part toujours à l'envers.
Juste au cas où vous penseriez que j'ai la berlue (ou le covid-19):
https://www.dropbox.com/s/tw70jgoc26juuno/DP%20Back%20%26%20Forth.mov?dl=0

**Comment by belangeo** [comment]
D'accord, je vais investiguer avec DP!

**Comment by NicolaGiannini** [comment]
J'ai testé avec Logic (au) et Reaper (au vst et vst3) et ça fonctionne bien!

**Comment by Normandeau** [comment]
V109
Réglé dans DP.

**Comment by NicolaGiannini** [comment]
Bonjour, 
je viens de constater ce comportement en Logic et en Reaper. 
Back & Forth  part à l'envers sur des pistes software instrument (souvent mais pas toujours)
Back & Forth fonctionne correctement avec des pistes audio. (souvent mais pas toujours)
voir la vidéo : https://www.dropbox.com/s/vv79kt3264thuya/backandfort.mov?dl=0
Robert tu peux voir si ça passe même à toi ?
Merci

**Comment by Normandeau** [comment]
Comportement vérifié avec Logic et DP
• Fully Fixed, Circle Clockwise, piste Instrument en Back & Forth
Cela a à voir avec Activate. 
- Dans DP, sur une piste instrument, comme il n'y a pas d'audio, le bouton Activate n'est pas mis à Off lorsque le séquenceur est arrêté. Ainsi, ControlGRIS reprend la séquence en route, là où elle s'est arrêté. Elle repart CW si le séquenceur s'est arrêté en CW, elle repart en CCW si le séquenceur s'est arrêté en CCW. 
- Dans Logic, c'est différent. Le bouton Activate se met à Off, mais en B&F la trajectoire repart toujours à l'envers.

• Fully Fixed, Circle Clockwise, piste audio en Back & Forth, piste instr. normale.
Les deux pistes partent toujours dans le bon sens.

**Comment by NicolaGiannini** [comment]
Dans Logic
En Circle Clockwise. Si je appuie sur Activate et après su play, la trajectoire repart à l'envers. Si je appuie sur play, et après su activate, la trajectoire repart dans le bon sens. Même comportement avec Fully Fixed et Circle Clockwise.

"Circular + Circular Clockwise" la trajectoire repart toujours dans le bon sens, mais "Circular + Circular Counter Clockwise" : la trajectoire repart à l'envers.

**Comment by Normandeau** [comment]
V110, DOME
• Logic Read; Piste audio; Toutes les Source Link Circular; Trajectory Clockwise; Activate et ensuite Play; Remise manuelle de la source 1 à la position de départ chaque fois; Normal ou B&F.
Toutes marchent dans le bon sens (CW).
Même chose dans DP et Reaper. Même chose en CUBE.

• Logic Read; Piste audio; Toutes les Source Link Circular; Trajectory Counter Clockwise; Activate et ensuite Play; Remise manuelle de la source 1 à la position de départ chaque fois; Normal ou B&F.
Toutes marchent à l'envers (CCW). Il y a une seule trajectoire qui ne fonctionne pas normalement, c'est Circle Counter Clockwise, qui part bien à l'envers, mais en faisant jumper la Source 1 de 180˚ au départ et cela avec tous les Source Link Circular.
Même chose dans DP et Reaper. Même chose en CUBE.

Conclusion: il semble que seule la trajectoire Circle Counter Clockwise soit défectueuse.
À confirmer systématiquement.

**Comment by SamuelBeland** [comment]
1.1.2

Confirmer si réglé.

**Comment by NicolaGiannini** [comment]
V112

Dans Logic avec Back & Forth sélectionné la trajectoire part :

1. dans le bon sens sur des pistes audio
2. à l'envers sur des pistes software instrument

Dans mon cas le phénomène se produit avec toutes les Source Link et les Trajectory Type.

Dans Reaper, apparement la trajectoire part toujours dans le bon sens, mais il y a un autre problème que je décris ici https://github.com/GRIS-UdeM/ControlGris/issues/115

**Comment by Normandeau** [comment]
V113
Dans DP, ça part toujours dans le bon sens(CW ou CCW), avec et sans Back & Forth. Sur une piste audio ou sur une piste instrument.

**Comment by NicolaGiannini** [comment]
V113
Dans Logic, j'ai toujours le même problème.

**Comment by NicolaGiannini** [comment]
V114
Dans Logic j'ai toujours le comportement, avec Back & Forth sélectionné la trajectoire part :

1. dans le bon sens sur des pistes audio
2. à l'envers sur des pistes software instrument

**Comment by Normandeau** [comment]
Et V115?

**Comment by NicolaGiannini** [comment]
V115, réglé dans Logic. (J'ai aussi fait la mise à jour de Logic, version 10.5.1)

**Comment by Normandeau** [comment]
V115
Réglé

**Comment by NicolaGiannini** [comment]
Je suis désolé, mais en faisant d’autres tests j’ai découvert qu’en réalité ce n’est pas réglé. 

De ce que je comprends, dans une piste midi la source se déplace dans le bon sens seulement si on suit les étapes suivantes : 

1 j’ajoute ControlGRIS à la piste
2 Je mets la Trajectory Type à Circle Clockwise
3 J’active Back and forth
4 J’active Activate OSC
5 J’appuie sur Activate
6 Je démarre la séquence

Résultat = la source bouge dans le bon sens, mais si je redémarre la séquence après l’étape 6 la source bouge à l’envers. Voir la vidéo : https://www.dropbox.com/s/2swpc7au6q1qaj3/Back-f1.mov?dl=0

Si je démarre la séquence après l’étape 1, la source bouge également à l’envers. Voir la vidéo : https://www.dropbox.com/s/2utqgp5u9v6gyvd/Back-f2.mov?dl=0 (au début de la vidéo, j’ajoute ControlGRIS à la piste)

**Comment by Normandeau** [comment]
V116
Coomportement normal dans DP et Logic. Semble réglé. Nicola pour Logic? Christophe pour Reaper?

**Comment by NicolaGiannini** [comment]
V116 Logic & Ableton Live

Dans mon cas, mon comportement est identique à celui de la version V115.
Pour résumer, si je démarre la séquence avant d'appuyer sur "Activate" la source bouge à l’envers.

Comme Robert n'a pas ce problème, il se peut que ce soit un problème de ma configuration.

Dans le détail :

1 J’ajoute ControlGRIS à la piste
2 Je mets la "Trajectory Type" à "Circle Clockwise"
3 J’active "Back and forth"
4 J’appuie sur "Activate"
5 Je démarre la séquence

Résultat = la source bouge dans le bon sens. Cependant si j'arrête la séquence et après je la redémarre, la source bouge à l’envers. J'ai fait une nouvelle vidéo :
https://www.dropbox.com/s/3sjodmldm5vxj0c/Back%20%26%20Forth1.mov?dl=0

Aussi si je démarre la séquence avant l'étape 4 (appuyer su "Activate"), la source bouge à l’envers.
Nouvelle vidéo : https://www.dropbox.com/s/r9t2s0ugxq08uo6/Back%20%26%20Forth2.mov?dl=0

J'ai testé les mêmes étapes dans Live 10 sur une piste Midi. Même dans Live, si je démarre la séquence avant d'appuyer sur "Activate" la source bouge à l’envers.

**Comment by NicolaGiannini** [comment]
V117
Dans Logic il semble réglé. 
Dans Ableton Live (version VST et AU), parfois la source bouge dans le bon sens, parfois pas. Cela se produit aussi dans des pistes audio. Je n'ai pas encore réussi à trouver une séquence d'actions qui produit toujours le même résultat. Mais j'ai noté que chaque fois qu’on appuie sur Play la source change de direction, voire la vidéo : 
https://www.dropbox.com/s/q7z6e0677twjpc3/LiveBackandForth-.mov?dl=0

Je continue à tester.

**Comment by Normandeau** [comment]
V118
Et avec celle-ci?

**Comment by NicolaGiannini** [comment]
V118
Logic 10.5.1

En ce qui concerne la piste midi j’ai le même comportement que j’avais dans V116, soit : 

> Pour résumer, si je démarre la séquence avant d'appuyer sur "Activate" la source bouge à l’envers.
> 
> Dans le détail :
> 
> 1 J’ajoute ControlGRIS à la piste
> 2 Je mets la "Trajectory Type" à "Circle Clockwise"
> 3 J’active "Back and forth"
> 4 J’appuie sur "Activate"
> 5 Je démarre la séquence
> 
> Résultat = la source bouge dans le bon sens. Cependant si j'arrête la séquence et après je la redémarre, la source bouge à l’envers.
> Aussi si je démarre la séquence avant l'étape 4 (appuyer sur « Activate »), la source bouge à l’envers.

J'ai fait un test simultanément avec une piste audio et une piste midi. J'ai obtenu le même résultat et j'ai réalisé une autre chose. Lorsque j'arrête la séquence, la source de la piste audio se positionne (incorrectement) exactement là où la source de la piste midi (qui bouge à l’envers) s'arrête.

En général, lorsque j'arrête la séquence, la source de la piste audio est positionnée là où elle serait si la source avait bougé en sens inverse.

Voir la vidéo.

https://www.dropbox.com/s/gjnrtbll0040hrs/backandforth.mov?dl=0
Dans la vidéo : 
de 00,00 à 00,39
Les sources se déplacent dans le bon sens, mais lorsque j'arrête la séquence, la source de la piste audio est positionnée incorrectement.

de 00,39 à 1,01
La source de la piste midi bouge à l'envers (parce que j'ai arrêté la séquence et après je l'ai redémarrée). Quand j'arrête la séquence on voit que la source de la piste audio est placée dans la même position que celle de la piste midi (position incorrecte, car la piste midi a bougé à l'envers).

**Comment by Normandeau** [comment]
V200RC2
DP11
Suite d'une très longue discussion de... 2020-21 au sujet du Back & Forth! Dans DP11 ça fonctionne comme prévu. Tests à faire dans les autres DAWs.

**Comment by Normandeau** [comment]
Je ferme cette rubrique car elle est trop longue — elle a démarré en 2020 — et comporte trop de rubriques. On y discute en effet de:
- Drawing
- Dampening
- Back & Forth
Qui sont trois sujets (presque) indépendants. Je démarre donc des issues nouvelles à ces sujets.
