### ISSUE TITLE
Pendule et Drawing

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#95]
V108
Je comprends qu'on peut simuler un pendule avec la combinaison Drawing-Shift. Et ce qui est bien c'est qu'on faire des pendules n'importe où dans l'espace et pas seulement en passant par le centre. On a aussi une fonction dampening qui reste à ajuster, voir issue #94 . Mais ça reste un pendule linéaire si je puis dire. En effet, une des caractéristiques du pendule que l'on a perdue par rapport au SpatGRIS, c'est la déviation, ajustée en angle. Les caractéristiques du pendule étaient donc:
- aller-retour
- dampening
- deviation

Voir ceci pour se rafraichir la mémoire:
https://www.dropbox.com/s/2yjjuy4xk5wtrtt/Pendule%20SpatGRIS1.mov?dl=0

**Comment by NicolaGiannini** [comment]
Je suis d’accord avec Robert. En comparant SpatGRIS et ControlGRIS on voit comme le fait d’avoir les trois fonctions "aller-retour", "dampening" et "deviation" permet d'avoir plus des possibilités de control et des trajectoires. 
Par exemple maintenant avec ControlGRIS c'est pas possible d'avoir un pendulum linéaire mais sans dampening, ou, comme l'indique bien Robert, on a plus la "deviation" que en fait c'est utile.

**Comment by Normandeau** [comment]
En y réfléchissant davantage, il me semble que toutes affaires cessantes, c'est au pendule qu'on devrait consacrer du temps. En effet, le pendule est la seule trajectoire «concrète» de ControlGRIS. C'est la seule qui est basée sur un modèle naturel et non pas sur une fonction mathématique abstraite, comme les cercles et autres carrés. Le pendule est donc notre première proposition d'aller de l'avant vers l'adoption de trajectoires concrètes. Bien que celui-ci ne soit pas encore générés par une analyse sonore, il n'en demeure pas moins qu'il est beaucoup plus facile de le relier à un comportement physique que pour les autres.
Je propose donc qu'on aille de l'avant avec une trajectoire distincte nommé Pendulum, avec ses trois caractéristiques nommées plus haut (celles du SpatGris 1 essentiellement). Et avec la possibilité de le placer n'importe où dans l'espace comme on peut le faire actuellement avec Drawing (une grosse amélioration par rapport à SpatGRIS 1 où on pouvait placer le End Point n'importe où dans l'espace mais ça ne marchait pas bien).
Possible?

**Comment by belangeo** [comment]
Ok, je crois bien que ça va le faire... J'ai ajouté un nouveau contrôle pour ajuster la déviation en degrés par cycle, applicable à n'importe quelle trajectoire (sauf REALTIME bien sûr). Avec une droite dessinée, le dampening et la déviation en degrés, vous pouvez faire pas mal toutes les variations sur le thème du pendule. Avec d'autres types de trajectoire, la déviation en degrés crée des mouvements assez funky!

**Comment by Normandeau** [comment]
V110
On peut maintenant fabriquer des pendules assez complexes et flexibles.
