### ISSUE TITLE
Modes circulaires avec Open Stage Control: problématiques

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#97]
V108
Mode CUBE, DP10, Open Stage Control 0.49.11
Sans toucher la Source 1
Sans Open Stage Control, passage de:
• Independent:
![Independent sans OSC](https://user-images.githubusercontent.com/8959779/77262095-cde62780-6c69-11ea-9038-dcb14f0d15eb.jpg)

• à Fully FIxed, tout à fait normal, toutes les sources se sont ajustées à la source 1:
![Fully Fixed sans OSC](https://user-images.githubusercontent.com/8959779/77262112-ec4c2300-6c69-11ea-941e-96dd8ad96066.jpg)

Avec Open Stage Control, passage de:
• Independent:
![Independent avec OSC](https://user-images.githubusercontent.com/8959779/77262152-48af4280-6c6a-11ea-8e74-c728f56dbeec.jpg)

• à Fully FIxed, un peu déséquilibré:
![Fully Fixed avec OSC](https://user-images.githubusercontent.com/8959779/77262166-72686980-6c6a-11ea-90c1-e41882d61922.jpg)

• Mais lorsque je déplace la Source 1 dans OSC, là ce n'est plus fixé entre la Source 1 et les autres qui sont restées solidaires entre elles:
![Source 1 à partir de OSC](https://user-images.githubusercontent.com/8959779/77262187-aba0d980-6c6a-11ea-840d-26f1290d4b9f.jpg)

• J'ai aussi le même genre de comportement étrange lorsque je suis en Fixed Radius par exemple ici:
![Fixed Radius avec OSC](https://user-images.githubusercontent.com/8959779/77262309-71840780-6c6b-11ea-8f71-4ca52e9566a1.jpg)

Pourriez-vous valider cela?

**Comment by NicolaGiannini** [comment]
Je confirme, testé en Logic.

**Comment by Xon77** [comment]
J'obtiens le même comportement étrange avec Reaper & Open Stage Control

**Comment by belangeo** [comment]
Je n'arrive pas à reproduire avec Reaper et Open Stage Control sous linux... Je vais tester plus tard sous MacOS.

**Comment by Normandeau** [comment]
V109
Avec la nouvelle version de ControlGrisOSC (Added an OSC plugin ID) de OpStaCon, tout semble rentré dans l'ordre. À confirmer.

**Comment by NicolaGiannini** [comment]
C'est ok pour moi aussi!

**Comment by Normandeau** [comment]
Réglé
