### ISSUE TITLE
Dans Open Stage Control il est possible de sélectionner Symmetric X et Y même en mode multicanal. 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/ControlGris#98]
Dans ControlGRIS les "Source Link"" Symmetric X" et "Y" ne sont pas sélectionables si les sources sont plus de 2. Mais on peut toujours sélectionner  "Symmetric X" et "Y" en OSC. Cela n’est pas vraiment un bouge de ControlGRIS mais j’ai pensé de le signaler.

**Comment by Normandeau** [comment]
Bonne remarque. En fait, je pense que c'est un problème.
Car non seulement on peut les sélectionner avec Open Stage Control, mais c'est surtout que Symmetric X ou Y apparaissent en clair (et non pas en grisé) dans ControlGRIS, comme s'ils avaient été vraiment sélectionnés et disponibles. Cela peut engendrer de la confusion chez les utilisateurs. En octo ici:

![Symmetric Y en clair](https://user-images.githubusercontent.com/8959779/77314381-ee4eca00-6cdb-11ea-92a3-92d0c9d3f7df.jpg)

**Comment by Normandeau** [comment]
Et cela nous renvoie ensuite à #97

**Comment by Xon77** [comment]
C’est là qu’un peu de programmation va être nécessaire dans OSC pour qu’il puisse changer l’interface en fonction du nombre de sources (2 ou plus). 
Pour la prochaine version du Lemur (à venir), cela ne posera pas de problème, à partir du moment où l’ajout d’une référence / adresse OSC pour le nombre de sources sera ajoutée.
Mais, ne connaissant pas suffisamment OSC, je ne sais pas comment cela est possible.

**Comment by belangeo** [comment]
J'ai empêché la sélection de SYMMETRIC X ou Y à partir d'un message OSC si dans un autre mode que stéréo dans le ControlGris. Ça ne change pas qu'on peut toujours sélectionner les links symmetric dans OSC mais ça c'est un autre problème!

**Comment by Xon77** [comment]
Merci Olivier, serait-il possible d'avoir une référence / adresse OSC pour le nombre de sources, afin de pouvoir changer l'interface en conséquence, dans le Lemur ou OSC, le cas échéant ?

**Comment by belangeo** [comment]
On est d'accord que la valeur de « First Source ID » n'est jamais la même pour différents plugins dans une même session? Je pourrais glisser cette valeur dans le nom des messages que reçoit et envoie ControlGris.

**Comment by Xon77** [comment]
En effet, la valeur de « First Source ID » n'est jamais la même pour différents plugins dans une même session, mais je ne vois pas comment le Lemur ou Open Stage Control saura le nombre de sources avec cette info ?

**Comment by belangeo** [comment]
Oh désolé, j'ai lu ta question trop vite! Tu voudrais que le ControlGris envoie un messages OSC avec le nombre de sources en argument? Comme:

/controlgris/numOfSources <current number of sources>

Pas de probème! Cependant, je ne donnerais pas cette option dans l'autre sens... Il me semble risqué de pouvoir changer le nombre de sources via un contrôleur externe. D'accord sur ce point?

**Comment by Xon77** [comment]
Je pense qu'une adresse OSC pour le nombre de sources est la seule manière pour changer l'interface en conséquence dans le Lemur ou Open Stage Control.
Peut-être y a t-il une meilleure solution ?
Et oui, que dans un sens, si cela te semble risqué. 
Mais @Normandeau, et autres, voudrait-on pouvoir changer le nombre de sources via un contrôleur externe ?

**Comment by Normandeau** [comment]
«D'accord sur ce point?»
Absolument.

**Comment by Normandeau** [comment]
V109
Réglé
