### ISSUE TITLE
Saved, Not Saved, Automated et Spans Link

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ControlGris#99]
ControlGRIS V108
Je travaille sur le manuel, oh joie! À propos des presets, voici le constat.
What is saved, not saved and what can automated and what should be saved

Saved with Presets:
• Source 1 position Azimuth-Distance-Elevation (automated)
• Spans link (can't be automated)
Question: je sais qu'on a déjà décidé cela, mais **est-ce que le Spans link ne devrait pas être automatisable?** Donc ne pas faire partie des presets?

Not saved but can be automated:
• Spans
• Source Link and Source Link Alt
• Presets
• Bypass

Not saved and not automated:
• Trajectory Type
• Dur per cycle
• Sec(s)/Beat(s)
• Number of cycles dampening
• Back & Forth
• Activate

Rien n'est sauvegardé dans le panneau Configuration
**Est-ce que toutes les informations de Settings ne devraient pas être sauvegardés dans les presets?**
Dans Controllers, les informations de Send on port: IP devraient être sauvegardés dans les presets (ce sont plus ou moins toujours les mêmes valeurs, Or elles se resettent à chaque occurence de ControGRIS et il faut toujours les replacer manuellement).

**Comment by Normandeau** [comment]
Oublié la question: Qu'en dites-vous?

**Comment by Xon77** [comment]
Selon moi, 

- le span link ne devrait pas être automatisable, puisque l'info de chaque span est déjà automatisable.

- les informations de Settings ne devraient pas (obligatoirement) être sauvegardés dans les presets.
Dans Controllers, les informations de Send on port: IP ne sont pas forcément les mêmes valeurs et dépend de chaque application (Lemur, Open Stage Control ou d'autres à venir)
Par exemple, pour le Lemur, il ne reçoit exclusivement que sur le port 8000 et non 9000, comme c'est le cas pour Open Stage Control (ceci dit, on peut l'éditer dans Open Stage Control).

**Comment by belangeo** [comment]
- En effet, automatiser le spans link entre en conflit avec l'automation des spans eux-même.
- Les infos de settings sont, selon moi, des infos qui ne doivent pas changer en milieu de séquence. Elles ne devraient donc pas faire partie des presets (elles font déjà partie des "settings" du plugin, donc sauvegardées avec la session).
- Idem pour les infos dans Controllers. Ces infos font partie des "settings" du plugin, alors il est possible de se faire un template avec des numéros de port particuliers (sauvegardé en tant que preset du DAW, pas dans le système de presets interne du plugin). De plus, changer de numéro de port implique de se déconnecter du port courant puis de se reconnecter sur le nouveau port, opération qui prend un temps qui se compte probablement en seconde... Les preset du plugin doivent agir sans délai...

**Comment by NicolaGiannini** [comment]
Maintenant on gère les spans individuels par les automations et pas par les preset, donc peut être que c'est pas trop sensé de gérer les Span Link par les preset.

**Comment by NicolaGiannini** [comment]
il y a peut-être une autre chose à considérer : les spans link ne fonctionne pas si activé après l'enregistrement d'une automation. 
Je m'explique.
J'enregistre une automation du Azimuth Span
Je arrête la session
j'active le Span Link
je mets en play
L'Elevation Span ne suive pas l'azimuth Span.

Peut-être que ne rendent pas le bouton Span Links enregistrable dans les presets et les automations serait plus pratique donc? 
Je pense cependant que l'effet du bouton Spans Links devrait toujours être enregistré dans les automations.

**Comment by Xon77** [comment]
Selon moi, les spans links devraient servir à l'enregistrement de l'automation et ne sont pas à considérer dans la lecture de l'automation. Une automation, juste pour les span link, risque d'alourdir le nombre d'automations pour une piste de manière superflue. Mais, c'est juste un avis...

**Comment by belangeo** [comment]
D'accord avec Christophe... De plus, il y a toujours le problème de conflit entre les automations.

**Comment by NicolaGiannini** [comment]
Je suis d'accord avec vous.

Dans mon commentaire precedente je voulais signaler que maintenant si on active le Span Links fonctionne que en manipulation direct mais pas avec les automations.

**Comment by Xon77** [comment]
En effet, c'est à mentionner dans la documentation.

**Comment by Normandeau** [comment]
Merci pour vos commentaires. Les infos sont dans le manuel. Mais une des choses que j'essaie d'éviter dans le manuel, ce sont des renvois à des situations multiples et complexes. Autrement dit: une fonction = une explication. Le problème avec le Span Link c'est que selon les différents réglages, on obtient des fonctionnements différents. Le cas soulevé par Nicola illustre bien la chose. 
**Suggestion alors: pourquoi est-ce que le Span Link ne fonctionnerait pas comme les deux boutons Activate: ni dans les presets, ni automatisable?** Utilisable seulement à la demande. Comme Activate, il fonctionne autant en lecture qu'en enregistrement, mais aussitôt que le séquenceur est stoppé, il se désactive. Ainsi la fonction est préservée et le comportement est constant et cohérent avec le reste.
Qu'en dites-vous?

**Comment by NicolaGiannini** [comment]
Je suis d'accord avec Robert! Je m'en servirais, je peux déjà imaginer le cas où j'enregistre une automatisation pour le Azimuth Span et après quelques minutes, je veux essayer l'effets sur les deux spans.

**Comment by belangeo** [comment]
> mais aussitôt que le séquenceur est stoppé, il se désactive.

Est-ce bien n/cessaire? Il me semble que ça implique de cliquer sur deux boutons (Activate et SpanLink) chaque fois qu'on fait un test pour préparer un enregistrement...

**Comment by Normandeau** [comment]
Il y a déjà deux boutons Activate.

**Comment by Normandeau** [comment]
Donc un de plus ou un de moins pour assurer une certaine cohérence.
C'est ce qu'on fait.

**Comment by belangeo** [comment]
Kidou!

**Comment by Normandeau** [comment]
V109
Fiou, réglé!
